---
description: 本章介绍了如何在FreeBSD上安装和配置Wayland和合成器，以提供图形用户环境。
next: books/handbook/network
part: 第一部分：入门指南
path: /books/handbook/
prev: books/handbook/x11
showBookMenu: true
tags: '["Wayland", "XWayland", "KDE", "Plasma", "Xfce", "Gnome", "Intel", "AMD", "NVIDIA", "Wayfire", "Sway", "Hikari"]'
title: '第六章 Wayland'
weight: 8
---

[[wayland]]
= 在FreeBSD上的Wayland
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/wayland/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[] include::shared/{{% lang %}}/teams.adoc[] include::shared/{{% lang %}}/mailing-lists.adoc[] include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[wayland-synopsis]]
== Wayland概述
Wayland是一个新的显示服务器，但它与Xorg在几个重要方面有所不同。首先，Wayland只是一个协议，充当客户端之间的中介，使用不同的机制来消除对X服务器的依赖。Xorg包括X11协议，用于运行远程显示，并且X服务器将接受连接并显示窗口。在Wayland下，合成器或窗口管理器提供显示服务器，而不是传统的X服务器。

由于Wayland不是一个X服务器，传统的X屏幕连接需要使用其他方法，如VNC或RDP来进行远程桌面管理。其次，Wayland可以作为一个独立实体来管理客户端和合成器之间的复合通信，而不需要支持X协议。

Wayland相对较新，不是所有的软件都已经更新以在没有`Xwayland`支持的情况下本地运行。因为Wayland不提供X服务器，并且期望合成器提供该支持，尚不支持Wayland的X11窗口管理器将要求不使用`-rootless`参数启动`Xwayland`。移除`-rootless`参数后，将恢复X11窗口管理器的支持。

[NOTE]
====
当前的NVIDIA(R)驱动程序应该能够与大多数wlroots合成器配合使用，但可能会有一些不稳定性，并且在此时可能不支持所有功能。我们请求志愿者帮助改进NVIDIA(R) DRM。
====

目前，许多软件在Wayland上可以正常运行，包括Firefox。还有一些可用的桌面环境，比如Compiz Fusion的替代品Wayfire，以及i3窗口管理器的替代品Sway。

[NOTE]
====
截至2021年5月，plasma5-kwin在FreeBSD上支持Wayland。要在Wayland下使用Plasma，请使用`ck-launch-session`的`startplasma-wayland`参数，并使用以下命令将dbus与其绑定：`ck-launch-session dbus-run-session startplasma-wayland`。这样可以使其正常工作。
====

对于合成器来说，必须存在支持man:evdev[4]驱动程序的内核才能利用按键绑定功能。这在默认情况下已经内置在[.filename]#GENERIC#内核中；然而，如果内核被定制并且去除了man:evdev[4]支持，那么就需要加载man:evdev[4]模块。此外，使用`Wayland`的用户还需要是`video`组的成员。要快速进行此更改，请使用`pw`命令：

[source, shell]
----
pw groupmod video -m user
----

安装Wayland很简单；协议本身没有太多的配置。大部分的组合将取决于所选择的合成器。通过现在安装`seatd`，可以跳过合成器安装和配置的一步，因为`seatd`需要提供对某些设备的非root访问权限。

这里描述的所有合成器都应该与package:graphics/drm-kmod[]开源驱动程序配合使用；然而，使用专有驱动程序时，NVIDIA(R)显卡可能会出现问题。首先安装以下软件包：

[source, shell]
----
# 安装 wayland seatd 包
----

一旦协议和支持包被安装，合成器必须创建用户界面。接下来的几节将介绍几种合成器。所有使用Wayland的合成器都需要在环境中定义一个运行时目录，可以通过在Bourne shell中使用以下命令来实现：

[source, shell]
----
% export XDG_RUNTIME_DIR=/var/run/user/`id -u`
----

需要注意的是，大多数合成器会在XDG_RUNTIME_DIR目录中搜索配置文件。在这里包含的示例中，将使用一个参数来指定一个配置文件在[.filename]#~/.config#中，以便将临时文件和配置文件分开存放。建议为每个合成器配置一个别名，以加载指定的配置文件。

[WARNING]
====
据报道，ZFS用户可能会在某些Wayland客户端上遇到问题，因为它们需要在运行时目录中访问`posix_fallocate()`函数。尽管作者无法在他们的ZFS系统上重现此问题，但建议的解决方法是不要将ZFS用于运行时目录，而是使用`tmpfs`作为[.filename]#/var/run#目录。在这种情况下，通过命令`mount -t tmpfs tmpfs /var/run`将`tmpfs`文件系统挂载到[.filename]#/var/run#，然后通过[.filename]#/etc/fstab#使此更改在重新启动后持久化。可以配置XDG_RUNTIME_DIR环境变量以使用[.filename]#/var/run/user/$UID#，避免与ZFS可能存在的问题。在查看以下部分的配置示例时，请考虑这种情况。
====

seatd守护进程帮助在合成器中管理非root用户对共享系统设备的访问，包括图形卡。对于传统的X11管理器，如Plasma和GNOME，不需要使用`seatd`，但对于这里讨论的Wayland合成器，在启动合成器环境之前，需要在系统上启用并运行它。要立即启用和启动`seatd`守护进程，并在系统初始化时启动：

[source, shell]
----
# sysrc seatd_enable=”YES”
# service seatd start
----

之后，需要安装一个类似于X11桌面的合成器(compositor)来创建GUI环境。这里讨论了三种合成器，包括基本配置选项、设置屏幕锁定以及获取更多信息的建议。

[[wayland-wayfire]]
== Wayfire合成器

Wayfire是一个旨在轻量化和可定制化的合成器。它提供了多种功能，并且还恢复了之前发布的Compiz Fusion桌面的一些元素。所有的部分在现代硬件上看起来都很漂亮。要启动和运行Wayfire，请先安装所需的软件包：

[source, shell]
----
# 安装 wayfire wf-shell alacritty swaylock-effects swayidle wlogout kanshi mako wlsunset 包
----

`alacritty`软件包提供了一个终端仿真器。然而，并不完全需要它，因为其他终端仿真器如`kitty`和XFCE-4 `Terminal`已经在Wayfire合成器下进行了测试和验证。Wayfire的配置相对简单；它使用一个文件，应该对其中的任何自定义进行审查。要开始，将示例文件复制到运行时环境配置目录，然后编辑该文件：

[source, shell]
----
% mkdir ~/.config/wayfire
% cp /usr/local/share/examples/wayfire/wayfire.ini ~/.config/wayfire
----

对于大多数用户来说，默认设置应该是可以的。在配置文件中，像著名的 `cube` 这样的项目已经预先配置好了，并且有说明来帮助设置可用的选项。一些值得注意的主要设置包括：

[.programlisting]
....
[output]
mode = 1920x1080@60000
position = 0,0
transform = normal
scale = 1.000000
....

在这个例子中，从配置文件中，屏幕的输出应该是列表中列出的模式和列表中列出的赫兹。例如，模式应该设置为`宽度x高度@刷新率`。位置将输出放置在指定的像素位置上。默认值对大多数用户来说应该是可以接受的。最后，transform设置了背景变换，scale将输出按指定的比例因子进行缩放。这些选项的默认值通常是可以接受的；有关更多信息，请参阅文档。

如前所述，Wayland是一种新的协议，还不是所有的应用程序都能与之兼容。目前，`sddm`似乎不支持在Wayland中启动和管理合成器。在这些示例中，使用了`swaylock`实用程序。配置文件中包含了运行`swayidle`和`swaylock`来处理屏幕空闲和锁定的选项。

当系统处于空闲状态时，可以使用此选项来定义要执行的操作。

[.programlisting]
....
idle = swaylock
....

锁超时是通过以下行进行配置的：

[.programlisting]
....
[idle]
toggle = <super> KEY_Z
screensaver_timeout = 300
dpms_timeout = 600
....

第一个选项将在300秒后锁定屏幕，再过300秒后，屏幕将通过`dpms_timeout`选项关闭。

需要注意的最后一件事是<super>键。大多数配置都提到了这个键，它是键盘上的传统“Windows”键。大多数键盘都有这个超级键可用；然而，如果该键不可用，应在此配置文件中重新映射它。例如，要锁定屏幕，请按住超级键，kbd:[shift]键，然后按下kbd:[escape]键。除非映射已更改，否则这将执行swaylock应用程序。`swaylock`的默认配置将显示一个灰色屏幕；然而，该应用程序可以高度自定义，并且有很好的文档。此外，由于安装的是swaylock-effects版本，因此有几个可用的选项，例如模糊效果，可以使用以下命令查看：

[source, shell]
----
% swaylock --effect-blur 7x5
----

还有一个`--clock`参数，它会在锁屏界面上显示一个带有日期和时间的时钟。当安装了`x11/swaylock-effects`软件包时，会包含一个默认的`pam.d`配置文件。它提供了适用于大多数用户的默认选项。还有更高级的选项可用；有关更多信息，请参阅PAM文档。

此时，是时候测试Wayfire并查看它是否能在系统上启动了。只需输入以下命令：

[source, shell]
----
% wayfire -c ~/.config/wayfire/wayfire.ini
----

现在，合成器应该开始运行，并在屏幕顶部显示一个背景图像和一个菜单栏。Wayfire将尝试列出已安装的兼容应用程序，并在此下拉菜单中呈现它们；例如，如果安装了XFCE-4文件管理器，它将显示在此下拉菜单中。如果特定应用程序与键盘快捷键兼容且足够有价值，可以使用[.filename]#wayfire.ini#配置文件将其映射到键盘序列。Wayfire还有一个名为Wayfire Config Manager的配置工具。它位于下拉菜单栏中，但也可以通过终端发出以下命令来启动：

[source, shell]
----
% wcm

wcm是Web内容管理的缩写，指的是一种用于管理和发布网站内容的技术和工具。它可以帮助网站管理员和内容创作者轻松地创建、编辑和发布网站上的内容。通过使用wcm，用户可以方便地管理网站的布局、样式和多媒体内容，同时也可以进行版本控制和权限管理。wcm还提供了一些高级功能，如工作流程管理、多语言支持和搜索引擎优化等，以提升网站的效率和用户体验。
----

通过这个应用程序，可以启用、禁用或配置各种Wayfire配置选项，包括合成特效。此外，为了提供更用户友好的体验，可以在配置文件中启用背景管理器、面板和停靠应用程序。

[.programlisting]
....
panel = wf-panel
dock = wf-dock
background = wf-background
....

[WARNING]
====
通过 `wcm` 进行的更改将覆盖 [.filename]#wayfire.ini# 配置文件中的自定义更改。强烈建议备份 [.filename]#wayfire.ini# 文件，以便可以恢复任何重要的更改。
====

最后，在 [.filename]#wayfire.ini# 中列出的默认启动器是 package:x11/wf-shell[]，用户可以根据需要替换为其他面板。

[[wayland-hikari]]
== Hikari Compositor

Hikari合成器使用了几个以提高生产力为中心的概念，例如sheets（工作表）、workspaces（工作区）等等。从这个角度来看，它类似于平铺式窗口管理器。具体来说，合成器从一个单一的工作区开始，类似于虚拟桌面。Hikari使用一个单一的工作区或虚拟桌面进行用户交互。工作区由多个视图组成，这些视图是合成器中的工作窗口，分组为sheets（工作表）或groups（组）。sheets（工作表）和groups（组）都由一组视图组成，即被分组在一起的窗口。在sheets（工作表）或groups（组）之间切换时，活动的sheet（工作表）或group（组）将被统称为工作区。手册将详细介绍每个功能，但在本文档中，只需考虑一个使用单个sheet（工作表）的工作区。Hikari的安装将包括一个单一的软件包package:x11-wm/hikari[]和一个终端模拟器`alacritty`。

[source, shell]
----
# 安装 hikari 和 alacritty 包
----

[NOTE]
====
其他终端，如`kitty`或Plasma的`Terminal`，在Wayland下可以正常工作。用户应该尝试使用他们喜欢的终端编辑器来验证兼容性。
====

Hikari使用一个配置文件[.filename]#hikari.conf#，可以放置在XDG_RUNTIME_DIR目录中，也可以在启动时使用`-c`参数指定。不需要自动启动配置文件，但是可能会使迁移到这个合成器更容易一些。开始配置是创建Hikari配置目录并复制配置文件进行编辑：

[source, shell]
----
% mkdir ~/.config/hikari
% cp /usr/local/etc/hikari/hikari.conf ~/.config/hikari
----

配置被分解为各种部分，如ui、outputs、layouts等等。对于大多数用户来说，默认设置应该可以正常运行；然而，一些重要的更改应该被进行。例如，$TERMINAL变量通常在用户的环境中没有设置。可以更改这个变量或者修改[.filename]#hikari.conf#文件以进行读取。

[.programlisting]
....
terminal = "/usr/local/bin/alacritty"
....

将使用绑定的按键启动`alacritty`终端。在浏览配置文件时，应注意大写字母用于为用户映射键。例如，用于启动终端的kbd:[L]键kbd:[L+Return]实际上是前面讨论过的超级键或Windows徽标键。因此，按住kbd:[L/super/Windows]键并按下kbd:[Enter]键将使用默认配置打开指定的终端仿真器。将其他键映射到应用程序需要创建一个动作定义。为此，动作项应列在动作段中，例如：

[.programlisting]
....
actions {
  terminal = "/usr/local/bin/alacritty"
  browser = "/usr/local/bin/firefox"
}
....

然后，可以将一个动作映射到键盘部分，该部分在绑定部分中定义：

[.programlisting]
....
bindings {
  keyboard {
SNIP
    "L+Return" = action-terminal
    "L+b" = action-browser
SNIP
....

在 Hikari 重新启动后，按住 Windows 徽标按钮并在键盘上按下 kbd:[b] 键将启动网页浏览器。合成器没有菜单栏，建议用户在迁移之前至少设置一个终端仿真器。手册中包含大量的文档，应在进行完整迁移之前阅读。Hikari 的另一个积极方面是，在迁移到合成器时，可以在 Plasma 和 GNOME 桌面环境中启动 Hikari，以便在完全迁移之前进行试用。

在Hikari中锁定屏幕很容易，因为默认的[.filename]#pam.d#配置文件和解锁工具已经与软件包捆绑在一起。锁定屏幕的键绑定是kbd:[L]（Windows徽标键）+ kbd:[Shift] + kbd:[Backspace]。需要注意的是，所有未标记为公共的视图将被隐藏。当屏幕锁定时，这些视图将不接受输入，但要注意敏感信息可能可见。对于一些用户来说，可能更容易迁移到其他屏幕锁定工具，比如在本节中讨论的swaylock-effects。要启动Hikari，请使用以下命令：

[source, shell]
----
% hikari -c ~/.config/hikari/hikari.conf

这是一个命令行指令，它使用hikari配置文件`~/.config/hikari/hikari.conf`来启动hikari。
----

[[wayland-sway]]
== Sway合成器

Sway合成器是一种平铺式合成器，旨在取代i3窗口管理器。它应该与用户当前的i3配置兼容；但是，新功能可能需要一些额外的设置。在接下来的示例中，假设进行了全新安装，没有迁移任何i3配置。要安装Sway和有价值的组件，请以root用户身份执行以下命令：

[source, shell]
----
# 安装 sway swayidle swaylock-effects alacritty dmenu-wayland dmenu 包
----

对于一个基本的配置文件，执行以下命令，然后在复制完成后编辑配置文件：

[source, shell]
----
% mkdir ~/.config/sway
% cp /usr/local/etc/sway/config ~/.config/sway
----

基本配置文件有许多默认值，对于大多数用户来说这是可以的。但是还需要进行一些重要的更改，如下所示：

[.programlisting]
....
# Logo key. Use Mod1 for Alt.
input * xkb_rules evdev
set $mod Mod4
# Your preferred terminal emulator
set $term alacritty
set $lock swaylock -f -c 000000
output "My Workstation" mode 1366x786@60Hz position 1366 0
output * bg ~/wallpapers/mywallpaper.png stretch
### Idle configuration
exec swayidle -w \
          timeout 300 'swaylock -f -c 000000' \
          timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
          before-sleep 'swaylock -f -c 000000'
....

在前面的示例中，加载了`xkb`规则以处理man:evdev[4]事件，并将$mod键设置为Windows徽标键以进行键绑定。接下来，终端仿真器被设置为`alacritty`，并定义了一个屏幕锁定命令；稍后会详细介绍。输出关键字、模式、位置、背景壁纸以及Sway还被告知将该壁纸拉伸以填满屏幕。最后，设置`swaylock`在300秒超时后将屏幕或监视器锁定并进入睡眠模式。在这里还定义了锁定的背景颜色为000000，即黑色。使用swaylock-effects，还可以使用`--clock`参数显示时钟。有关更多选项，请参阅手册页。还应该查看man:sway-output[5]手册页；它包含了大量关于自定义输出选项的信息。

在Sway中，要打开应用程序菜单，请按住Windows徽标键（mod键）并按下kbd:[d]键。可以使用键盘上的箭头键来导航菜单。还有一种方法可以操作栏的布局并添加一个托盘；请阅读man:sway-bar[5]手册页面获取更多信息。默认配置在右上角添加了日期和时间。在配置文件的`Bar`部分中可以找到一个示例。默认情况下，配置不包括在上面的示例之外锁定屏幕，启用锁定计时器。创建一个锁定键绑定需要在`Key bindings`部分添加以下行：

[.programlising]
....
# Lock the screen manually
bindsym $mod+Shift+Return exec $lock
....

现在可以使用按住Windows徽标键、按住Shift键，最后按下回车键的组合来锁定屏幕。当安装了Sway，无论是从软件包还是FreeBSD Ports Collection安装的，都会安装一个默认的[.filename]#pam.d#文件。默认配置对大多数用户来说应该是可接受的，但也提供了更高级的选项。请阅读PAM文档以获取更多信息。

最后，要退出Sway并返回到shell，请按住Windows徽标键和Shift键，然后按下键盘上的[e]键。会显示一个提示，其中有一个选项可以退出Sway。在迁移期间，可以通过在诸如Plasma之类的X11桌面上的终端模拟器中启动Sway。这使得在完全迁移到这个合成器之前，测试不同的更改和键绑定变得更加容易。要启动Sway，请执行以下命令：

[source, shell]
----
% sway -c ~/.config/sway/config

在这个命令中，`sway` 是一个用于窗口管理器的程序。`-c` 参数用于指定配置文件的路径，`~/.config/sway/config` 是配置文件的路径。通过执行这个命令，可以启动 `sway` 窗口管理器，并加载指定路径下的配置文件。
----

[[wayland-xwayland]]
== 使用Xwayland

在安装Wayland时，除非Wayland是没有构建X11支持的，否则应该已经安装了`Xwayland`二进制文件。如果[.filename]#/usr/local/bin/Xwayland#文件不存在，请使用以下命令进行安装：

[source, shell]
----
# 安装 xwayland-devel 包
----

[NOTE]
====
推荐使用Xwayland的开发版本，并且很可能已经随Wayland软件包一起安装。每个合成器都有一种启用或禁用此功能的方法。
====

一旦安装了`Xwayland`，请在所选的合成器中进行配置。对于Wayfire来说，在[.filename]#wayfire.ini#文件中需要添加以下行：

[.programlisting]
....
xwayland = true
....

对于Sway合成器，默认情况下应启用`Xwayland`。即便如此，建议在[.filename]#~/.config/sway/config#中手动添加以下配置行：

[.programlisting]
.....
启用XWayland
.....

最后，对于Hikari来说，不需要进行任何更改。默认情况下，已经内置了对`Xwayland`的支持。要禁用该支持，可以从ports集合中重新构建该软件包，并在那时禁用Xwayland支持。

在进行这些更改后，通过命令行启动合成器，并从键绑定中执行一个终端。在这个终端中，输入`env`命令并搜索`DISPLAY`变量。如果合成器能够正确启动Xwayland X服务器，这些环境变量应该类似于以下内容：

[source, shell]
----
% env | grep DISPLAY
% env | grep DISPLAY
----

[.programlisting]
....
WAYLAND_DISPLAY=wayland-1
DISPLAY=:0
....

在这个输出中，有一个默认的Wayland显示器和一个为Xwayland服务器设置的显示器。验证`Xwayland`是否正常工作的另一种方法是安装和测试小包：[x11/eyes]，并检查输出。如果`xeyes`应用程序启动并且眼睛跟随鼠标指针移动，那么Xwayland正常工作。如果显示了以下错误或类似错误，则在`Xwayland`初始化过程中发生了某些问题，可能需要重新安装：

[.programlisting]
....
Error: Cannot open display wayland-0
....

[WARNING]
====
Wayland的一个安全特性是，在没有运行X服务器的情况下，没有其他网络监听器。一旦启用了`Xwayland`，这个安全特性对系统就不再适用。
====

对于一些复合器，比如Wayfire，`Xwayland`可能无法正常启动。因此，`env`将显示`DISPLAY`环境变量的以下信息：

[source, shell]
----
% env | grep DISPLAY
% env | grep DISPLAY
----

[.programlisting]
....
DISPLAY=wayland-1
WAYLAND_DISPLAY=wayland-1
....

尽管已经安装和配置了`Xwayfire`，但X11应用程序无法启动，出现显示问题。为了解决这个问题，可以通过以下两种方法验证是否已经存在一个使用UNIX套接字的`Xwayland`实例。首先，检查`sockstat`的输出，并搜索X11-unix:

[source, shell]
----
% sockstat | grep x11
----

应该有类似以下信息的内容：

[.programlisting]
....
trhodes  Xwayland   2734  8  stream /tmp/.X11-unix/X0
trhodes  Xwayland   2734  9  stream /tmp/.X11-unix/X0
trhodes  Xwayland   2734  10 stream /tmp/.X11-unix/X0
trhodes  Xwayland   2734  27 stream /tmp/.X11-unix/X0_
trhodes  Xwayland   2734  28 stream /tmp/.X11-unix/X0
....

这表明存在一个X11套接字。可以通过在合成器下运行的终端模拟器中尝试手动执行`Xwayland`来进一步验证：

[source, shell]
----
% Xwayland是一个允许在Wayland显示服务器上运行X11应用程序的兼容层。它允许用户在Wayland环境中使用传统的X11应用程序，并提供了与X11协议的兼容性。Xwayland是Wayland项目的一部分，旨在逐步替代X Window System，并为用户提供更现代化的图形显示体验。
----

如果已经存在一个X11套接字，则应向用户显示以下错误：

[.programlisting]
....
(EE)
Fatal server error:
(EE) Server is already active for display 0
	If this server is no longer running, remove /tmp/.X0-lock
	and start again.
(EE)
....

由于存在一个可用的活动X显示器，使用显示器零，环境变量设置不正确，要修复这个问题，将`DISPLAY`环境变量更改为`:0`，然后尝试再次执行应用程序。以下示例使用`package:mail/claws-mail[]`作为需要`Xwayland`服务的应用程序：

[source, shell]
----
导出 DISPLAY=:0
----

在这个改变之后，package:mail/claws-mail[]应用程序现在应该开始使用`Xwayland`并正常工作。

[[wayland-remotedesktop]]
== 使用VNC进行远程桌面访问

在本文档中早些时候已经指出，Wayland不像Xorg提供相同的X服务器样式访问。相反，用户可以自由选择远程桌面协议，如RDP或VNC。FreeBSD Ports集合中包括`wayvnc`，它将支持基于wlroots的合成器，例如在这里讨论的合成器。可以使用以下命令安装此应用程序：

[source, shell]
----
# 安装 wayvnc 包
----

与其他一些软件包不同，`wayvnc` 不提供配置文件。幸运的是，手册页面记录了重要的选项，并且可以将它们推导成一个简单的配置文件：

[.programlisting]
....
address=0.0.0.0
enable_auth=true
username=username
password=password
private_key_file=/path/to/key.pem
certificate_file=/path/to/cert.pem
....

需要生成密钥文件，并强烈建议使用它们以增加连接的安全性。当调用时，wayvnc将在[.filename]#~/.config/wayvnc/config#中搜索配置文件。可以使用`-C configuration_file`选项在启动服务器时覆盖该文件。因此，要启动`wayvnc`服务器，请执行以下命令：

[source, shell]
----
% wayvnc -C ~/.config/wayvnc/config

将wayvnc配置文件设置为~/.config/wayvnc/config。
----

[NOTE]
====
在撰写本文时，系统初始化时没有rc.d脚本来启动`wayvnc`。如果需要这个功能，需要创建一个本地启动文件。这可能是对端口维护者的一个功能请求。
====

[[wayland-ly]]
== Wayland登录管理器
虽然存在多个登录管理器，并且正在逐渐迁移到Wayland，但其中一个选择是`ly`包中的文本用户界面（TUI）管理器。`ly`只需要最少的配置，它会在系统初始化时显示一个登录窗口来启动Sway、Wayfire等桌面环境。要安装`ly`，请执行以下命令：

[source, shell]
----
# 安装 ly 包
----

将会提供一些配置提示，导入步骤是将以下行添加到 [.filename]#/etc/gettytab# 文件中：

[programlisting]
....
Ly:\
  :lo=/usr/local/bin/ly:\
  :al=root:
....

然后在[.filename]#/etc/ttys#中修改ttyv1行，使其与以下行匹配：

[programlisting]
....
ttyv1 "/usr/libexec/getty Ly" xterm onifexists secure
....

系统重新启动后，应该出现登录界面。要配置特定的设置，例如语言和编辑[.filename]#/usr/local/etc/ly/config.ini#。至少，这个文件应该有之前在[.filename]#/etc/ttys#中指定的终端。

[NOTE]
====
如果将ttyv0设置为登录终端，可能需要按下kbd:[alt]和kbd:[F1]键才能正确显示登录窗口。
====

当登录窗口出现时，使用左右箭头可以在不同支持的窗口管理器之间切换。

[[wayland-utilities]]
== 有用的工具

所有合成器都可以使用的一个有用的Wayland实用程序是waybar。虽然Wayfire带有一个启动菜单，但一个易于使用和快速的任务栏对于任何合成器或桌面管理器来说都是一个很好的附件。一个快速且易于配置的Wayland兼容的任务栏是waybar。要安装该软件包和一个支持音频控制的实用程序，请执行以下命令：

[source, shell]
----
# 安装 pavucontrol 和 waybar 包
----

要创建配置目录并复制默认配置文件，请执行以下命令：

[source, shell]
----
% mkdir ~/.config/waybar
% cp /usr/local/etc/xdg/waybar/config ~/.config/waybar
----

`lavalauncher`实用程序为各种应用程序提供了一个启动栏。软件包中没有提供示例配置文件，因此必须执行以下操作：

[source, shell]
----
创建一个名为"~/.config/lavalauncher"的文件夹。
----

下面是一个只包含Firefox的示例配置文件，并且放置在右侧：

[.programlising]
....
global-settings {
	watch-config-file = true;
}

bar {
	output            = eDP-1;
	position          = bottom;
	background-colour = "#202020";

	# Condition for the default configuration set.
	condition-resolution = wider-than-high;

	config {
		position = right;
	}

	button {
		image-path          =     /usr/local/lib/firefox/browser/chrome/icons/default/default48.png;
		command[mouse-left] =     /usr/local/bin/firefox;
	}
	button {
	  image-path           =   /usr/local/share/pixmaps/thunderbird.png;
	  command[mouse-left]  =   /usr/local/bin/thunderbird;
}
....
