---
description: 'FreeBSD 新手会发现本书的第一部分指导用户完成 FreeBSD 安装过程，并轻松地介绍了支撑 UNIX 的概念和约定。'
next: books/handbook/parti
path: /books/handbook/
prev: books/handbook
showBookMenu: true
tags: ["preface", "audience", "organization", "conventions", "acknowledgments"]
title: 前言
weight: 1
---

[preface]
[[book-preface]]
= 前言
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/preface/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[preface-audience]]
== 预期读者

FreeBSD 新手会发现本书的第一部分指导用户完成 FreeBSD 安装过程，并轻松地介绍了 UNIX(R) 的概念和约定。阅读这一部分只需要有探索的愿望，以及接受新概念的能力。

一旦你走到这一步，手册的第二部分，也是更大的部分，是一个对 FreeBSD 系统管理员感兴趣的各种主题的全面参考。其中一些章节可能会建议你先阅读一些内容，在每个章节的简介中会有注明。

有关更多信息来源的列表，请参见 crossref:bibliography[bibliography,参考文献]。

[[preface-changes-from4]]
== 第四版

当前版本的手册代表了一个工作组的累积努力，该工作组一直在审查和更新所有手册内容。以下是自第四版手册以来的主要更新。

* 手册已从 link:https://docbook.org/[Docbook] 转换为 link:https://gohugo.io/[Hugo] 和 link:https://asciidoctor.org/[AsciiDoctor]。
* link:https://docs.FreeBSD.org[FreeBSD 文档门户] 已创建。
* 添加了 crossref:wayland[wayland,Wayland]，其中包含在 FreeBSD 下安装和配置 Wayland 的信息。
* crossref:bibliography[bibliography,参考文献] 已经进行了广泛的更新。


[[preface-changes-from3]]
== 第三版

当前在线版本的手册代表了过去 10 年来数百名贡献者的累积努力。以下是自 2004 年出版第三版两卷本以来的一些重大变化：

* 添加了 crossref:wine[wine,WINE]，关于如何在 FreeBSD 上运行 Windows(R) 应用程序的信息。
* crossref:dtrace[dtrace,DTrace] 添加了有关功能强大的 DTrace 性能分析工具的信息。
* crossref:filesystems[filesystems,其他文件系统] 添加了有关 FreeBSD 中非本地文件系统的信息，如 Sun(TM) 的 ZFS。
* crossref:audit[audit,安全事件审计] 增加了关于 FreeBSD 中新的审计功能的信息，并解释了其用途。
* crossref:virtualization[virtualization,虚拟化] 添加了有关在虚拟化软件上安装 FreeBSD 的信息。的信息。
* crossref:bsdinstall[bsdinstall,安装 FreeBSD] 新增了使用新安装程序 bsdinstall 安装 FreeBSD 的内容。

[[preface-changes-from2]]
== 第二版（2004 年）

第三版是 FreeBSD 文档项目专注成员超过两年工作的巅峰之作。印刷版的规模增长到了需要分为两卷出版的程度。以下是这个新版中的主要变化：

* crossref:config[config-tuning ,配置和调优] 增加了关于 ACPI 电源和资源管理、`cron` 系统实用程序以及更多内核调优选项的新信息。
* crossref:security[security, Security] 增加了关于虚拟私有网络（VPN）、文件系统访问控制列表（ACLs）和安全公告的新信息。
* crossref:mac[mac,Mandatory Access Control] 是本版本的新章节。它解释了 MAC 是什么，以及如何使用这种机制来保护 FreeBSD 系统。
* crossref:disks[disks,Storage] 增加了关于 USB 存储设备、文件系统快照、文件系统配额、文件和网络支持的文件系统以及加密磁盘分区的新信息。
* 向 crossref:ppp-and-slip[ppp-and-slip,PPP] 添加了故障排除部分。
* crossref:mail[mail,电子邮件] 扩展了关于使用替代传输代理、SMTP 身份验证、UUCP、fetchmail、procmail 和其他高级主题的新信息。
* crossref:network-servers[network-servers,网络服务器] 在本版中是全新的。本章包括有关设置 Apache HTTP 服务器、ftpd 以及使用 Samba 为 Microsoft(R) Windows(R) 客户端设置服务器的信息。为了改善呈现效果，一些来自 crossref:advanced-networking[advanced-networking ,高级网络] 的部分内容被移至此处。
* crossref:advanced-networking[advanced-networking,高级网络] 增加了关于在 FreeBSD 上使用蓝牙设备、设置无线网络和异步传输模式（ATM）网络的新信息。
* 添加术语表，以提供一个集中的位置，用于定义整本书中使用的技术术语。
* 对本书中的表格和图表进行了一些美观的改进。

[[preface-changes]]
== 第一版（2001 年）

第二版是 FreeBSD 文档项目专注成员两年多工作的巅峰之作。以下是本版的主要变化：

* 添加完整索引。
* 所有的 ASCII 图形都已被替换为图形化的图表。
* 每个章节都添加了一个标准的简介，以便快速概述该章节包含的信息以及读者应该了解的内容。
* 内容已经在逻辑上重新组织成三个部分：“入门指南”，“系统管理”和“附录”。
* 对 crossref:basics[basics, FreeBSD 基础知识] 进行了扩展，包含了关于进程、守护进程和信号的额外信息。
* 对 crossref:ports[ports ,安装应用程序：软件包和端口] 进行了扩展，包含了关于二进制包管理的额外信息。
* crossref:x11[x11,X Window 系统] 章节完全重写，重点是使用现代桌面技术，如 KDE 和 GNOME 在 XFree86(TM) 4.X 上。
* 对 crossref:boot[boot, FreeBSD 引导过程] 进行了扩展。
* crossref:disks[disks,存储] 一章是由原本分为"磁盘"和"备份"两个章节合并而成的。我们认为将这些主题作为一个单独的章节呈现更容易理解。同时，还添加了一个关于 RAID （硬件和软件）的部分。
* crossref:serialcomms[serialcomms,Serial Communications] 章节完全重新组织和更新，适用于 FreeBSD 4.X/5.X 。
* crossref:ppp-and-slip[ppp-and-slip,PPP] 章节进行了重大更新。
* crossref:advanced-networking[advanced-networking,高级网络] 中添加了许多新的部分。
* 对 crossref:mail[mail ,电子邮件] 进行扩展，包括更多关于配置 sendmail 的信息。
* 对 crossref:linuxemu[linuxemu, Linux® 二进制兼容性] 进行了扩展，包括了安装 Oracle(R) 和 SAP(R) R/3(R) 的信息。
* 本第二版涵盖了以下新主题：

** crossref:config[config-tuning,配置和调优]。
** crossref:multimedia[multimedia,多媒体]。

[[preface-overview]]
== 本书的组织结构

本书分为五个逻辑上独立的部分。第一部分是 _入门_，介绍了 FreeBSD 的安装和基本使用。预计读者会按照章节的顺序阅读，可能会跳过熟悉的主题章节。第二部分是 _常见任务_，介绍了 FreeBSD 的一些常用功能。这部分以及后续的部分可以按任意顺序阅读。每个章节都以简洁的摘要开始，描述了章节内容和读者所需的基础知识。这样可以让读者随意跳转到感兴趣的章节。第三部分是 _系统管理_，介绍了管理主题。第四部分是 _网络通信_，介绍了网络和服务器主题。第五部分包含参考信息的附录。

_crossref:introduction[introduction, 导言]_::
本文向新用户介绍 FreeBSD 。它描述了 FreeBSD 项目的历史、目标和开发模型。

_crossref:bsdinstall[bsdinstall, 安装 FreeBSD]_::
使用 bsdinstall，引导用户完成 FreeBSD 9._x_及更高版本的完整安装过程。

_crossref:basics[basics, FreeBSD 基础知识]_::
介绍了 FreeBSD 操作系统的基本命令和功能。如果您熟悉 Linux(R) 或其他 UNIX(R) 的变种，那么您可能可以跳过本章。

_crossref:ports[ports ,安装应用程序：软件包和 Ports]_::
本文介绍了使用 FreeBSD 创新的“Ports Collection”和标准二进制软件包安装第三方软件的方法。

_crossref:x11[x11, X Window 系统]_::
描述了 X Window System 的一般情况，特别是在 FreeBSD 上使用 X11 的情况。还描述了常见的桌面环境，如 KDE 和 GNOME。

_crossref:wayland[wayland, Wayland]_::
描述了 Wayland 显示服务器的一般情况，特别是在 FreeBSD 上使用 Wayland 的情况。还描述了常见的合成器，如 Wayfire、Hikari 和 Sway。

_crossref:desktop[desktop,桌面应用程序]_::
列举了一些常见的桌面应用程序，如网络浏览器和办公套件，并描述了如何在 FreeBSD 上安装它们。

_crossref:multimedia[multimedia,多媒体]_::
展示了如何为您的系统设置音频和视频播放支持。还介绍了一些示例音频和视频应用程序。

_crossref:kernelconfig[kernelconfig,配置 FreeBSD 内核]_::
解释了为什么您可能需要配置一个新的内核，并提供了详细的配置、构建和安装自定义内核的指令。

_crossref:printing[printing ,打印]_::
描述了在 FreeBSD 上管理打印机的方法，包括有关横幅页面、打印机计费和初始设置的信息。

_crossref:linuxemu[linuxemu , Linux(R) 二进制兼容性]_::
描述了 FreeBSD 的 Linux(R) 兼容功能。还提供了许多流行的 Linux(R) 应用程序（如 Oracle(R) 和 Mathematica(R)）的详细安装说明。

_crossref:wine[wine,WINE]_::
描述了 WINE 并提供了详细的安装说明。还描述了 WINE 的操作方式，如何安装 GUI 助手，如何在 FreeBSD 上运行 Windows(R) 应用程序，并提供其他提示和解决方案。

_crossref:config[config-tuning ,配置和调优]_::
描述了系统管理员可以调整 FreeBSD 系统以获得最佳性能的参数。还描述了在 FreeBSD 中使用的各种配置文件以及它们的位置。

_crossref:boot[boot, FreeBSD 引导过程]_::
描述了 FreeBSD 的启动过程，并解释了如何通过配置选项来控制这个过程。

_crossref:security[security,安全]_::
描述了许多不同的工具，可用于帮助保护您的 FreeBSD 系统的安全性，包括 Kerberos、IPsec 和 OpenSSH。

_crossref:jails[jails,Jails]_::
描述了 FreeBSD 中的 jails 框架以及 jails 相对于传统的 chroot 支持的改进。

_crossref:mac[mac,强制访问控制]_::
解释了强制访问控制（Mandatory Access Control,MAC）是什么，以及如何使用这种机制来保护 FreeBSD 系统。

_crossref:audit[audit,安全事件审计]_::
描述了什么是 FreeBSD 事件审计，如何安装、配置以及如何检查或监控审计日志。

_crossref:disks[disks,存储]_::
描述了如何使用 FreeBSD 管理存储介质和文件系统。这包括物理磁盘、RAID 阵列、光盘和磁带介质、内存支持的磁盘和网络文件系统。

_crossref:geom[geom, GEOM：模块化磁盘转换框架]_::
描述了 FreeBSD 中的 GEOM 框架是什么以及如何配置各种支持的 RAID 级别。

_crossref:zfs[zfs, OpenZFS 存储平台]_::
描述了 OpenZFS 存储平台，并提供了一个快速入门指南，以及关于在 FreeBSD 下运行 OpenZFS 的高级主题的信息。

_crossref:filesystems[filesystems,其他文件系统]_::
研究了 FreeBSD 对非本地文件系统（如 ext2、 ext3 和 ext4）的支持。

_crossref:virtualization[virtualization,虚拟化]_::
描述了虚拟化系统提供的功能以及如何在 FreeBSD 上使用它们。

_crossref:l10n[l10n,本地化 - i18n/L10n 的使用和设置]_::
描述了如何在非英语语言环境中使用 FreeBSD。涵盖了系统和应用程序级别的本地化。

_crossref:cutting-edge[updating-upgrading,更新和升级 FreeBSD]_::
解释了 FreeBSD-STABLE、FreeBSD-CURRENT 和 FreeBSD 发布版之间的区别。描述了哪些用户会从跟踪开发系统中受益，并概述了该过程。介绍了用户可以采取的方法来更新系统到最新的安全发布版。

_crossref:dtrace[dtrace , DTrace]_::
描述了如何在 FreeBSD 上配置和使用 Sun(TM) 的 DTrace 工具。通过进行实时系统分析，动态跟踪可帮助定位性能问题。

_crossref:usb-device-mode[usb-device-mode,USB 设备模式/USB OTG]_::
解释了在 FreeBSD 上使用 USB 设备模式和 USB On The Go（USB OTG）的方法。

_crossref:ppp-and-slip[ppp-and-slip,PPP]_::
描述了如何在 FreeBSD 中使用 PPP 连接到远程系统。

_crossref:mail[mail,电子邮件]_::
解释了电子邮件服务器的不同组件，并深入探讨了最流行的邮件服务器软件 sendmail 的简单配置主题。

_crossref:network-servers[network-servers,网络服务器]_::
提供详细的说明和示例配置文件，以将您的 FreeBSD 机器设置为网络文件系统服务器、域名服务器、网络信息系统服务器或时间同步服务器。

_crossref:firewalls[firewalls, Firewalls]_::
解释了基于软件的防火墙背后的哲学，并提供有关可用于 FreeBSD 的不同防火墙的配置的详细信息。

_crossref:advanced-networking[advanced-networking,高级网络]_::
描述了许多网络主题，包括在局域网上与其他计算机共享互联网连接、高级路由主题、无线网络、蓝牙(R)、ATM、IPv6 等等。

_crossref:mirrors[mirrors,获取 FreeBSD]_::
列出了获取 FreeBSD 光盘或 DVD 的不同来源，以及允许您下载和安装 FreeBSD 的互联网上的不同网站。

_crossref:bibliography[bibliography ,参考文献]_::
这本书涉及了许多不同的主题，可能会让你渴望更详细的解释。参考书目列出了文本中引用的许多优秀书籍。

_crossref:eresources[eresources ,互联网资源]_::
描述了许多可供 FreeBSD 用户发布问题和参与有关 FreeBSD 的技术讨论的论坛。

_crossref:pgpkeys[pgpkeys , OpenPGP 密钥]_::
列出了几位 FreeBSD 开发者的 PGP 指纹。

[[preface-conv]]
== 本书中使用的约定

为了提供一致且易于阅读的文本，本书遵循了几个约定。

[[preface-conv-typographic]]
=== 排版约定

_斜体_::
斜体字用于文件名、URL、强调的文本以及技术术语的首次使用。

`等宽`::
错误消息、命令、环境变量、端口名称、主机名、用户名、组名、设备名、变量和代码片段使用 `等宽字体`。

粗体::
应用程序、命令和按键使用 *粗体* 字体。

[[preface-conv-commands]]
=== 用户输入

键以 *粗体* 显示，以突出显示与其他文本的区别。同时输入的键组合以 `+` 符号分隔键，例如：

kbd:[Ctrl + Alt + Del]

意思是用户应该同时按下 kbd:[Ctrl]、kbd:[Alt] 和 kbd:[Del] 键。

需要按顺序输入的键将用逗号分隔，例如：

kbd:[Ctrl + X]，kbd:[Ctrl + S]

这意味着用户需要同时按下键盘上的 kbd:[Ctrl] 和 kbd:[X] 键，然后再同时按下键盘上的 kbd:[Ctrl] 和 kbd:[S] 键。

[[preface-conv-examples]]
=== 示例

以 [.filename]#C:\># 开头的示例表示一个 MS-DOS(R) 命令。除非另有说明，这些命令可以在现代 Microsoft(R) Windows(R) 环境中的 "Command Prompt" 窗口中执行。

[source, shell]
....
C:\> tools\fdimage floppies\kern.flp A:
....

以 # 开头的示例表示在 FreeBSD 中必须以超级用户身份调用的命令。您可以登录为 `root` 来输入命令，或者登录为您的普通帐户并使用 man:su[1] 来获取超级用户权限。

[source, shell]
....
# dd if=kern.flp of=/dev/fd0
....

以 % 开头的示例表示应从普通用户帐户调用的命令。除非另有说明，设置环境变量和其他 shell 命令使用 C-shell 语法。

[source, shell]
....
% top
....

[[preface-acknowledgements]]
== 致谢

你手中的这本书代表了全球数百人的努力。无论他们是纠正错别字还是提交完整的章节，所有的贡献都是有用的。

几家公司通过支付作者全职工作、出版费用等方式支持了本文档的开发。特别是 BSDi（后来被 Wind River Systems 收购）支付了 FreeBSD 文档项目的成员全职工作，以改进这本书，直到 2000 年 3 月第一版印刷版的出版（ISBN 1-57176-241-8）。随后， http://www.windriver.com[Wind River Systems] 支付了几位额外的作者，改进了印刷输出基础设施，并为文本添加了额外的章节。这项工作最终在 2001 年 11 月出版了第二版印刷版（ISBN 1-57176-303-1）。在 2003 年至 2004 年期间， http://www.freebsdmall.com[FreeBSD Mall,Inc] 支付了几位贡献者，改进了手册，为第三版印刷版做准备。第三版印刷版被分为两卷。两卷都已出版，分别是 The FreeBSD Handbook 3rd Edition Volume 1: User Guide（ISBN 1-57176-327-9）和The FreeBSD Handbook 3rd Edition Volume 2: Administrators Guide（ISBN 1-57176-328-7）。
