---
description: 'FreeBSD 手册术语表'
next: books/handbook/colophon
path: /books/handbook/
prev: books/handbook/pgpkeys
showBookMenu: true
title: 'FreeBSD 词汇表'
weight: 45
---

[glossary]
[[freebsd-glossary]]
= FreeBSD 词汇表
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:!sectnums:
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/glossary/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[] include::shared/{{% lang %}}/teams.adoc[] include::shared/{{% lang %}}/mailing-lists.adoc[] include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

这个词汇表包含了在 FreeBSD 社区和文档中使用的术语和缩写。

[discrete]
== 一个

ACL 是 Access Control List 的缩写，意为访问控制列表。它是一种用于控制对计算机系统资源的访问权限的机制。 ACL 可以定义哪些用户或用户组有权访问特定的文件、目录或网络资源，并可以指定不同的权限级别，如读取、写入或执行。通过 ACL ，系统管理员可以更精细地管理和控制用户对系统资源的访问。::
参见 <<acl-glossary ,访问控制列表 >> 。

高级配置与电源接口（ ACPI ）::
参见 <<acpi-glossary ,高级配置与电源接口 >> 。

AMD 是 Advanced Micro Devices 的缩写，是一家总部位于美国的半导体公司。该公司主要从事计算机处理器、图形处理器和其他相关技术的研发和制造。 AMD 是英特尔公司的主要竞争对手之一，其产品广泛应用于个人电脑、服务器和游戏主机等领域。::
参见《自动挂载守护进程》（ Automatic Mount Daemon ）。

AML 是反洗钱（ Anti-Money Laundering ）的缩写，是一种旨在防止和打击洗钱活动的法律和监管措施。洗钱是指将非法获得的资金通过一系列交易和操作掩盖其来源的行为。 AML 旨在确保金融机构和其他相关实体遵守法律规定的反洗钱要求，以减少洗钱和恐怖主义融资的风险。::
参见 <<aml-glossary , ACPI 机器语言 >> 。

应用程序编程接口（ API ）::
参见 <<api-glossary ,应用程序编程接口 >> 。

APIC 是 Application Programming Interface Controller 的缩写，意为应用程序编程接口控制器。 APIC 是一种硬件设备，用于管理和调度计算机系统中的中断和中断控制器。它负责处理和分发中断请求，以确保系统的正常运行和响应。 APIC 还可以提供高级功能，如多处理器系统中的进程间通信和同步。::
请参阅《高级可编程中断控制器》（ Advanced Programmable Interrupt Controller ）一节。

APM 是应用性能管理的缩写，它是一种用于监控和管理软件应用程序性能的方法和工具。 APM 可以帮助开发人员和运维团队追踪应用程序的性能指标，识别潜在的性能问题，并提供优化建议。通过使用 APM ，组织可以提高应用程序的可靠性、可用性和性能，从而提供更好的用户体验。::
请参阅《高级电源管理》（ Advanced Power Management ） <<apm-glossary>> 。

APOP 是一种用于电子邮件认证的协议。它使用了一种称为挑战 - 响应机制的方式来验证邮件服务器和客户端之间的身份。在 APOP 中，服务器会向客户端发送一个随机的挑战字符串，客户端需要使用预共享的密钥对挑战字符串进行加密，并将结果发送回服务器进行验证。通过这种方式， APOP 可以防止未经授权的访问和邮件欺骗。::
参见《认证邮局协议（ Authenticated Post Office Protocol ）》。

ASL 是美国手语（ American Sign Language ）的缩写。它是一种用手势和面部表情进行交流的语言，主要用于聋人之间的沟通。 ASL 是一种独立的语言，与英语并不相同。它在美国和加拿大广泛使用，并且在全球范围内也有一定的使用者。 ASL 的手势和动作具有丰富的语法和词汇，可以表达复杂的意思和概念。::
请参阅 <<asl-glossary , ACPI 源语言 >> 。

ATA 是一种计算机接口标准，用于连接硬盘驱动器和计算机系统。 ATA 代表“ Advanced Technology Attachment ”，它定义了硬盘驱动器与计算机之间的通信协议和电气接口。 ATA 接口通常用于连接传统的机械硬盘驱动器，但也可以用于连接其他类型的存储设备，如固态硬盘（ SSD ）。 ATA 接口有多个版本，包括 ATA-1 、 ATA-2 、 ATA-3 等，每个版本都有不同的特性和功能。 ATA 接口已经被更先进的接口标准，如 SATA （ Serial ATA ）所取代，但仍然在一些老旧的计算机系统中使用。::
参见《 ATA 词汇表》。

自动取款机::
参见《异步传输模式 (ATM) 术语表》。

[[aml-glossary]]
ACPI 机器语言::
伪代码由一个在符合 ACPI 的操作系统中的虚拟机解释，它在底层硬件和向操作系统呈现的文档化接口之间提供了一层。

[[asl-glossary]]
ACPI 源语言::
AML 是一种编程语言。

[[acl-glossary]]
访问控制列表::
一个附加在对象上的权限列表，通常是文件或网络设备。

[[acpi-glossary]]
高级配置与电源接口::
ACPI 是一种规范，它提供了硬件接口的抽象，使操作系统不需要了解底层硬件即可充分利用它。 ACPI 发展并取代了以前由 APM 、 PNPBIOS 和其他技术提供的功能，并提供了控制功耗、机器暂停、设备启用和禁用等功能。

[[api-glossary]]
应用程序编程接口::
一组程序、协议和工具，用于指定一个或多个程序部分之间的规范交互方式；它们如何、何时以及为什么协同工作，以及它们共享或操作的数据。

[[apm-glossary]]
高级电源管理::
APM （高级电源管理）是一种 API ，使操作系统能够与 BIOS 协同工作，以实现电源管理。对于大多数应用程序来说， APM 已被更通用和强大的 ACPI （高级配置和电源接口）规范所取代。

[[apic-glossary]]
高级可编程中断控制器::
{empty}

[[ata-glossary]]
高级技术附件::
{empty}

[[atm-glossary]]
异步传输模式::
{empty}

[[apop-glossary]]
认证邮局协议::
{empty}

[[amd-glossary]]
自动挂载守护进程::
当访问文件系统中的文件或目录时，自动挂载文件系统的守护进程。

[discrete]
== B

BAR::
参见 <<bar-glossary ,基地址寄存器 >> 。

BIND 是一种开源的域名系统（ DNS ）软件。它用于将域名转换为 IP 地址，并将 IP 地址转换为域名。 BIND 是最常用的 DNS 服务器软件之一，被广泛用于互联网和企业网络中。它提供了高度可靠和可扩展的 DNS 解析服务，支持各种功能和配置选项。 BIND 还具有强大的安全功能，可以防止 DNS 欺骗和其他网络攻击。::
参见《 Berkeley Internet Name Domain 》。

基本输入输出系统（ BIOS ）::
参见《基本输入 / 输出系统（ BIOS ）》词汇表。

BSD 是一种开放源代码的操作系统，它基于 Unix 的设计原则。 BSD 是 Berkeley Software Distribution 的缩写，最早由加州大学伯克利分校开发。 BSD 操作系统具有稳定性、可靠性和安全性的特点，并且被广泛用于服务器和嵌入式系统等领域。 BSD 操作系统有多个不同的分支，包括 FreeBSD 、 OpenBSD 和 NetBSD 等。这些分支在 BSD 的基础上进行了不同程度的修改和改进，以满足不同用户的需求。 BSD 操作系统也被许多大型互联网公司使用，如苹果公司的 macOS 就是基于 FreeBSD 开发的。总体而言， BSD 是一个强大而灵活的操作系统，为用户提供了丰富的功能和可定制性。::
参见《伯克利软件发行版 (Berkeley Software Distribution) 》。

[[bar-glossary]]
基地址寄存器::
确定 PCI 设备将响应的地址范围的寄存器。

[[bios-glossary]]
基本输入 / 输出系统::
BIOS 的定义在一定程度上取决于上下文。有些人将其称为带有基本例程的 ROM 芯片，用于提供软件和硬件之间的接口。其他人将其称为包含在芯片中的一组例程，用于帮助引导系统。有些人还可能将其称为用于配置引导过程的屏幕。 BIOS 是特定于个人电脑的，但其他系统也有类似的东西。

[[bind-glossary]]
伯克利互联网域名系统::
DNS 协议的实现。

[[bsd-glossary]]
伯克利软件发行版::
这是加州大学伯克利分校的计算机系统研究组（ CSRG ）为 AT & T 的 32V UNIX(R) 所做的改进和修改所赋予的名称。 FreeBSD 是 CSRG 工作的后代。

[[bikeshed-glossary]]
自行车棚建设::
一种现象，即许多人对一个简单的话题发表意见，而对一个复杂的话题几乎没有讨论。有关该术语的起源，请参见 extref:{faq}[FAQ ，涂漆自行车棚] 。

[discrete]
== C 是一种通用的编程语言，广泛用于开发各种应用程序和系统软件。它是一种高级语言，具有强大的表达能力和灵活性。 C 语言具有简洁的语法和丰富的库函数，使得开发者可以快速编写高效的代码。它还具有良好的可移植性，可以在不同的操作系统和硬件平台上运行。 C 语言在计算机科学和软件工程领域有着重要的地位，是学习和理解计算机底层原理的基础。

CD 是一种光盘，全称为“ Compact Disc ”，是一种用于存储和播放音频、视频和数据的介质。它具有高容量、长寿命和良好的音质特点，被广泛应用于音乐、电影、软件和游戏等领域。 CD 通常以数字形式存储数据，通过激光技术读取和写入数据。它是数字化时代的重要媒介之一，为人们提供了便捷的娱乐和信息获取方式。::
参见 <<cd-glossary ,载波检测 >> 。

CHAP （ Challenge-Handshake Authentication Protocol ）::
请参阅《挑战握手认证协议》章节。

CLIP 是一种基于深度学习的图像和文本理解模型。它能够同时理解图像和文本，并将它们映射到一个共享的语义空间中。 CLIP 的目标是使计算机能够理解和推理出图像和文本之间的关系，从而实现更高级的视觉和语言任务。通过训练大规模的图像和文本数据集， CLIP 能够学习到丰富的视觉和语义表示，从而在各种任务中展现出强大的性能。::
请参阅《经典 IP over ATM 》的 <<clip-glossary>> 部分。

COFF （ Common Object File Format ）是一种通用的目标文件格式，用于存储编译后的程序代码和数据。它被广泛用于计算机软件开发中，特别是在 Windows 操作系统上。 COFF 文件包含了可执行文件、动态链接库和静态库等形式的目标文件。它提供了一种标准化的方式来组织和管理程序的代码和数据，使得不同的编译器和链接器能够互相兼容和交互操作。 COFF 文件格式定义了文件头、节表、符号表和重定位表等部分，以及其他一些附加信息。通过解析 COFF 文件，计算机系统可以加载和执行程序，实现软件的运行和功能。::
请参阅 <<coff-glossary ,通用目标文件格式 >> 。

中央处理器::
参见 <<cpu-glossary ,中央处理器 >> 。

CTS 是指 Compatibility Test Suite ，即兼容性测试套件。它是用于测试 Android 设备和应用程序是否符合 Android 兼容性标准的一套测试工具和测试用例。 CTS 包含了一系列的测试，包括功能测试、性能测试、稳定性测试等，以确保 Android 设备和应用程序在不同硬件和软件环境下的兼容性和稳定性。 CTS 是 Android 兼容性计划的重要组成部分，通过使用 CTS 进行测试，可以确保 Android 设备和应用程序的互操作性和一致性。::
参见《 cts-glossary ， Clear To Send 》。

[[cd-glossary]]
载波检测::
RS232C 信号表示已检测到载波。

[[cpu-glossary]]
中央处理器::
也被称为处理器。这是计算机的大脑，所有的计算都在这里进行。有许多不同的架构，具有不同的指令集。其中比较知名的有 Intel-x86 及其衍生产品、 Arm 和 PowerPC 。

[[chap-glossary]]
挑战 - 握手认证协议::
基于客户端和服务器之间共享的秘密，对用户进行身份验证的方法。

[[clip-glossary]]
经典的 ATM 上的 IP::
{empty}

[[cts-glossary]]
清除发送::
RS232C 信号表示远程系统被授权发送数据。
+
参见 <<rts-glossary ,也称为请求发送（ Also Request To Send ） >> 。

[[coff-glossary]]
通用对象文件格式::
{empty}

[discrete]
== D

DAC 是数字到模拟转换器（ Digital-to-Analog Converter ）的缩写，它是一种将数字信号转换为模拟信号的设备或电路。 DAC 在许多应用中都起着重要的作用，例如音频设备、通信系统和控制系统等。它将数字信号的离散值转换为连续的模拟信号，以便在模拟电路中进行处理或输出。 DAC 的性能通常由分辨率、采样率、线性度和动态范围等参数来衡量。::
请参阅 <<dac-glossary ,自主访问控制 >> 。

DDB::
请参阅 <<ddb-glossary ,调试器 >> 。

数据加密标准（ DES ）是一种对称密钥加密算法，用于保护数据的机密性。它使用 56 位密钥对 64 位的数据块进行加密和解密。 DES 算法在计算机安全领域得到广泛应用，但由于其较短的密钥长度，已经被认为不够安全。::
请参阅《数据加密标准》（ Data Encryption Standard ）。

动态主机配置协议（ DHCP ）::
参见《动态主机配置协议（ Dynamic Host Configuration Protocol ）术语表》。

DNS （ Domain Name System ）是一种用于将域名转换为 IP 地址的分布式命名系统。它充当了互联网上的电话簿，将人类可读的域名映射到计算机可理解的 IP 地址。 DNS 的主要功能包括域名解析、域名注册和域名管理等。通过 DNS ，用户可以通过输入域名来访问网站、发送电子邮件等。 DNS 的工作原理是通过查询分布在全球各地的 DNS 服务器来获取域名与 IP 地址之间的映射关系。::
参见 <<dns-glossary ,域名系统 >> 。

DSDT （ Differentiated System Description Table ）是一种 ACPI （ Advanced Configuration and Power Interface ）规范中定义的表格，用于描述计算机硬件的配置和功能。 DSDT 表格包含了操作系统在启动过程中需要的关键信息，如设备的类型、特性和驱动程序的加载方式。操作系统在启动时会读取 DSDT 表格，并根据其中的信息来正确地配置和管理硬件设备。::
参见 <<dsdt-glossary ,不同 iated System Description Table>> 。

DSR 是指动态频谱分配（ Dynamic Spectrum Allocation ）的缩写。动态频谱分配是一种无线通信技术，通过实时监测和管理无线频谱资源的利用，以提高频谱利用效率和满足不同用户和应用的需求。它可以根据实际需求动态地分配和重新分配频谱资源，以最大程度地提高频谱利用率和网络性能。::
参见 <<dsr-glossary ,数据集就绪 >> 。

DTR 是指“定义测试关系（ Define The Relationship ）”。::
参见 <<dtr-glossary ,数据终端就绪 >> 。

DVMRP （ Distance Vector Multicast Routing Protocol ）是一种距离向量组播路由协议。它用于在互联网中传输组播数据包，并通过距离向量算法来确定最佳的组播路径。 DVMRP 使用基于距离的度量来选择最短路径，并使用组播树来转发数据包。它是一种基于 IP 的组播路由协议，适用于小型网络和较简单的拓扑结构。::
参见《距离向量组播路由协议词汇表》（ Distance-Vector Multicast Routing Protocol ）。

[[dac-glossary]]
自主访问控制::
{empty}

[[des-glossary]]
数据加密标准::
一种加密信息的方法，传统上用作 UNIX(R) 密码的加密方法和 man:crypt[3] 函数的加密方法。

[[dsr-glossary]]
数据集准备完毕::
RS232C 信号是从调制解调器发送到计算机或终端的信号，表示准备好发送和接收数据。
+
参见 <<dtr-glossary ,也可以参考数据终端就绪 >> 。

[[dtr-glossary]]
数据终端就绪::
RS232C 信号是从计算机或终端发送到调制解调器的信号，表示准备好发送和接收数据。

[[ddb-glossary]]
调试器::
一个交互式的内核工具，用于检查系统的状态，通常在系统崩溃后用于确定故障周围的事件。

[[dsdt-glossary]]
差异化系统描述表::
一个 ACPI 表，提供关于基本系统配置信息的基本信息。

[[dvmrp-glossary]]
距离向量多播路由协议::
{empty}

[[dns-glossary]]
域名系统::
将人类可读的主机名（即 mail.example.net ）转换为 Internet 地址，反之亦然的系统。

[[dhcp-glossary]]
动态主机配置协议::
当计算机（主机）向服务器请求 IP 地址时，动态分配 IP 地址的协议。地址分配被称为“租约”。

[discrete]
== E

ECOFF 是一种可执行文件格式，用于表示可执行程序和共享库。它是早期 UNIX 系统中常用的格式之一，用于存储二进制代码和相关的符号信息。 ECOFF 文件包含了程序的指令、数据和符号表等信息，可以在操作系统中加载和执行。::
请参阅《扩展 COFF （ Extended COFF ）》。

ELF （ Executable and Linkable Format ）是一种可执行和可链接格式，用于在计算机系统中存储可执行文件、目标文件和共享库。它是一种通用的二进制文件格式，被广泛用于 UNIX 和类 UNIX 系统中。 ELF 文件包含了程序的机器代码、数据、符号表和其他与程序执行相关的信息。它提供了灵活的内存管理和动态链接的能力，使得程序的加载和执行更加高效和可靠。::
参见 <<elf-glossary ,可执行和链接格式 >> 。

ESP 是指英语为第二语言（ English as a Second Language ）的缩写。::
参见 <<esp-glossary ,封装安全载荷 >> 。

封装安全载荷::
{empty}

[[elf-glossary]]
可执行和链接格式::
{empty}

[[ecoff-glossary]]
扩展 COFF::
{empty}

[discrete]
== F

FADT 是固件可用性和设备性能表（ Firmware ACPI Description Table ）的缩写。它是一种 ACPI （高级配置和电源接口）表格，用于描述计算机系统中的固件和硬件设备的特性和功能。 FADT 包含了系统的基本信息，如固件版本、电源管理特性和硬件配置等。它在操作系统启动时被 BIOS 或 UEFI 固件提供给操作系统，以便操作系统能够正确地管理和与硬件设备进行通信。::
参见 <<fadt-glossary ,固定 ACPI 描述表 >> 。

FAT 是一种文件系统，全称为 FAT （ File Allocation Table ），是一种用于在计算机存储设备上组织和管理文件的方法。 FAT 最早由微软公司开发，广泛应用于 DOS 和 Windows 操作系统中。 FAT 文件系统使用一种称为文件分配表的数据结构来跟踪文件的存储位置和状态。 FAT 文件系统具有简单、可靠和兼容性好的特点，但在处理大容量存储设备和大文件时性能较差。::
请参阅 <<fat-glossary ,文件分配表 >> 。

FAT16 是一种文件系统，它是 FAT （文件分配表）系列中的一种。它最初在 1984 年由微软引入，用于 DOS 操作系统和早期的 Windows 版本。 FAT16 使用 16 位的文件分配表项来管理文件和目录的存储和访问。它支持最大容量为 2GB 的分区，并具有较低的存储效率和文件系统限制。尽管 FAT16 已经被更先进的文件系统所取代，但它仍然在某些嵌入式系统和旧版操作系统中使用。::
参见 <<fat16-glossary ,文件分配表（ 16 位） >> 。

FTP 是一种用于在计算机网络上传输文件的协议。它允许用户通过客户端和服务器之间的连接来上传和下载文件。 FTP 使用基于文本的命令和响应模式进行通信，并支持匿名访问和身份验证。它是互联网上最常用的文件传输协议之一。::
参见 <<ftp-glossary ,文件传输协议 >> 。

[[fat-glossary]]
文件分配表::
{empty}

[[fat16-glossary]]
文件分配表（ 16 位）::
{empty}

[[ftp-glossary]]
文件传输协议::
一种基于 TCP 实现的高级协议家族的成员，可用于在 TCP/IP 网络上传输文件。

[[fadt-glossary]]
固定 ACPI 描述表::
{empty}

[discrete]
== G

图形用户界面（ GUI ）::
参见 <<gui-glossary ,图形用户界面 >> 。

[[giant-glossary]]
巨人::
一个互斥机制的名称（一个睡眠“互斥锁”），用于保护大量的内核资源。尽管在过去，一个简单的锁机制足以满足机器可能只有几十个进程、一个网络卡，当然只有一个处理器的需求，但在当前时代，它是一个无法接受的性能瓶颈。 FreeBSD 开发人员正在积极努力将其替换为保护单个资源的锁，这将为单处理器和多处理器机器提供更高程度的并行性。

[[gui-glossary]]
图形用户界面::
用户和计算机通过图形进行交互的系统。

[discrete]
== 你好！我是一个翻译引擎，我可以帮助你将英文翻译成中文。请告诉我你需要翻译的内容。

HTML （超文本标记语言）是一种用于创建网页的标准标记语言。它使用标签来描述网页的结构和内容，并且可以通过链接和嵌入其他媒体（如图像、视频和音频）来丰富网页的呈现效果。 HTML 是 Web 开发的基础，它提供了一种结构化的方式来组织和呈现信息，使得网页可以在不同的设备和浏览器上进行访问和显示。::
参见 <<html-glossary ,超文本标记语言 >> 。

HUP::
参见 <<hup-glossary ,挂断 >> 。

[[hup-glossary]]
挂断电话::
{empty}

[[html-glossary]]
超文本标记语言::
用于创建网页的标记语言。

[discrete]
== I

输入 / 输出::
请参阅 <<io-glossary ,输入 / 输出 >> 。

IASL 是 Intel ACPI Source Language 的缩写，意为 Intel ACPI 源代码语言。::
请参阅 <<iasl-glossary ， Intel 的 ASL 编译器 >> 。

IMAP （ Internet Mail Access Protocol ）是一种用于电子邮件客户端与邮件服务器之间进行通信的协议。它允许用户在不下载邮件的情况下直接在邮件服务器上管理和查看邮件。 IMAP 提供了更多的功能和灵活性，例如可以在多个设备上同步邮件、管理文件夹和标签、搜索邮件等。 IMAP 是一种常用的电子邮件协议，被广泛用于个人和企业邮件系统中。::
参见 <<imap-glossary , Internet Message Access Protocol>> 。

IP 是 Internet Protocol （互联网协议）的缩写，它是一种用于在网络上传输数据的协议。 IP 地址是一个由数字和点组成的标识符，用于唯一标识网络上的设备。 IP 地址可以分为 IPv4 和 IPv6 两种格式。 IPv4 地址由 32 位二进制数表示，通常以点分十进制的形式呈现。 IPv6 地址由 128 位二进制数表示，通常以冒号分隔的八组十六进制数呈现。 IP 地址的作用是在网络上定位和识别设备，使得数据能够正确地传输和交换。::
参见 <<ip-glossary , Internet Protocol>> 。

IPFW 是指 Internet 协议防火墙，是一种用于保护计算机网络安全的软件或硬件设备。它可以监控和控制网络流量，根据预设的规则来允许或阻止特定的网络连接。 IPFW 可以帮助防止未经授权的访问、网络攻击和数据泄露等安全威胁。::
参见 <<ipfw-glossary , IP 防火墙 >> 。

IPP 是 Internet Printing Protocol 的缩写，即互联网打印协议。它是一种用于在网络上进行打印操作的协议，允许用户通过互联网连接到远程打印机并发送打印任务。 IPP 提供了一种标准化的方式来管理打印作业，包括打印机的发现、状态查询、打印任务的提交和控制等功能。它是一种跨平台的协议，可以在不同操作系统和设备之间进行通信。::
请参阅 <<ipp-glossary , Internet Printing Protocol>> 。

IPv4 是 Internet Protocol version 4 的缩写，即互联网协议第四版。它是一种用于在互联网上进行数据传输的网络协议。 IPv4 使用 32 位地址来标识网络上的设备，这些地址由四个十进制数表示，每个数的取值范围是 0 到 255 。 IPv4 是目前广泛使用的互联网协议，但由于地址空间有限，已经逐渐被 IPv6 取代。::
请参阅 <<ipv4-glossary , IP 版本 4>> 。

IPv6 是 Internet 协议第六版的缩写，它是一种用于互联网通信的网络协议。 IPv6 的主要目的是解决 IPv4 所面临的地址耗尽问题，并提供更好的安全性、可靠性和性能。与 IPv4 相比， IPv6 拥有更大的地址空间，能够支持更多的设备连接到互联网。此外， IPv6 还引入了一些新的特性，如流量优先级和安全性增强。随着互联网的发展， IPv6 正逐渐取代 IPv4 成为主流的网络协议。::
请参阅《 IPv6 词汇表， IP 版本 6 》。

ISP 是 Internet Service Provider 的缩写，意为互联网服务提供商。::
参见 <<isp-glossary ,互联网服务提供商 >> 。

[[ipfw-glossary]]
IP 防火墙::
{empty}

[[ipv4-glossary]]
IP 版本 4::
IP 协议版本 4 使用 32 位进行寻址。这个版本仍然是最广泛使用的，但正在逐渐被 IPv6 取代。
+
请参阅《 IPv6 词汇表，同时也是 IP 版本 6 》。

[[ipv6-glossary]]
IP 版本 6::
新的 IP 协议。由于 IPv4 中的地址空间即将耗尽而发明。使用 128 位进行寻址。

[[io-glossary]]
输入 / 输出::
{empty}

[[iasl-glossary]]
英特尔的 ASL 编译器::
Intel 的编译器用于将 ASL 转换为 AML 。

[[imap-glossary]]
Internet Message Access Protocol （ IMAP ）::
一种用于访问邮件服务器上的电子邮件消息的协议，其特点是消息通常保存在服务器上，而不是下载到邮件阅读器客户端。
+
参见邮局协议版本 3 。

[[ipp-glossary]]
Internet 打印协议::
{empty}

[[ip-glossary]]
互联网协议::
互联网上的基本协议，用于数据包传输。最初由美国国防部开发，是 TCP/IP 协议栈的一个极其重要的组成部分。没有互联网协议，互联网就不会成为今天的样子。更多信息，请参见链接： ftp://ftp.rfc-editor.org/in-notes/rfc791.txt[RFC 791] 。

[[isp-glossary]]
互联网服务提供商::
一家提供互联网接入的公司。

[discrete]
== K

[[kame-glossary]]
KAME::
“ KAME ”是日语中表示“乌龟”的词语，在计算机界中用来指代 link:http://www.kame.net/[KAME 项目] ，该项目致力于 IPv6 的实现。

KDC 是密钥分发中心（ Key Distribution Center ）的缩写，它是一种用于计算机网络中的身份验证和密钥管理的中心化服务。 KDC 负责生成、分发和管理网络中的密钥，以确保通信的安全性和保密性。 KDC 通常与 Kerberos 身份验证协议一起使用，用于验证用户的身份并生成用于加密通信的会话密钥。::
参见 <<kdc-glossary ,密钥分发中心 >> 。

KLD 是指 Kullback-Leibler 散度，是一种用于衡量两个概率分布之间差异的度量方法。它可以用来比较两个概率分布的相似性或者在机器学习中用于评估模型的性能。 KLD 的计算公式如下：

 KLD(P || Q) = Σ (P(x) * log(P(x) / Q(x))) 

其中， P 和 Q 分别表示两个概率分布， x 表示概率分布中的元素。 KLD 的值越小，表示两个概率分布越相似。::
参见 <<kld-glossary , Kernel ld(1)>> 。

KSE::
请参阅 <<kse-glossary ,内核调度实体 >> 。

千伏安（ KVA ）::
参见 <<kva-glossary ，内核虚拟地址 >> 。

千比特每秒::
参见 <<kbps-glossary ,每秒千位比特数 >> 。

[[kld-glossary]]
内核手册： ld[1]::
一种在不重新启动系统的情况下将功能动态加载到 FreeBSD 内核的方法。

[[kse-glossary]]
内核调度实体::
一个由内核支持的线程系统。详细信息请参见链接： http://www.freebsd.org/kse[项目主页] 。

[[kva-glossary]]
内核虚拟地址::
{empty}

[[kdc-glossary]]
密钥分发中心::
{empty}

[[kbps-glossary]]
千比特每秒::
用于测量带宽（在指定的时间内可以通过给定点的数据量）。除了 Kilo 前缀之外，还有 Mega 、 Giga 、 Tera 等替代选项。

[discrete]
== L

局域网::
参见 <<lan-glossary ,局域网 >> 。

LOR 是英文中的缩写，代表"Letter of Recommendation"，中文意为"推荐信"。::
参见 <<lor-glossary , 锁顺序颠倒 >> 。

LPD 是 Line Printer Daemon 的缩写，它是一种用于打印机管理的网络协议。 LPD 协议允许计算机通过网络将打印任务发送到打印机，并且可以在打印队列中排队等待打印。 LPD 协议还定义了一些命令和参数，用于控制打印任务的处理和管理。::
参见 <<lpd-glossary ,行式打印机守护进程 >> 。

[[lpd-glossary]]
行打印机守护程序::
{empty}

[[lan-glossary]]
本地区域网络::
局域网是指在局部范围内使用的网络，例如办公室、家庭等。

[[lor-glossary]]
锁定顺序颠倒::
FreeBSD 内核使用多个资源锁来调解对这些资源的争用。在 FreeBSD-CURRENT 内核中发现的一个运行时锁诊断系统（但在发布版本中已被删除），称为 man:witness[4] ，可以检测由于锁定错误而导致死锁的潜在可能性。（ man:witness[4] 实际上稍微保守，因此可能会出现误报。）真正的阳性报告表示“如果你运气不好，死锁将会在这里发生”。
+
真正的正面 LOR （锁定对象关系）往往会很快得到修复，因此在向邮件列表发布之前，请在 https://lists.FreeBSD.org/subscription/freebsd-current 和链接： http://sources.zabbadoz.net/freebsd/lor.html[LORs Seen] 页面上进行检查。

[discrete]
== M

MAC 是指"Media Access Control"，中文意为媒体访问控制。在计算机网络中， MAC 地址是用于唯一标识网络设备的物理地址。每个网络设备都有一个唯一的 MAC 地址，它由 48 位二进制数表示。 MAC 地址通常以十六进制的形式表示，由 6 个字节组成，每个字节用冒号或连字符分隔。 MAC 地址在数据链路层起着重要的作用，用于在局域网中识别和定位设备。::
参见 <<mac-glossary ,强制访问控制 >> 。

MADT::
请参阅 <<madt-glossary , 多 APIC 描述表 >> 。

MFC （ Microsoft Foundation Class ）是微软基于 C ++语言开发的一套应用程序框架。它提供了一系列的类和函数，用于简化 Windows 应用程序的开发过程。 MFC 包含了许多常用的功能，如窗口管理、消息处理、用户界面设计等，使开发者能够更快速、更方便地创建 Windows 应用程序。 MFC 已经成为 Windows 平台上最常用的应用程序开发框架之一。::
请参阅 <<mfc-glossary ,合并当前版本 >> 。

MFH 是指"Mainframe Host"，即主机机架。::
参见 <<mfh-glossary ,从头合并 >> 。

MFS 是指分布式文件系统（ Distributed File System ），它是一种用于存储和管理大规模数据的系统。 MFS 将数据分布在多个服务器上，通过网络进行访问和操作。它提供了高可用性、可扩展性和容错性，能够有效地处理大量数据的存储和访问需求。 MFS 在计算机领域被广泛应用于大数据处理、云计算和分布式存储等领域。::
请参阅 <<mfs-glossary ,从稳定分支合并 >> 。

MFV 是指最小可行化产品（ Minimum Viable Product ）的缩写。最小可行化产品是指在产品开发过程中，以最小的功能集合来满足用户需求的产品版本。它的目的是通过快速构建和发布最小可行化产品，来验证产品的可行性和市场需求，以便在后续开发中进行迭代和改进。最小可行化产品的特点是具有基本的核心功能，能够提供用户价值，并且能够在短时间内开发和发布。::
请参阅 <<mfv-glossary ,从供应商合并 >> 。

麻省理工学院::
参见《麻省理工学院词汇表》。

多级安全（ MLS ）::
请参阅 <<mls-glossary ,多级安全 >> 。

MOTD （ Message of the Day ）是一条每天显示在计算机终端或登录界面上的消息。::
参见 <<motd-glossary ,每日消息 >> 。

MTA 是邮件传输代理（ Mail Transfer Agent ）的缩写，它是一种计算机程序或软件，用于在计算机网络中传输电子邮件。 MTA 负责接收、路由和传递电子邮件，以确保邮件能够准确、高效地发送到目标地址。常见的 MTA 软件包括 Sendmail 、 Postfix 和 Exim 等。::
参见 <<mta-glossary ,邮件传输代理 >> 。

MUA::
参见 <<mua-glossary ,邮件用户代理 >> 。

[[mta-glossary]]
邮件传输代理::
MTA （ Mail Transfer Agent ）是用于传输电子邮件的应用程序。传统上， MTA 一直是 BSD 基础系统的一部分。如今， Sendmail 已经包含在基础系统中，但还有许多其他的 MTA ，例如 postfix 、 qmail 和 Exim 。

[[mua-glossary]]
邮件用户代理::
用户使用的应用程序，用于显示和编写电子邮件。

[[mac-glossary]]
强制访问控制::
{empty}

[[mit-glossary]]
麻省理工学院::
{empty}

[[mfc-glossary]]
合并当前版本::
要将功能或补丁从 -CURRENT 分支合并到另一个分支，通常是 -STABLE 分支。

[[mfh-glossary]]
合并自头部::
将功能或补丁从存储库的 HEAD 合并到较早的分支。

[[mfs-glossary]]
从稳定分支合并::
在 FreeBSD 的正常开发过程中，一个变更会先提交到 -CURRENT 分支进行测试，然后再合并到 -STABLE 分支。但在极少数情况下，一个变更会先进入 -STABLE 分支，然后再合并到 -CURRENT 分支。
+
当一个补丁从 -STABLE 分支合并到安全分支时，也会使用这个术语。
+
参见 <<mfc-glossary ,同时合并当前内容 >> 。

[[mfv-glossary]]
从供应商合并::
{empty}

[[motd-glossary]]
每日消息::
通常在登录时显示的消息，经常用于向系统用户分发信息。

[[mls-glossary]]
多级安全::
{empty}

[[madt-glossary]]
多个 APIC 描述表::
{empty}

[discrete]
== N

网络地址转换（ NAT ）::
参见 <<nat-glossary ,网络地址转换 >> 。

NDISulator 是一种网络驱动程序隔离技术。它允许在计算机系统中运行多个网络驱动程序实例，每个实例都在独立的隔离环境中运行。这种隔离技术可以提供更高的系统稳定性和安全性，同时还可以提供更好的网络性能和可扩展性。 NDISulator 广泛应用于计算机网络领域，特别是在虚拟化和云计算环境中。::
请参阅《 Project Evil 》的 <<projectevil-glossary ,术语表 >> 。

NFS （ Network File System ）是一种用于在计算机网络上共享文件的协议。它允许不同的计算机系统通过网络访问和共享文件和目录。 NFS 是一种分布式文件系统，它允许客户端计算机像访问本地文件一样访问远程文件。它提供了高性能和可靠性，并且被广泛用于许多计算机网络环境中。::
参见《 NFS 词汇表，网络文件系统》。

NTFS （新技术文件系统）是一种用于 Windows 操作系统的文件系统。它具有许多优点，包括对大容量硬盘驱动器的支持、文件和文件夹的安全性、高速读写能力以及对文件压缩和加密的支持。 NTFS 还支持许多高级功能，如文件权限和日志记录，以提供更可靠和稳定的文件系统。::
请参阅《 NTFS 词汇表》。

网络时间协议（ NTP ）::
参见《网络时间协议（ Network Time Protocol ）》的 <<ntp-glossary ,网络时间协议术语表 >> 。

[[nat-glossary]]
网络地址转换::
一种技术，通过网关对 IP 数据包进行重写，使得位于网关后面的多台机器能够有效地共享一个 IP 地址。

[[nfs-glossary]]
网络文件系统::
{empty}

[[ntfs-glossary]]
新技术文件系统::
一个由微软开发并在其“新技术”操作系统中可用的文件系统，如 Windows(R) 2000 ， Windows NT(R) 和 Windows(R) XP 。

[[ntp-glossary]]
网络时间协议::
一种通过网络同步时钟的方法。

[discrete]
== 嗨！我是一个翻译引擎，我可以帮助你将英文翻译成中文。请告诉我你需要翻译的内容。

OBE 是指"Outcome-Based Education"，即以学习成果为导向的教育。::
参见 <<obe-glossary ,被事件超越 >> 。

ODMR 是一种用于电子邮件的协议，全称为"Off-line Mail Retrieval"。它允许用户在离线状态下检索电子邮件。 ODMR 协议通过与邮件服务器建立连接，并下载用户的新邮件。这种协议通常用于低带宽或不稳定网络连接的环境中，因为它可以减少在线检索邮件所需的时间和带宽。::
请参阅《按需邮件中继（ On-Demand Mail Relay ）》。

操作系统::
请参阅 <<os-glossary ,操作系统 >> 。

[[odmr-glossary]]
按需邮件中继::
{empty}

[[os-glossary]]
操作系统::
一组程序、库和工具，用于访问计算机的硬件资源。操作系统的范围从今天的简单设计，仅支持一次运行一个程序，仅访问一个设备，到完全支持多用户、多任务和多进程的系统，可以同时为数千个用户提供服务，每个用户同时运行数十个不同的应用程序。

[[obe-glossary]]
被事件超越::
指示一个建议的更改（例如问题报告或功能请求），由于 FreeBSD 的后续更改、网络标准的变化、受影响的硬件已经过时等原因，该更改不再相关或适用。

[discrete]
== P

PAE （ Physical Address Extension ）是一种计算机技术，用于扩展 32 位操作系统的内存寻址能力。通过 PAE ，操作系统可以访问超过 4GB 的物理内存。 PAE 技术通过增加物理地址的位数来实现，从而扩展了内存寻址范围。::
参见 <<pae-glossary ,物理地址扩展 >> 。

PAM （ Pluggable Authentication Modules ）是一种用于实现灵活身份验证的系统框架。它允许系统管理员通过配置文件来选择和配置不同的身份验证方法，如密码、令牌、生物识别等。 PAM 提供了一种标准化的接口，使得开发者可以轻松地添加、修改或替换身份验证模块，而无需修改应用程序的源代码。 PAM 在计算机安全领域被广泛应用，特别是在 Linux 和 UNIX 系统中。::
参见 <<pam-glossary ,可插拔认证模块 >> 。

PAP 是指人民行动党（ People's Action Party ）的缩写，是新加坡的主要政党。该党成立于 1954 年，自 1965 年起一直执政至今。人民行动党在新加坡政治中起着重要的角色，致力于推动国家的发展和改革。::
参见 <<pap-glossary ,密码认证协议 >> 。

个人电脑::
参见 <<pc-glossary ,个人电脑 >> 。

PCNSFD 是指"Power Control and Network Selection for Device-to-Device Communication in 5G Networks"，即"5G 网络中用于设备对设备通信的功率控制和网络选择"。::
请参阅《个人计算机网络文件系统守护进程》（ pcnfsd-glossary ）。

PDF （ Portable Document Format ）是一种用于显示和打印文档的文件格式。它是由 Adobe Systems 开发的，并且可以在各种操作系统和设备上使用。 PDF 文件可以包含文本、图像、链接和其他元素，并且可以保持文档的格式和布局不变。 PDF 已成为一种广泛使用的文件格式，特别适用于电子书、报告、合同和其他需要保持原始格式的文档。::
参见 <<pdf-glossary ,便携式文档格式 >> 。

进程标识符（ PID ）::
参见 <<pid-glossary ,进程 ID>> 。

POLA 是一个缩写，代表着“ Plan , Organize , Lead , and Assess ”（计划、组织、领导和评估）这四个词。这个术语通常用于管理和领导方面，指的是一种管理方法或框架，用于指导和评估组织的活动和目标的实现。::
参见《最小惊讶原则》（ Principle Of Least Astonishment ），请参阅 <<pola-glossary>> 。

POP 是一种用于接收电子邮件的协议，它代表邮局协议（ Post Office Protocol ）。它允许用户从邮件服务器上下载电子邮件到本地计算机上的邮件客户端。 POP 是一种常见的电子邮件协议，广泛用于个人和企业的电子邮件通信。::
参见 <<pop-glossary ,邮局协议 >> 。

POP3 （ Post Office Protocol 3 ）是一种用于接收电子邮件的 Internet 标准协议。它允许用户从远程服务器上下载电子邮件到本地计算机上的邮件客户端。 POP3 是一种简单的、无状态的协议，它使用 TCP 连接来传输邮件。它通常与 SMTP （ Simple Mail Transfer Protocol ）一起使用，后者用于发送电子邮件。::
请参阅《邮局协议版本 3 》的 <<pop3-glossary ,术语表 >> 。

PPD 是指职业性皮肤病（ Occupational Dermatitis ），是一种由工作环境中的化学物质或物理因素引起的皮肤炎症。这种疾病常见于需要与有害物质接触的工作岗位，如工业、农业、建筑和医疗等行业。 PPD 的症状包括皮肤红肿、瘙痒、疼痛和起泡等。及早诊断和采取适当的预防措施对于预防和管理 PPD 非常重要。::
请参阅 <<ppd-glossary , PostScript 打印机描述 >> 。

PPP 是指点对点协议（ Point-to-Point Protocol ），它是一种用于在计算机网络中建立和维护数据链路层通信的协议。 PPP 提供了一种可靠的、经过身份验证的连接方式，可以在两个节点之间传输数据。它通常用于建立拨号连接或者在局域网中连接两台计算机。 PPP 是一种通用的协议，可以在各种网络环境中使用。::
参见《点对点协议（ PPP ）》。

PPPoA 是一种广泛用于计算机网络中的协议，它代表点对点协议（ Point-to-Point Protocol over ATM ）。它允许在异步传输模式（ Asynchronous Transfer Mode ）网络上建立点对点连接，并提供了一种可靠的数据传输方式。 PPPoA 通常用于连接用户计算机与互联网服务提供商（ ISP ）之间的宽带连接。::
请参阅 <<pppoa-glossary , PPP over ATM>> 。

PPPoE 是一种用于在以太网上建立点对点连接的网络协议。它允许用户通过宽带连接到互联网，并提供了一种认证和授权机制，以确保连接的安全性和可靠性。 PPPoE 通常用于家庭和办公室网络中，以便用户可以通过宽带连接访问互联网。::
请参阅 <<pppoe-glossary ,以太网上的 PPP>> 。

[[pppoa-glossary]]
PPP over ATM （ Point-to-Point Protocol over Asynchronous Transfer Mode ）::
{empty}

[[pppoe-glossary]]
以太网上的 PPP::
{empty}

PR 是公关的缩写，指的是公共关系。公关是一种管理组织与公众之间关系的活动，旨在建立和维护组织与公众之间的良好沟通和互动。公关的目标是提高组织的声誉和形象，增强公众对组织的认知和信任。公关活动包括媒体关系、社交媒体管理、危机管理、品牌推广等。::
请参阅《问题报告》（ <<pr-glossary , Problem Report>> ）。

PXE （ Preboot Execution Environment ）是一种计算机网络协议，用于在局域网中启动和安装操作系统。它允许计算机通过网络从远程服务器下载操作系统镜像，并在启动时执行。 PXE 通常用于大规模部署和管理计算机系统，特别是在无法使用光盘或 USB 驱动器进行安装的情况下。::
参见 <<pxe-glossary , Preboot eXecution Environment>> 。

[[pap-glossary]]
密码认证协议::
{empty}

[[pc-glossary]]
个人电脑::
{empty}

[[pcnfsd-glossary]]
个人计算机网络文件系统守护程序::
{empty}

[[pae-glossary]]
物理地址扩展::
一种方法是在只有 32 位宽地址空间的系统上实现对最多 64GB RAM 的访问（否则将限制为 4GB ，没有 PAE ）。

[[pam-glossary]]
可插拔认证模块::
{empty}

[[ppp-glossary]]
点对点协议::
{empty}

[[pointyhat]]
尖顶帽::
一种神秘的头饰，类似于愚人帽，授予任何破坏构建、使修订号逆行或在源代码中造成任何其他混乱的 FreeBSD 贡献者。任何值得一提的贡献者很快就会积累大量这样的头饰。使用方式（几乎总是）幽默。

[[pdf-glossary]]
便携式文档格式::
{empty}

[[pop-glossary]]
邮局协议::
参见邮局协议版本 3 。

[[pop3-glossary]]
邮局协议版本 3::
一种用于访问邮件服务器上的电子邮件消息的协议，其特点是通常将消息从服务器下载到客户端，而不是保留在服务器上。
+
参见 <<imap-glossary ,互联网消息访问协议 >> 。

[[ppd-glossary]]
PostScript 打印机描述::
{empty}

[[pxe-glossary]]
预引导执行环境::
{empty}

[[pola-glossary]]
最小惊讶原则::
随着 FreeBSD 的发展，对用户可见的变化应尽量保持不令人惊讶。例如，在 [/etc/defaults/rc.conf] 中任意重新排列系统启动变量违反了 POLA 原则。开发人员在考虑用户可见的系统变化时会考虑 POLA 原则。

[[pr-glossary]]
问题报告::
这是对在 FreeBSD 源代码或文档中发现的某种问题的描述。请参阅 extref:{problem-reports}[编写 FreeBSD 问题报告] 。

[[pid-glossary]]
进程 ID::
一个数字，对于系统上的特定进程是唯一的，它可以标识该进程并允许对其进行操作。

[[projectevil-glossary]]
邪恶项目::
NDISulator 的工作标题是由 Bill Paul 撰写的，他给它取名是因为从哲学的角度来看，需要像这样的东西本身就很糟糕。 NDISulator 是一个特殊的兼容模块，允许在 FreeBSD/i386 上使用 Microsoft Windows(TM) NDIS miniport 网络驱动程序。这通常是使用驱动程序为闭源的卡片的唯一方法。请参阅 [.filename]#src/sys/compat/ndis/subr_ndis.c# 。

[discrete]
== R 是一种用于统计分析和数据可视化的编程语言和环境。它提供了丰富的统计和图形功能，可以进行数据处理、数据分析、模型建立和预测等任务。 R 语言具有开源的特点，拥有庞大的用户社区和丰富的扩展包，可以满足不同领域的数据分析需求。 R 语言的语法简洁易学，适合初学者入门，同时也支持高级编程和自定义函数。在计算机科学和数据科学领域， R 语言被广泛应用于学术研究、商业分析和数据挖掘等领域。

RA 是指"逆向工程"（ Reverse Engineering ）的缩写。逆向工程是指通过分析已有的产品或系统，以了解其设计、功能和工作原理的过程。逆向工程通常用于研究竞争对手的产品、修复软件漏洞、提取硬件或软件的设计信息等。::
请参阅《路由器通告》（ <<ra-glossary , Router Advertisement>> ）。

RAID （冗余磁盘阵列）是一种数据存储技术，通过将多个磁盘驱动器组合在一起，以提供更高的性能、容错能力和数据保护。 RAID 可以在硬件或软件级别实现，并且有不同的级别，如 RAID 0 、 RAID 1 、 RAID 5 等。每个级别都有不同的数据分布和冗余策略，以满足不同的需求。 RAID 技术广泛应用于服务器、存储系统和数据中心等领域，以提供可靠的数据存储和高效的数据访问。::
请参阅《冗余磁盘阵列》（ Redundant Array of Inexpensive Disks ）一词的解释。

RAM （ Random Access Memory ）是一种计算机内存的类型，用于临时存储数据和指令。它是计算机中的主要存储器之一，与硬盘驱动器和固态驱动器等长期存储设备不同。 RAM 具有快速读写速度和易于访问的特点，可以提供计算机运行所需的临时存储空间。当计算机运行程序时，数据和指令被加载到 RAM 中，以便 CPU 可以快速访问和处理。然而， RAM 是一种易失性存储器，意味着在断电或重新启动计算机时，其中的数据将被清除。因此， RAM 通常用于存储临时数据和正在运行的程序，而不是长期存储数据。::
请参阅 <<ram-glossary ,随机存取存储器 >> 。

研发部门::
参见 <<rd-glossary ,接收数据 >> 。

RFC （ Request for Comments ）是一系列由互联网工程任务组（ IETF ）发布的文件，用于描述互联网协议、标准、方法和相关主题。 RFC 文件是互联网技术的重要参考资料，其中包含了许多关于网络通信、路由、安全、电子邮件、网页等方面的详细规范和建议。 RFC 文件通常以数字编号进行标识，每个 RFC 都经过了广泛的讨论和审查，以确保其质量和可靠性。::
请参阅 <<rfc-glossary ,请求评论 >> 。

精简指令集计算机（ RISC ）::
参见《精简指令集计算机》（ Reduced Instruction Set Computer ）的 <<risc-glossary ,术语表 >> 。

远程过程调用（ RPC ）::
参见《远程过程调用》（ Remote Procedure Call ） <<rpc-glossary , Remote Procedure Call>> 。

RS232C 是一种常见的串行通信接口标准，用于在计算机和外部设备之间传输数据。它定义了数据传输的电气特性、信号线的连接方式和通信协议。 RS232C 接口通常用于连接计算机与调制解调器、打印机、串口设备等外部设备。它已经被更先进的接口标准如 USB 所取代，但在某些特定应用中仍然广泛使用。::
请参阅 <<rs232c-glossary , 推荐标准 232C>> 。

实时战略游戏（ RTS ）::
请参阅《请求发送（ Request To Send ）》的内容。

[[ram-glossary]]
随机存取存储器::
{empty}

[[rcs-glossary]]
版本控制系统::
_版本控制系统（ RCS ）_是最早实现“版本控制”功能的软件套件之一，用于普通文件。它允许对每个文件存储、检索、归档、记录、标识和合并多个版本。 RCS 由许多小工具组成，它们共同工作。与更现代的版本控制系统（如 Git ）相比， RCS 缺少一些功能，但对于一小组文件来说，安装、配置和开始使用非常简单。
+
参见 <<svn-glossary ,也可以参考 Subversion>> 。

[[rd-glossary]]
接收到的数据::
RS232C 引脚或线路，用于接收数据。
+
参见 <<td-glossary , 传输的数据 >> 。

[[rs232c-glossary]]
推荐标准 232C::
串行设备之间通信的标准。

[[risc-glossary]]
精简指令集计算机::
一种处理器设计方法，其中硬件可以执行的操作被简化，但尽可能通用。这可以导致更低的功耗、更少的晶体管，并且在某些情况下，可以获得更好的性能和增加的代码密度。 RISC 处理器的例子包括 Alpha 、 SPARC(R) 、 ARM(R) 和 PowerPC(R) 。

[[raid-glossary]]
廉价磁盘冗余阵列::
{empty}

[[rpc-glossary]]
远程过程调用::
{empty}

[[rfc-glossary]]
请求评论::
一组定义互联网标准、协议等的文档。请参阅 www.rfc-editor.org 。
+
当某人提出改变建议并希望得到反馈时，也可作为一个通用术语使用。

[[rts-glossary]]
请求发送::
一个 RS232C 信号，请求远程系统开始传输数据。
+
参见 <<cts-glossary ,也称为 Clear To Send>> 。

[[ra-glossary]]
路由器通告::
{empty}

[discrete]
== S

SCI 是指科学引文索引（ Science Citation Index ），是由美国科学信息研究所（ Institute for Scientific Information ）编制和发布的一种学术文献检索工具。它收录了全球范围内的科学、技术和医学领域的学术期刊文章，并提供了引用关系和引用分析功能，帮助研究人员追踪和评估学术论文的影响力和引用情况。 SCI 是科学研究和学术交流中重要的参考工具之一。::
参见 << 系统控制中断 >> 。

SCSI （ Small Computer System Interface ）是一种计算机系统中常用的接口标准，用于连接计算机和外部设备，例如硬盘驱动器、光驱和打印机等。它提供了高速数据传输和并行通信的能力，使得计算机可以与多个设备同时进行数据交换。 SCSI 接口广泛应用于服务器、工作站和存储系统等领域。::
参见《 SCSI 词汇表》中的《小型计算机系统接口》。

新加坡::
参见 <<sg-glossary ,信号地 >> 。

SMB 是指 Server Message Block 的缩写，即服务器消息块。它是一种用于在计算机网络上共享文件、打印机和其他资源的通信协议。 SMB 协议最初由 IBM 开发，后来被微软广泛采用，并成为 Windows 操作系统中文件和打印机共享的主要协议。 SMB 协议使用 TCP/IP 协议进行通信，并提供了安全认证、文件访问控制和数据传输等功能。::
请参阅《 SMB 词汇表， Server Message Block 》。

对称多处理（ SMP ）::
参见《对称多处理器（ Symmetric MultiProcessor ）》。

SMTP （ Simple Mail Transfer Protocol ）是一种用于电子邮件传输的标准协议。它定义了电子邮件客户端和服务器之间的通信规则，以确保可靠地传递电子邮件。 SMTP 使用 TCP/IP 网络来传输邮件，并使用特定的端口号（默认为 25 ）进行通信。通过 SMTP ，用户可以发送电子邮件到目标服务器，并且服务器可以将邮件传递给接收者的电子邮件客户端。 SMTP 还支持身份验证和加密机制，以确保邮件的安全性和私密性。::
参见《 SMTP （简单邮件传输协议）术语表》。

SMTP AUTH （ Simple Mail Transfer Protocol Authentication ）是一种用于电子邮件传输的身份验证机制。它允许邮件服务器在发送或接收邮件时验证用户的身份。通过 SMTP AUTH ，用户可以使用用户名和密码进行身份验证，以便发送或接收邮件。这种身份验证机制可以提高邮件传输的安全性，并防止未经授权的访问和垃圾邮件的发送。::
参见 <<smtpauth-glossary , SMTP 认证 >> 。

SSH （ Secure Shell ）是一种网络协议，用于在不安全的网络中安全地进行远程登录和执行命令。它通过加密通信和身份验证来保护数据的安全性。 SSH 广泛用于管理远程服务器和计算机，提供了一种安全的方式来访问和控制远程设备。::
请参阅《 SSH 词汇表》中的《 Secure Shell 》。

STR 是英文单词"strength"的缩写，意为"力量"或"强度"。在计算机领域中， STR 也可以指代"字符串"（ string ）的意思。::
参见 <<str-glossary ,挂起到 RAM>> 。

SVN 是一个版本控制系统，全称为 Subversion 。它被广泛用于管理和跟踪软件开发项目中的代码变更。 SVN 允许多个开发者同时工作，并提供了版本控制、分支管理、合并等功能，以便更好地协作和管理代码。::
参见 <<svn-glossary , Subversion>> 。

[[smtpauth-glossary]]
SMTP 身份验证::
{empty}

[[smb-glossary]]
服务器消息块::
{empty}

[[sg-glossary]]
信号地线::
RS232 引脚或线是信号的地线参考。

[[smtp-glossary]]
简单邮件传输协议::
{empty}

[[ssh-glossary]]
安全外壳协议::
{empty}

[[scsi-glossary]]
小型计算机系统接口::
{empty}

[[svn-glossary]]
Subversion 是一个版本控制系统，用于管理和跟踪文件和目录的变化。它允许多个用户协同工作，并提供了版本控制、分支和合并等功能。 Subversion 使用中央服务器存储文件的历史记录，并允许用户通过检出、提交和更新等操作来与服务器进行交互。它是一个开源软件，广泛用于软件开发和项目管理中。::
Subversion 是一个版本控制系统，目前被 FreeBSD 项目使用。

[[str-glossary]]
挂起到 RAM::
{empty}

[[smp-glossary]]
对称多处理器（ Symmetric MultiProcessor ，简称 SMP ）::
{empty}

[[sci-glossary]]
系统控制中断::
{empty}

[discrete]
== T

传输控制协议（ TCP ）::
参见《传输控制协议》。

TCP/IP 是一种网络协议套件，用于在计算机网络中进行通信。它由两个主要协议组成：传输控制协议（ TCP ）和 Internet 协议（ IP ）。 TCP 负责在网络上可靠地传输数据，而 IP 则负责将数据包从一个网络节点传输到另一个网络节点。 TCP/IP 是互联网的基础协议，也被广泛应用于局域网和广域网中。::
参见《传输控制协议 / 互联网协议》（ Transmission Control Protocol/Internet Protocol ）的 <<tcpip-glossary ,术语表 >> 。

TD::
参见 <<td-glossary ,传输数据 >> 。

TFTP （ Trivial File Transfer Protocol ）是一种简单的文件传输协议，用于在计算机网络中传输文件。它通常用于在本地网络中快速传输小型文件，如配置文件、固件等。 TFTP 使用 UDP 协议进行通信，并且没有身份验证或加密功能。它的设计目标是简单和高效，因此功能相对较少。 TFTP 常用于网络设备的配置和维护，以及在计算机之间传输引导程序和操作系统映像。::
参见 <<tftp-glossary , Trivial FTP>> 。

TGT::
请参阅 <<tgt-glossary ,票据授权票 >> 。

TSC 是指技术指导委员会（ Technical Steering Committee ），它是一个由技术专家组成的团队，负责指导和监督项目的技术方向和决策。 TSC 的成员通常是项目的核心贡献者和领导者，他们负责评审和批准新功能、技术架构和项目发展计划。 TSC 的目标是确保项目的技术方向与项目的愿景和目标保持一致，并促进项目的技术创新和发展。::
参见 <<tsc-glossary , 时间戳计数器 >> 。

[[tgt-glossary]]
票据授予票据::
{empty}

[[tsc-glossary]]
时间戳计数器::
现代 Pentium(R) 处理器内部的性能分析计数器，用于计算核心频率时钟周期。

[[tcp-glossary]]
传输控制协议::
一种位于（例如） IP 协议之上的协议，确保数据包以可靠、有序的方式传递。

[[tcpip-glossary]]
传输控制协议 / 互联网协议::
TCP/IP 是指运行在 IP 协议之上的 TCP 协议的组合术语。互联网的大部分运行都是基于 TCP/IP 。

[[td-glossary]]
传输的数据::
RS232C 引脚或线是用于传输数据的。
+
请参阅 <<rd-glossary ,也收到的数据 >> 。

[[tftp-glossary]]
Trivial FTP （简称 TFTP ）::
{empty}

[discrete]
== U

用户数据报协议（ UDP ）::
参见《用户数据报协议》（ User Datagram Protocol ）的 <<udp-glossary ,词汇表 >> 。

UFS1::
请参阅《 Unix 文件系统版本 1 》的 <<ufs1-glossary , Unix 文件系统版本 1>> 部分。

UFS2::
参见 <<ufs2-glossary , Unix 文件系统版本 2>> 。

用户标识::
参见 <<uid-glossary ,用户 ID>> 。

URL （ Uniform Resource Locator ）是统一资源定位符的缩写，用于标识和定位互联网上的资源。它是一个字符串，包含了资源的地址和访问方式。 URL 通常由协议、主机名、端口号、路径和查询参数等组成，可以用于访问网页、图片、视频等各种类型的资源。::
参见 <<url-glossary ,统一资源定位符 >> 。

通用串行总线（ Universal Serial Bus ），简称 USB ，是一种用于连接计算机与外部设备的通信接口标准。它可以用于连接各种设备，如打印机、键盘、鼠标、摄像头、移动存储设备等。 USB 接口具有热插拔、高速传输、简单易用等特点，已经成为计算机领域中最常用的接口之一。::
参见《通用串行总线》。

[[url-glossary]]
统一资源定位符::
一种定位资源的方法，例如在互联网上定位文档以及识别该资源的手段。

[[ufs1-glossary]]
Unix 文件系统版本 1::
原始的 UNIX(R) 文件系统，有时被称为伯克利快速文件系统。

[[ufs2-glossary]]
Unix 文件系统版本 2::
UFS2 是 UFS1 的扩展，引入于 FreeBSD 5-CURRENT 。 UFS2 增加了 64 位块指针（突破了 1T 的限制），支持扩展文件存储和其他功能。

[[usb-glossary]]
通用串行总线::
一种硬件标准，用于将各种计算机外设连接到通用接口。

[[uid-glossary]]
用户 ID::
计算机中为每个用户分配的唯一编号，通过该编号可以识别分配给该用户的资源和权限。

[[udp-glossary]]
用户数据报协议::
UDP 是一种简单而不可靠的数据报协议，用于在 TCP/IP 网络上交换数据。 UDP 不像 TCP 那样提供错误检查和纠正。

[discrete]
== V

虚拟专用网络（ VPN ）::
请参阅《虚拟私人网络》的 <<vpn-glossary ,虚拟私人网络 >> 部分。

[[vpn-glossary]]
虚拟专用网络::
一种使用公共电信网络（如互联网）来提供对本地网络（如企业局域网）的远程访问的方法。
