---
description: '如何获取 FreeBSD ： CD 和 DVD 套装， FTP 站点以及如何安装和使用 Git'
next: books/handbook/bibliography
part: '第五部分 . 附录'
path: /books/handbook/
prev: books/handbook/partv
showBookMenu: true
tags: ["Obtaining", "CD", "DVD", "FTP", "Git"]
title: '附录 A. 获取 FreeBSD'
weight: 41
---

[appendix]
= 获取 FreeBSD 

您可以通过以下方式获取 FreeBSD ：
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: A
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/mirrors/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[] include::shared/{{% lang %}}/teams.adoc[] include::shared/{{% lang %}}/mailing-lists.adoc[] include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[mirrors]]
== 镜像

FreeBSD 项目的官方镜像由项目集群管理员操作的多台机器组成，并且通过 GeoDNS 进行管理，以将用户引导到最近的可用镜像。当前的镜像位置包括澳大利亚、巴西、德国、日本（两个站点）、马来西亚、南非、台湾、英国和美国（加利福尼亚州、新泽西州和华盛顿州）。

官方镜像服务：

[cols="1,1,3"]
|===
| 服务名称 | 协议 | 更多信息

| **docs.FreeBSD.org** 是一个提供 FreeBSD 操作系统文档的网站。
| 链接： https://docs.FreeBSD.org/
| FreeBSD 文档门户网站。

| **download.FreeBSD.org** 是一个提供 FreeBSD 操作系统下载的网站。
| 链接： https://download.FreeBSD.org/ [https] 链接： ftp://download.FreeBSD.org/pub/FreeBSD/ [ftp]
| 与 `ftp.FreeBSD.org` 相同的内容， `ftp` 是一个遗留的名称；推荐使用 `download.FreeBSD.org` 。

| **git.FreeBSD.org** 是一个用于 FreeBSD 操作系统的 Git 代码托管服务。
| 通过 `https` 和 `ssh` 使用 git
| 更多详细信息请参考链接： https://docs.freebsd.org/en/books/handbook/mirrors/#git[使用 git] 部分。

| **pkg.FreeBSD.org** 是一个用于 FreeBSD 操作系统的软件包管理系统。
| man:pkg[8] 可以通过 `http` 和 `https` 进行下载。
| man:pkg[8] 程序使用的官方 FreeBSD 软件包仓库。

| **vuxml.FreeBSD.org** / **www.VuXML.org** 是一个网站，用于发布和维护 FreeBSD 操作系统的安全漏洞信息。
| 链接： https://www.vuxml.org/ [https]
| FreeBSD 项目的 VuXML 网页。 `pkg audit` 从该服务获取漏洞列表。

| **www.FreeBSD.org**
| 链接： https://www.FreeBSD.org/ [https]
| FreeBSD 网站。
|===

所有官方镜像都支持 IPv4 和 IPv6 。

http://ftp-archive.FreeBSD.org 不在 GeoDNS 基础设施中，只托管在一个地点（美国）。

该项目正在寻找新的场地；愿意赞助的人，请联系集群管理员团队获取更多信息。

由社区和其他公司维护的镜像列表：

[cols="1,1,3"]
|===
|国家 | 主机名 | 协议

| 澳大利亚图标： envelope[link = mailto:{mirrors-australia-email} , title ="镜像联系"]
| ftp.au.FreeBSD.org 是一个位于澳大利亚的 FreeBSD 镜像站点。
| 链接： http://ftp.au.FreeBSD.org/pub/FreeBSD[http] 链接： http://ftp.au.FreeBSD.org/pub/FreeBSD[http_v6] 链接： rsync://ftp.au.FreeBSD.org[rsync] 链接： rsync://ftp.au.FreeBSD.org[rsync_v6]

| 
| ftp3.au.FreeBSD.org 是一个位于澳大利亚的 FreeBSD 镜像站点。
| 链接： [http://ftp3.au.FreeBSD.org/pub/FreeBSD](http://ftp3.au.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp3.au.FreeBSD.org/pub/FreeBSD](ftp://ftp3.au.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp3.au.FreeBSD.org](rsync://ftp3.au.FreeBSD.org)

| 奥地利图标： envelope[link = mailto:{mirrors-austria-email} , title ="镜像联系方式"]
| ftp.at.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： http://ftp.at.FreeBSD.org/pub/FreeBSD/[http] 
链接： http://ftp.at.FreeBSD.org/pub/FreeBSD/[http_v6] 
链接： ftp://ftp.at.FreeBSD.org/pub/FreeBSD/[ftp] 
链接： ftp://ftp.at.FreeBSD.org/pub/FreeBSD/[ftp_v6] 
链接： rsync://ftp.at.FreeBSD.org/pub/FreeBSD/[rsync] 
链接： rsync://ftp.at.FreeBSD.org/pub/FreeBSD/[rsync_v6]

| 巴西图标： envelope[link = mailto:{mirrors-brazil-email} , title ="镜像联系方式"]
| ftp2.br.FreeBSD.org 是一个位于巴西的 FreeBSD 镜像站点。
| 链接： http://ftp2.br.FreeBSD.org/FreeBSD[http] 
链接： rsync://ftp2.br.FreeBSD.org[rsync] 
链接： rsync://ftp2.br.FreeBSD.org[rsync_v6]

| 
| ftp3.br.FreeBSD.org 是一个位于巴西的 FreeBSD 镜像站点。
| 链接： [http://ftp3.br.FreeBSD.org/pub/FreeBSD](http://ftp3.br.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp3.br.FreeBSD.org/pub/FreeBSD](ftp://ftp3.br.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp3.br.FreeBSD.org](rsync://ftp3.br.FreeBSD.org)

| 保加利亚图标： envelope[link = mailto:{mirrors-bulgaria-email} , title ="镜像联系人"]
| ftp.bg.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： ftp://ftp.bg.FreeBSD.org/pub/FreeBSD[ftp] 链接： ftp://ftp.bg.FreeBSD.org/pub/FreeBSD[ftp_v6] 链接： rsync://ftp.bg.FreeBSD.org[rsync] 链接： rsync://ftp.bg.FreeBSD.org[rsync_v6]

| 捷克共和国图标： envelope[link = mailto:{mirrors-czech-email} , title ="镜像联系方式"]
| ftp.cz.FreeBSD.org 是一个位于捷克共和国的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和访问。
| 链接： http://ftp.cz.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp.cz.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： rsync://ftp.cz.FreeBSD.org[rsync] 
链接： rsync://ftp.cz.FreeBSD.org[rsync_v6]

| 丹麦图标： envelope[link = mailto:{mirrors-denmark-email} , title ="镜像联系方式"]
| ftp.dk.FreeBSD.org 是一个位于丹麦的 FreeBSD 软件的 FTP 服务器。
| 链接： http://ftp.dk.FreeBSD.org/FreeBSD/[http] 
链接： http://ftp.dk.FreeBSD.org/FreeBSD/[http_v6] 
链接： ftp://ftp.dk.FreeBSD.org/FreeBSD/[ftp] 
链接： ftp://ftp.dk.FreeBSD.org/FreeBSD/[ftp_v6] 
链接： rsync://ftp.dk.FreeBSD.org/FreeBSD/[rsync] 
链接： rsync://ftp.dk.FreeBSD.org/FreeBSD/[rsync_v6]

| 芬兰图标： envelope[link = mailto:{mirrors-finland-email} , title ="镜像联系人"]
| ftp.fi.FreeBSD.org 是一个位于芬兰的 FreeBSD 软件下载站点。
| 链接： ftp://ftp.fi.FreeBSD.org/pub/FreeBSD[ftp]

| 法国图标： envelope[link = mailto:{mirrors-france-email} , title ="镜像联系方式"]
| ftp.fr.FreeBSD.org 是一个位于法国的 FTP 服务器，用于下载 FreeBSD 操作系统和相关软件。
| 链接： http://ftp.fr.FreeBSD.org/pub/FreeBSD[http] 链接： http://ftp.fr.FreeBSD.org/pub/FreeBSD[http_v6] 链接： ftp://ftp.fr.FreeBSD.org/pub/FreeBSD[ftp] 链接： ftp://ftp.fr.FreeBSD.org/pub/FreeBSD[ftp_v6] 链接： rsync://ftp.fr.FreeBSD.org[rsync] 链接： rsync://ftp.fr.FreeBSD.org[rsync_v6]

| 
| ftp3.fr.FreeBSD.org 是一个位于法国的 FreeBSD 镜像站点。
| 链接： ftp://ftp3.fr.FreeBSD.org/pub/FreeBSD[ftp]

| 
| ftp6.fr.FreeBSD.org 是一个位于法国的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和更新。
| 链接： [http://ftp6.fr.FreeBSD.org/pub/FreeBSD](http://ftp6.fr.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp6.fr.FreeBSD.org/pub/FreeBSD](ftp://ftp6.fr.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp6.fr.FreeBSD.org](rsync://ftp6.fr.FreeBSD.org)

| 德国图标： envelope[link = mailto:{mirrors-germany-email} , title ="镜像联系方式"]
| ftp.de.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接 : ftp://ftp.de.FreeBSD.org/pub/FreeBSD[ftp] 链接 : ftp://ftp.de.FreeBSD.org/pub/FreeBSD[ftp_v6] 链接 : rsync://ftp.de.FreeBSD.org[rsync] 链接 : rsync://ftp.de.FreeBSD.org[rsync_v6]

| 
| ftp1.de.FreeBSD.org 是一个位于德国的 FreeBSD 镜像站点。
| 链接： http://ftp1.de.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp1.de.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp1.de.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp1.de.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp1.de.FreeBSD.org[rsync] 
链接： rsync://ftp1.de.FreeBSD.org[rsync_v6]

| 
| ftp2.de.FreeBSD.org 是一个位于德国的 FreeBSD 镜像站点。
| 链接： http://ftp2.de.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp2.de.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp2.de.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp2.de.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp2.de.FreeBSD.org[rsync] 
链接： rsync://ftp2.de.FreeBSD.org[rsync_v6]

| 
| ftp5.de.FreeBSD.org 是一个位于德国的 FreeBSD 软件下载站点。
| 链接 : ftp://ftp5.de.FreeBSD.org/pub/FreeBSD[ftp] 链接 : ftp://ftp5.de.FreeBSD.org/pub/FreeBSD[ftp_v6]

| 
| ftp7.de.FreeBSD.org 是一个位于德国的 FreeBSD 镜像站点。
| 链接： http://ftp7.de.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp7.de.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp7.de.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp7.de.FreeBSD.org/pub/FreeBSD[ftp_v6]

| 希腊图标： envelope[link = mailto:{mirrors-greece-email} , title ="镜像联系方式"]
| ftp.gr.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： http://ftp.gr.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp.gr.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp.gr.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp.gr.FreeBSD.org/pub/FreeBSD[ftp_v6]

| 
| ftp2.gr.FreeBSD.org 是一个用于下载 FreeBSD 操作系统的 FTP 服务器。
| 链接： http://ftp2.gr.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp2.gr.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp2.gr.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp2.gr.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp2.gr.FreeBSD.org[rsync]

| 日本图标： envelope[link = mailto:{mirrors-japan-email} , title ="镜像联系"]
| ftp.jp.FreeBSD.org 是一个位于日本的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和更新。用户可以通过该服务器访问和获取 FreeBSD 的安装镜像、软件包和补丁等资源。
| 链接： http://ftp.jp.FreeBSD.org/pub/FreeBSD[http] 链接： http://ftp.jp.FreeBSD.org/pub/FreeBSD[http_v6] 链接： ftp://ftp.jp.FreeBSD.org/pub/FreeBSD[ftp] 链接： ftp://ftp.jp.FreeBSD.org/pub/FreeBSD[ftp_v6] 链接： rsync://ftp.jp.FreeBSD.org[rsync] 链接： rsync://ftp.jp.FreeBSD.org[rsync_v6]

| 
| ftp2.jp.FreeBSD.org 是一个位于日本的 FreeBSD 镜像站点。
| 链接： ftp://ftp2.jp.FreeBSD.org/pub/FreeBSD[ftp] 链接： rsync://ftp2.jp.FreeBSD.org[rsync] 链接： rsync://ftp2.jp.FreeBSD.org[rsync_v6]

| 
| ftp3.jp.FreeBSD.org 是一个位于日本的 FreeBSD 镜像站点。
| 链接： http://ftp3.jp.FreeBSD.org/pub/FreeBSD [http] 
链接： rsync://ftp3.jp.FreeBSD.org [rsync]

| 
| ftp4.jp.FreeBSD.org 是一个位于日本的 FreeBSD 软件镜像站点。
| 链接： ftp://ftp4.jp.FreeBSD.org/pub/FreeBSD[ftp]

| 
| ftp6.jp.FreeBSD.org 是一个位于日本的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和更新。
| 链接： http://ftp6.jp.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp6.jp.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp6.jp.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp6.jp.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp6.jp.FreeBSD.org[rsync] 
链接： rsync://ftp6.jp.FreeBSD.org[rsync_v6]

| 哈萨克斯坦图标： envelope[link = mailto:support @ ps.kz , title ="镜像联系方式"]
| 镜像 .ps.kz
| http://mirror.ps.kz/freebsd[http] 链接： ftp://mirror.ps.kz/freebsd[ftp]

| 
| 镜像 .neolabs.kz
| 链接： [http://mirror.neolabs.kz/freebsd](http://mirror.neolabs.kz/freebsd) 
链接： [ftp://mirror.neolabs.kz/freebsd](ftp://mirror.neolabs.kz/freebsd)

| 韩国图标： envelope[link = mailto:{mirrors-korea-email} , title ="镜像联系方式"]
| ftp.kr.FreeBSD.org 是一个位于韩国的 FreeBSD 镜像站点。
| 链接： http://ftp.kr.FreeBSD.org/pub/FreeBSD[http] 链接： https://ftp.kr.FreeBSD.org/pub/FreeBSD[https] 链接： ftp://ftp.kr.FreeBSD.org/pub/FreeBSD[ftp] 链接： rsync://ftp.kr.FreeBSD.org[rsync]

| 
| ftp2.kr.FreeBSD.org 是一个位于韩国的 FreeBSD 镜像站点。
| 链接： rsync://ftp2.kr.FreeBSD.org[rsync]

| 拉脱维亚图标： envelope[link = mailto:{mirrors-latvia-email} , title ="镜像联系人"]
| ftp.lv.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： [http://ftp.lv.FreeBSD.org/freebsd](http://ftp.lv.FreeBSD.org/freebsd) 
链接： [ftp://ftp.lv.FreeBSD.org/freebsd](ftp://ftp.lv.FreeBSD.org/freebsd)

| 荷兰图标： envelope[link = mailto:{mirrors-netherlands-email} , title ="镜像联系人"]
| ftp.nl.FreeBSD.org 是一个位于荷兰的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和访问。
| 链接： http://ftp.nl.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp.nl.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp.nl.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp.nl.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp.nl.FreeBSD.org[rsync] 
链接： rsync://ftp.nl.FreeBSD.org[rsync_v6]

| 
| ftp2.nl.FreeBSD.org 是一个位于荷兰的 FreeBSD 镜像站点。
| 链接： [http://ftp2.nl.FreeBSD.org/pub/FreeBSD](http://ftp2.nl.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp2.nl.FreeBSD.org/pub/FreeBSD](ftp://ftp2.nl.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp2.nl.FreeBSD.org](rsync://ftp2.nl.FreeBSD.org)

| 
| mirror.nl.altushost.com 是一个网站的镜像地址。
| 链接： https://mirror.nl.altushost.com/FreeBSD[https]

| 新西兰图标： envelope[link = mailto:{mirrors-new-zealand-email} , title ="镜像联系人"]
| ftp.nz.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： [http://ftp.nz.FreeBSD.org/pub/FreeBSD](http://ftp.nz.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp.nz.FreeBSD.org/pub/FreeBSD](ftp://ftp.nz.FreeBSD.org/pub/FreeBSD)

| 挪威图标： envelope[link = mailto:{mirrors-norway-email} , title ="镜像联系人"]
| ftp.no.FreeBSD.org 是一个免费的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和访问。
| 链接： ftp://ftp.no.FreeBSD.org/pub/FreeBSD[ftp] 链接： ftp://ftp.no.FreeBSD.org/pub/FreeBSD[ftp_v6] 链接： rsync://ftp.no.FreeBSD.org[rsync] 链接： rsync://ftp.no.FreeBSD.org[rsync_v6]

| 波兰图标： envelope[link = mailto:{mirrors-poland-email} , title ="镜像联系方式"]
| ftp.pl.FreeBSD.org 是一个用于下载 FreeBSD 操作系统的 FTP 服务器。
| 链接： [http://ftp.pl.FreeBSD.org/pub/FreeBSD](http://ftp.pl.FreeBSD.org/pub/FreeBSD) 
链接： [http_v6://ftp.pl.FreeBSD.org/pub/FreeBSD](http_v6://ftp.pl.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp.pl.FreeBSD.org/pub/FreeBSD](ftp://ftp.pl.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp.pl.FreeBSD.org](rsync://ftp.pl.FreeBSD.org) 
链接： [rsync_v6://ftp.pl.FreeBSD.org](rsync_v6://ftp.pl.FreeBSD.org)

| 俄罗斯图标： envelope[link = mailto:{mirrors-russia-email} , title ="镜像联系方式"]
| ftp.ru.FreeBSD.org 是一个免费的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和访问。
| 链接： http://ftp.ru.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp.ru.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp.ru.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp.ru.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp.ru.FreeBSD.org[rsync] 
链接： rsync://ftp.ru.FreeBSD.org[rsync_v6]

| 
| ftp2.ru.FreeBSD.org 是一个免费的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和访问。
| 链接： https://ftp2.ru.FreeBSD.org/pub/FreeBSD[https] 链接： ftp://ftp2.ru.FreeBSD.org/pub/FreeBSD[ftp] 链接： rsync://ftp2.ru.FreeBSD.org[rsync]

| 斯洛文尼亚图标： envelope[link = mailto:{mirrors-slovenia-email} , title ="镜像联系方式"]
| ftp.si.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： http://ftp.si.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp.si.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp.si.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp.si.FreeBSD.org/pub/FreeBSD[ftp_v6]

| 南非图标： envelope[link = mailto:{mirrors-south-africa-email} , title ="镜像联系方式"]
| ftp.za.FreeBSD.org 是一个用于下载 FreeBSD 操作系统的 FTP 服务器。
| 链接： https://ftp.za.FreeBSD.org/pub/FreeBSD[https] 链接： https://ftp.za.FreeBSD.org/pub/FreeBSD[https_v6] 链接： rsync://ftp.za.FreeBSD.org[rsync] 链接： rsync://ftp.za.FreeBSD.org[rsync_v6]

| 
| ftp2.za.FreeBSD.org 是一个免费的 FTP 服务器，用于提供 FreeBSD 操作系统的下载和访问。
| 链接： [http://ftp2.za.FreeBSD.org/pub/FreeBSD](http://ftp2.za.FreeBSD.org/pub/FreeBSD) 
链接： [http://ftp2.za.FreeBSD.org/pub/FreeBSD](http://ftp2.za.FreeBSD.org/pub/FreeBSD) （ IPv6 ）
链接： [ftp://ftp2.za.FreeBSD.org/pub/FreeBSD](ftp://ftp2.za.FreeBSD.org/pub/FreeBSD) （ IPv6 ）

| 
| ftp4.za.FreeBSD.org 是一个位于南非的 FreeBSD 软件下载站点。
| 链接： [http://ftp4.za.FreeBSD.org/pub/FreeBSD](http://ftp4.za.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp4.za.FreeBSD.org/pub/FreeBSD](ftp://ftp4.za.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp4.za.FreeBSD.org](rsync://ftp4.za.FreeBSD.org)

| 瑞典图标： envelope[link = mailto:{mirrors-sweden-email} , title ="镜像联系方式"]
| ftp.se.FreeBSD.org 是一个位于瑞典的 FreeBSD 软件的 FTP 服务器。
| 链接： [http://ftp.se.FreeBSD.org/pub/FreeBSD](http://ftp.se.FreeBSD.org/pub/FreeBSD) 
链接： [http_v6://ftp.se.FreeBSD.org/pub/FreeBSD](http_v6://ftp.se.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp.se.FreeBSD.org/pub/FreeBSD](ftp://ftp.se.FreeBSD.org/pub/FreeBSD) 
链接： [ftp_v6://ftp.se.FreeBSD.org/pub/FreeBSD](ftp_v6://ftp.se.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp.se.FreeBSD.org](rsync://ftp.se.FreeBSD.org) 
链接： [rsync_v6://ftp.se.FreeBSD.org](rsync_v6://ftp.se.FreeBSD.org)

| 
| 镜像地址： mirror.se.altushost.com
| 链接： https://mirror.se.altushost.com/FreeBSD[https]

| 台湾图标： envelope[link = mailto:{mirrors-taiwan-email} , title ="镜像联系方式"]
| ftp4.tw.FreeBSD.org 是一个位于台湾的 FreeBSD 软件下载站点。
| 链接： https://ftp4.tw.FreeBSD.org/pub/FreeBSD[https] 链接： ftp://ftp4.tw.FreeBSD.org/pub/FreeBSD[ftp] 链接： rsync://ftp4.tw.FreeBSD.org[rsync]

| 
| ftp5.tw.FreeBSD.org 是一个位于台湾的 FreeBSD 镜像站点。
| 链接： [http://ftp5.tw.FreeBSD.org/pub/FreeBSD](http://ftp5.tw.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp5.tw.FreeBSD.org/pub/FreeBSD](ftp://ftp5.tw.FreeBSD.org/pub/FreeBSD)

| 乌克兰图标： envelope[link = mailto:{mirrors-ukraine-email} , title ="镜像联系方式"]
| ftp.ua.FreeBSD.org 是一个提供 FreeBSD 操作系统下载的 FTP 服务器。
| 链接： [http://ftp.ua.FreeBSD.org/pub/FreeBSD](http://ftp.ua.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp.ua.FreeBSD.org/pub/FreeBSD](ftp://ftp.ua.FreeBSD.org/pub/FreeBSD) 
链接： [ftp://ftp.ua.FreeBSD.org/pub/FreeBSD](ftp://ftp.ua.FreeBSD.org/pub/FreeBSD) 
链接： [rsync://ftp.ua.FreeBSD.org](rsync://ftp.ua.FreeBSD.org) 
链接： [rsync://ftp.ua.FreeBSD.org](rsync://ftp.ua.FreeBSD.org)

| 英国图标： envelope[link = mailto:{mirrors-uk-email} , title ="镜像联系人"]
| ftp.uk.FreeBSD.org 是一个位于英国的 FreeBSD 软件下载站点。
| 链接： http://ftp.uk.FreeBSD.org/pub/FreeBSD[http] 链接： http://ftp.uk.FreeBSD.org/pub/FreeBSD[http_v6] 链接： ftp://ftp.uk.FreeBSD.org/pub/FreeBSD[ftp] 链接： ftp://ftp.uk.FreeBSD.org/pub/FreeBSD[ftp_v6] 链接： rsync://ftp.uk.FreeBSD.org[rsync] 链接： rsync://ftp.uk.FreeBSD.org[rsync_v6]

| 
| ftp2.uk.FreeBSD.org 是一个位于英国的 FreeBSD 镜像站点。
| 链接： http://ftp2.uk.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp2.uk.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： https://ftp2.uk.FreeBSD.org/pub/FreeBSD[https] 
链接： https://ftp2.uk.FreeBSD.org/pub/FreeBSD[https_v6] 
链接： ftp://ftp2.uk.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp2.uk.FreeBSD.org/pub/FreeBSD[ftp_v6]

| 美利坚合众国 icon:envelope[link = mailto:{mirrors-us-email} , title ="镜像联系方式"]
| ftp11.FreeBSD.org 是一个用于下载 FreeBSD 操作系统的 FTP 服务器。
| 链接： http://ftp11.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp11.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp11.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp11.FreeBSD.org/pub/FreeBSD[ftp_v6] 
链接： rsync://ftp11.FreeBSD.org[rsync] 
链接： rsync://ftp11.FreeBSD.org[rsync_v6]

| 
| ftp14.FreeBSD.org 是一个用于下载 FreeBSD 操作系统的 FTP 服务器。
| 链接： ftp://ftp14.FreeBSD.org/pub/FreeBSD[ftp] 链接： rsync://ftp14.FreeBSD.org[rsync] （前官方一级镜像）

| 
| ftp5.FreeBSD.org 是一个用于下载 FreeBSD 操作系统的 FTP 服务器。
| 链接： http://ftp5.FreeBSD.org/pub/FreeBSD[http] 
链接： http://ftp5.FreeBSD.org/pub/FreeBSD[http_v6] 
链接： ftp://ftp5.FreeBSD.org/pub/FreeBSD[ftp] 
链接： ftp://ftp5.FreeBSD.org/pub/FreeBSD[ftp_v6]
|===

社区镜像支持的协议列表最近更新于 2022 年 1 月 31 日，但不保证实时更新。

[[git]]
== 使用 Git

[[git-intro]]
=== 介绍

截至 2020 年 12 月， FreeBSD 使用 git 作为存储所有 FreeBSD 基础源代码和文档的主要版本控制系统。截至 2021 年 4 月， FreeBSD 使用 git 作为存储所有 FreeBSD Ports 集合的唯一版本控制系统。

[NOTE]
====
Git 通常是开发者工具。用户可能更喜欢使用 `freebsd-update` （参见： cutting-edge[updating-upgrading-freebsdupdate ，“ FreeBSD Update ”] ）来更新 FreeBSD 基本系统，以及使用 `git` （参见： ports[ports-using ，“使用 Ports Collection ”] ）来更新 FreeBSD Ports Collection 。
====

本节演示了如何在 FreeBSD 系统上安装 Git ，并使用它创建一个 FreeBSD 源代码仓库的本地副本。

[[git-install]]
=== 安装

Git 可以从 Ports Collection 安装，也可以作为一个软件包安装：

[source, shell]
....
# pkg install git
....

[[git-usage]]
=== 运行 Git

要将源代码的干净副本获取到本地目录中，使用 `git clone` 命令。这个文件目录被称为 _工作树_。

Git 使用 URL 来指定一个仓库。有三个不同的仓库， `src` 用于 FreeBSD 系统源代码， `doc` 用于文档， `ports` 用于 FreeBSD Ports 集合。这三个仓库都可以通过两种不同的协议访问： HTTPS 和 SSH 。例如， URL `https://git.FreeBSD.org/src.git` 指定了 `src` 仓库的主分支，使用 `https` 协议。

[[git-url-table]]
.FreeBSD Git 仓库 URL 表格
[options="header,footer"]
|=======================================================
|项目 | Git URL 是指指向 Git 仓库的统一资源定位符。
| 通过 HTTPS 访问只读源代码仓库             | `https://git.FreeBSD.org/src.git`
| 通过匿名 SSH 只读访问源代码仓库          | `ssh://anongit @ git.FreeBSD.org/src.git` 是一个指向 FreeBSD 源代码仓库的 SSH 链接。
| 通过 HTTPS 访问的只读文档仓库             | `https://git.FreeBSD.org/doc.git` 是一个指向 FreeBSD 文档存储库的 URL 。
| 通过匿名 SSH 访问的只读文档仓库          | `ssh://anongit @ git.FreeBSD.org/doc.git` 是一个指向 FreeBSD 文档仓库的 SSH 链接。
| 通过 HTTPS 访问只读端口的代码仓库           | `https://git.FreeBSD.org/ports.git` 是一个指向 FreeBSD ports 仓库的 URL 。
| 通过匿名 SSH 访问只读端口的代码仓库        | `ssh://anongit @ git.FreeBSD.org/ports.git` 是一个指向 FreeBSD 软件包集合的 Git 仓库的 SSH 链接。
|=======================================================

项目成员维护的外部镜像也可用；请参考 <<external-mirrors>> 部分。

要克隆 FreeBSD 系统源代码仓库的副本：

[source, shell]
....
# git clone -o freebsd https://git.FreeBSD.org/src.git /usr/src
....

`-o freebsd` 选项指定了源；按照 FreeBSD 文档的约定，源被假定为 `freebsd` 。由于初始检出必须下载远程存储库的完整分支，可能需要一些时间。请耐心等待。

最初，工作树包含了与 CURRENT 对应的 `main` 分支的源代码。要切换到 13-STABLE 分支，可以执行以下操作：
[source, shell]
....
# cd /usr/src
# git checkout stable/13
....

可以使用 `git pull` 命令更新工作树。要更新上面示例中创建的文件 `/usr/src` ，请使用：

[source, shell]
....
# cd /usr/src
# git pull --rebase
....

更新比检出要快得多，只传输已更改的文件。

=== 基于 Web 的代码仓库浏览器

FreeBSD 项目使用 cgit 作为基于 Web 的存储库浏览器： link:https://cgit.FreeBSD.org/[https://cgit.FreeBSD.org/] 。

=== 开发者指南

有关对存储库的写访问权限的信息，请参阅 extref:{committers-guide}[Committer's Guide , git-mini-primer] 。

[[external-mirrors]]
=== 外部镜像源

这些镜像不托管在 FreeBSD.org 上，但仍由项目成员维护。用户和开发者可以在这些镜像上拉取或浏览存储库。 `doc` 和 `src` GitHub 存储库的拉取请求正在接受；否则，与这些镜像的项目工作流程仍在讨论中。

Codeberg 是一个基于 Git 的开源代码托管平台。它提供了类似于 GitHub 的功能，允许开发者在上面创建和管理代码仓库，并与其他开发者进行协作。 Codeberg 致力于保护用户的隐私和数据安全，并且完全开放源代码。它是一个社区驱动的平台，旨在为开源项目提供一个自由、开放和可持续的托管解决方案。::
  - 文档： https://codeberg.org/FreeBSD/freebsd-doc
  - 端口： https://codeberg.org/FreeBSD/freebsd-ports
  - 源代码： https://codeberg.org/FreeBSD/freebsd-src

GitHub 是一个基于云端的代码托管平台，它提供了版本控制、协作功能和项目管理工具。开发者可以使用 GitHub 来存储、管理和共享他们的代码，并与其他开发者进行协作。 GitHub 还提供了一系列的功能，如问题跟踪、代码审查和持续集成，以帮助开发者更好地管理和维护他们的项目。::
  - 文档： https://github.com/freebsd/freebsd-doc
  - 端口： https://github.com/freebsd/freebsd-ports
  - 源代码： https://github.com/freebsd/freebsd-src

GitLab 是一个基于 Web 的 Git 仓库管理工具，它提供了版本控制、问题跟踪、持续集成等功能。 GitLab 是一个开源项目，可以自己搭建私有的 Git 仓库，也可以使用 GitLab 提供的托管服务。它是一个功能强大且易于使用的工具，被广泛用于软件开发团队的协作和代码管理。::
  - 文档： https://gitlab.com/FreeBSD/freebsd-doc
  - 端口： https://gitlab.com/FreeBSD/freebsd-ports
  - 源代码： https://gitlab.com/FreeBSD/freebsd-src

=== 邮件列表

FreeBSD 项目中用于一般使用和关于 git 的问题的主要邮件列表是 https://lists.freebsd.org/subscription/freebsd-git[freebsd-git] 。有关更多详细信息，包括提交消息列表，请参阅 crossref:handbook/eresources[eresources-mail ，邮件列表] 章节。

=== SSH 主机密钥

* gitrepo.FreeBSD.org 主机的指纹：
** ECDSA 密钥指纹为 `SHA256:seWO5D27ySURcx4bknTNKlC1mgai0whP443PAKEvvZA` 。
** ED25519 密钥指纹为 `SHA256:lNR6i4BEOaaUhmDHBA1WJsO7H3KtvjE2r5q4sOxtIWo` 。
** RSA 密钥指纹为 `SHA256:f453CUEFXEJAXlKeEHV + ajJfeEfx9MdKQUD7lIscnQI` 。

* git.FreeBSD.org 主机密钥指纹：
** ECDSA 密钥指纹为 `SHA256:/UlirUAsGiitupxmtsn7f9b7zCWd0vCs4Yo/tpVWP9w` 。
** ED25519 密钥指纹为 `SHA256:y1ljKrKMD3lDObRUG3xJ9gXwEIuqnh306tSyFd1tuZE` 。
** RSA 密钥指纹为 `SHA256:jBe6FQGoH4HjvrIVM23dcnLZk9kmpdezR/CvQzm7rJM` 。

这些也被发布为 DNS 中的 SSHFP 记录。

[[svn]]
== 使用 Subversion

[[svn-intro]]
=== 介绍

截至 2020 年 12 月， FreeBSD 使用 git 作为主要版本控制系统，用于存储所有 FreeBSD 的源代码和文档。从 git 仓库的 `stable/11` 、 `stable/12` 和相关的 releng 分支中导出的更改将被导入到 Subversion 仓库中。这种导出将在这些分支的生命周期内继续进行。从 2012 年 7 月到 2021 年 3 月， FreeBSD 使用 Subversion 作为存储所有 FreeBSD Ports Collection 的唯一版本控制系统。截至 2021 年 4 月， FreeBSD 使用 git 作为存储所有 FreeBSD Ports Collection 的唯一版本控制系统。

[NOTE]
====
Subversion 通常是开发人员工具。用户可能更喜欢使用 `freebsd-update` （参见： cutting-edge[updating-upgrading-freebsdupdate ，“ FreeBSD Update ”] ）来更新 FreeBSD 基本系统，以及使用 `git` （参见： ports[ports-using ，“ Using the Ports Collection ”] ）来更新 FreeBSD Ports Collection 。 2021 年 3 月之后， Subversion 仅用于旧版本分支（ `stable/11` 和 `stable/12` ）。
====

本节介绍了如何在 FreeBSD 系统上安装 Subversion ，并使用它创建一个 FreeBSD 仓库的本地副本。还包括有关使用 Subversion 的其他信息。

[[svn-svnlite]]
=== Svnlite

在 FreeBSD 上已经安装了 Subversion 的轻量级版本 `svnlite` 。只有在需要 Python 或 Perl API ，或者需要更高版本的 Subversion 时，才需要使用端口或软件包版本的 Subversion 。

与正常的 Subversion 使用唯一的区别是命令名称为 `svnlite` 。

[[svn-install]]
=== 安装

如果 `svnlite` 不可用或者需要完整版本的 Subversion ，则必须安装它。

Subversion 可以从 Ports Collection 安装：

[source, shell]
....
# cd /usr/ports/devel/subversion
# make install clean
....

Subversion 也可以作为一个软件包进行安装：

[source, shell]
....
# pkg install subversion
....

[[svn-usage]]
=== 运行 Subversion

要将源代码的干净副本获取到本地目录中，请使用 `svn` 命令。这个目录中的文件被称为“本地工作副本”。

[WARNING]
====
在首次使用 `checkout` 之前，移动或删除现有的目标目录。在现有的非 `svn` 目录上进行 `checkout` 可能会导致现有文件与从存储库中带入的文件之间发生冲突。
====

Subversion 使用 URL 来指定一个仓库，其格式为_protocol://hostname/path_。路径的第一个组件是要访问的 FreeBSD 仓库。有三个不同的仓库， `base` 用于 FreeBSD 基本系统源代码， `ports` 用于 Ports Collection ， `doc` 用于文档。例如， URL `https://svn.FreeBSD.org/base/head/` 指定了 src 仓库的主分支，使用 `https` 协议。

使用类似以下命令从给定的代码库中进行检出操作：

[source, shell]
....
# svn checkout https://svn.FreeBSD.org/repository/branch lwcdir
....

在哪里：

* _repository_ 是项目的一个仓库： `base` 、 `ports` 或 `doc` 。
* `_branch_` 的依赖取决于所使用的代码库。 `ports` 和 `doc` 主要在 `head` 分支中进行更新，而 `base` 则在 `head` 下维护了最新版本的 -CURRENT ，并在 `stable/11` （ 11._x_）和 `stable/12` （ 12._x_）下维护了相应的最新版本的 -STABLE 分支。
* _lwcdir_ 是指定分支的内容应放置的目标目录。通常情况下，对于 `ports` 来说，目标目录是 [.filename]#/usr/ports# ，对于 `base` 来说，目标目录是 [.filename]#/usr/src# ，对于 `doc` 来说，目标目录是 [.filename]#/usr/doc# 。

这个例子使用 HTTPS 协议从 FreeBSD 仓库检出源代码树，将本地工作副本放在 [/usr/src] 目录下。如果 [/usr/src] 目录已经存在但不是由 `svn` 创建的，请在检出之前重命名或删除它。

[source, shell]
....
# svn checkout https://svn.FreeBSD.org/base/head /usr/src
....

由于初始检出需要下载远程仓库的完整分支，可能需要一些时间。请耐心等待。

在初始检出之后，可以通过运行以下命令来更新本地工作副本：

[source, shell]
....
# svn update lwcdir
....

要更新上面示例中创建的 `/usr/src` 文件，请使用以下命令：

[source, shell]
....
# svn update /usr/src
....

更新比检出要快得多，只传输已更改的文件。

在检出之后，更新本地工作副本的另一种方法是通过 [.filename]#/usr/ports# 、 [.filename]#/usr/src# 和 [.filename]#/usr/doc# 目录中的 [.filename]#Makefile# 提供的。设置 `SVN_UPDATE` 并使用 `update` 目标。例如，要更新 [.filename]#/usr/src# ：

[source, shell]
....
# cd /usr/src
# make update SVN_UPDATE=yes
....

[[svn-mirrors]]
=== Subversion 镜像站点

FreeBSD 的 Subversion 仓库是：

[.programlisting]
....
svn.FreeBSD.org
....

这是一个公开可访问的镜像网络，使用 GeoDNS 来选择合适的后端服务器。要通过浏览器查看 FreeBSD Subversion 存储库，请使用 https://svnweb.FreeBSD.org/ 。

HTTPS 是首选的协议，但是需要安装 [.filename]#security/ca_root_nss# 软件包以便自动验证证书。

=== 更多信息请参考

关于使用 Subversion 的其他信息，请参阅名为 http://svnbook.red-bean.com/[《 Subversion Book 》] 的书籍，或者 http://subversion.apache.org/docs/[Subversion 文档] 。

[[mirrors-cdrom]]
== CD 和 DVD 套装

FreeBSD CD 和 DVD 套装可从多家在线零售商购买：

* FreeBSD Mall , Inc. + 1164 Claremont Dr + Brentwood , CA + 94513 + 美国 + 电话：+ 1 925 240-6652 + 传真：+ 1 925 674-0821 + 电子邮件： info @ freebsdmall.com + 网站： https://www.freebsdmall.com

* Getlinux + 网站： https://www.getlinux.fr/

* Dr. Hinner EDV + Sch ä ftlarnstr. 10 // 4. Stock + D-81371 M ü nchen + 德国 + 电话：+ 49 171 417 544 6 + 电子邮件： infow @ hinner.de + 网站： http://www.hinner.de/linux/freebsd.html
