---
description: 本章介绍了如何安装多种桌面环境，包括网络浏览器、办公软件、文档查看器和财务软件。
next: books/handbook/multimedia
part: 第二部分：常见任务
path: /books/handbook/
prev: books/handbook/partii
showBookMenu: true
tags: ["desktop", "KDE Plasma", "GNOME", "XFCE", "MATE", "Cinnamon", "LXQT", "browsers", "Firefox", "Chromium", "Iridium", "Falkon", "Konqueror", "Epiphany", "qutebrowser", "Dillo", "Links", "w3m", "Development tools", "Visual Studio Code", "Qt Creator", "Kdevelop", "Eclipse IDE", "Vim", "Neovim", "GNU Emacs", "Productivity", "LibreOffice", "Calligra", "AbiWord", "Viewers", "Okular", "Evince", "ePDFView", "Xpdf", "Finance", "KMyMoney", "GnuCash"]
title: '第 8 章 桌面环境'
weight: 11
---

[[desktop]]
= 桌面环境
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 8
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/desktop/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[desktop-synopsis]]
== 简介

尽管 FreeBSD 因其性能和稳定性而在服务器领域很受欢迎，但它也非常适合作为日常桌面使用。在 FreeBSD ports 树中有超过 {numports} 个应用程序可用，可以轻松构建一个定制的桌面环境，可以运行各种各样的桌面应用程序。本章介绍了如何安装流行的桌面环境以及诸如网络浏览器、办公软件、文档查看器和财务软件等桌面应用程序。

先决条件：

* 阅读本章的读者应该已经了解如何在 FreeBSD 上安装 crossref:x11[x11,X Window System] 或 crossref:wayland[wayland,Wayland] 。
* 在本章中，读者被指示安装官方软件包。请参考 crossref:ports[ports-using,使用 ports 集合] 部分，以从 ports 构建定制软件包。

[[desktop-environments]]
== 桌面环境

本节介绍了如何在 FreeBSD 系统上安装和配置一些流行的桌面环境。桌面环境可以是一个简单的窗口管理器，也可以是一个完整的桌面应用套件。

.支持的桌面环境
[options="header", cols="1,1,1"]
|===
| 名称 | 许可证 | 包

| KDE Plasma
| GPL 2.0 or later
| x11/kde5

| GNOME
| GPL 2.0 or later
| x11/gnome

| XFCE
| GPL, LGPL, BSD
| x11-wm/xfce4

| MATE
| GPL 2.0, LGPL 2.0
| x11/mate

| Cinnamon
| GPL 2.0 or later
| x11/cinnamon

| LXQT
| GPL, LGPL
| x11-wm/lxqt

|===

[[kde-environment]]
=== KDE Plasma

KDE Plasma 是一个易于使用的桌面环境。该桌面提供了一套应用程序，具有一致的外观和感觉，标准化的菜单和工具栏，键绑定，配色方案，国际化以及集中式、对话框驱动的桌面配置。有关 KDE 的更多信息，请访问 link:https://kde.org/[KDE 主页] 。有关 FreeBSD 特定信息，请参阅 link:https://freebsd.kde.org/[KDE 上的 FreeBSD 主页] 。

[[kde-meta-install]]
==== 安装 KDE Plasma 元包

要安装带有 KDE 框架、 Plasma 桌面和应用程序的 KDE Plasma 元包，请执行以下操作：

[source, shell]
....
# pkg install kde5
....

[[kde-minimal-install]]
==== 最小化的 KDE Plasma 安装

要安装最小化的 KDE Plasma ，请执行以下操作：

[source, shell]
....
# pkg install plasma5-plasma
....

[TIP]
====
这个安装非常简洁。必须单独安装 Konsole，执行以下操作：

[source, shell]
....
# pkg install konsole
....
====

[[kde-configuration]]
==== 配置 KDE Plasma

KDE Plasma 使用 man:dbus-daemon[1] 作为消息总线和硬件抽象层。这个应用程序会自动作为 KDE Plasma 的依赖项安装。

在 `/etc/rc.conf` 中启用 D-BUS 服务以在系统启动时启动：

[source, shell]
....
# sysrc dbus_enable="YES"
....

要增加消息大小，请执行以下操作：

[source, shell]
....
sysctl net.local.stream.recvspace=65536
sysctl net.local.stream.sendspace=65536
....

[[kde-start]]
==== 启动 KDE Plasma

首选的 KDE Plasma 显示管理器是 package:x11/sddm[]。要安装 package:x11/sddm[]，请执行以下操作：

[source, shell]
....
# pkg install sddm
....

在 `/etc/rc.conf` 中启用 SDDM 服务以在系统启动时启动：

[source, shell]
....
# sysrc sddm_enable="YES"
....

可以通过运行以下命令在 SDDM 中设置键盘语言（例如，对于西班牙语）：

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

启动 KDE Plasma 的第二种方法是手动调用 man:startx[1]。为了使其工作，需要在 ~/.xinitrc 中添加以下行：

[source, shell]
....
% echo "exec ck-launch-session startplasma-x11" > ~/.xinitrc
....

[[gnome-environment]]
=== GNOME

GNOME 是一个用户友好的桌面环境。它包括一个用于启动应用程序和显示状态的面板，一个桌面，一套工具和应用程序，以及一套使应用程序能够合作并保持一致的约定。

[[gnome-meta-install]]
==== 安装 GNOME 元包

要安装带有 GNOME 桌面和应用程序的 GNOME 元包，请执行以下操作：

[source, shell]
....
# pkg install gnome
....

[[gnome-minimal-install]]
==== 最小化的 GNOME 安装

要安装 GNOME-lite 元包，其中包含了经过精简的 GNOME 桌面，仅包含基本功能，请执行以下操作：

[source, shell]
....
# pkg install gnome-lite
....

[[gnome-configuration]]
==== 配置 GNOME

GNOME 需要挂载 `/proc`。在系统启动时自动挂载此文件系统，请将以下行添加到 `/etc/fstab` 文件中：

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

GNOME 使用 man:dbus-daemon[1] 作为消息总线和硬件抽象的工具。这个应用程序会作为 GNOME 的依赖自动安装。

在 `/etc/rc.conf` 中启用 D-BUS 服务以在系统启动时启动：

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[gnome-start]]
==== 启动 GNOME

GNOME Display Manager（简称 GDM ）是 GNOME 首选的显示管理器。GDM 作为 GNOME 软件包的一部分进行安装。

在 `/etc/rc.conf` 中启用 GDM 以在系统启动时启动：

[source, shell]
....
# sysrc gdm_enable="YES"
....

启动 GNOME 的第二种方法是手动调用 man:startx[1]。为了使其工作，需要在 `~/.xinitrc` 中添加以下行：

[source, shell]
....
% echo "exec gnome-session" > ~/.xinitrc
....

[[xfce-environment]]
=== XFCE

XFCE 是一个基于 GTK+ 的桌面环境，它轻量级并提供了一个简单、高效、易于使用的桌面。它可以完全配置，有一个带有菜单、小部件和应用程序启动器的主面板，提供文件管理器和声音管理器，并且支持主题定制。由于它快速、轻量级和高效，非常适合内存有限的老旧或较慢的计算机。

[[xfce-install]]
==== 安装 XFCE

要安装 XFCE 元包，请执行以下命令：

[source, shell]
....
# pkg install xfce
....

[[xfce-configuration]]
==== 配置 XFCE

XFCE 需要挂载 `/proc`。在系统启动时自动挂载此文件系统，请将以下行添加到 `/etc/fstab` 中：

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

XFCE 使用 man:dbus-daemon[1] 作为消息总线和硬件抽象的工具。这个应用程序会作为 XFCE 的依赖项自动安装。

在 `/etc/rc.conf` 中启用 D-BUS 以在系统启动时启动：

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[xfce-start]]
==== 启动 XFCE

package:x11/lightdm[] 是一个支持不同显示技术的显示管理器，它非常轻量级，内存使用量少，并且性能快速，是一个很好的选择。

要安装它，请执行以下操作：

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

在 `/etc/rc.conf` 中启用 lightdm 以在系统启动时启动：

[source, shell]
....
# sysrc lightdm_enable="YES"
....

启动 XFCE 的第二种方法是手动调用 man:startx[1]。为了使其工作，需要在 `~/.xinitrc` 中添加以下行：

[source, shell]
....
% echo '. /usr/local/etc/xdg/xfce4/xinitrc' > ~/.xinitrc
....

[[mate-environment]]
=== MATE

MATE 桌面环境是 GNOME 2 的延续。它使用传统的样式，提供直观和吸引人的桌面环境。

[[mate-meta-install]]
==== 安装 MATE 元包

要安装包含 MATE 桌面和一些额外应用程序（如文本编辑器、压缩管理器等）的 MATE 元包，请执行以下操作：

[source, shell]
....
# pkg install mate
....

[[mate-minimal-install]]
==== 最小化的 MATE 安装

要安装 MATE Lite 元包，其中 MATE 桌面被精简为仅包含基本功能，请执行以下操作：

[source, shell]
....
# pkg install mate-base
....

[[mate-configuration]]
==== 配置 MATE

MATE 需要挂载 `/proc`。在系统启动时自动挂载该文件系统，请将以下行添加到 `/etc/fstab` 文件中：

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

MATE 使用 man:dbus-daemon[1] 作为消息总线和硬件抽象层。这个应用程序会自动作为 MATE 的依赖项安装。在 `/etc/rc.conf` 中启用 D-BUS 以在系统启动时启动。

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[mate-start]]
==== 启动 MATE

package:x11/lightdm[] 是一个支持不同显示技术的显示管理器，它非常轻量级，内存使用量少，并且性能快速，是一个很好的选择。

要安装它，请执行以下操作：

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

在 `/etc/rc.conf` 中启用 lightdm 以在系统启动时启动：

[source, shell]
....
# sysrc lightdm_enable="YES"
....

启动 MATE 的第二种方法是手动调用 man:startx[1]。为了使其工作，需要在 `~/.xinitrc` 中添加以下行：

[source, shell]
....
% echo "exec ck-launch-session mate-session" > ~/.xinitrc
....

[[cinnamon-environment]]
=== Cinnamon

Cinnamon 是一个 UNIX(R) 桌面环境，提供先进的创新功能和传统的用户体验。桌面布局类似于 Gnome 2。底层技术是从 Gnome Shell 分叉出来的。重点是让用户感到宾至如归，并为他们提供易于使用和舒适的桌面体验。

[[cinnamon-install]]
==== 安装 Cinnamon

要安装 Cinnamon 软件包，请执行以下操作：

[source, shell]
....
# pkg install cinnamon
....

[[cinnamon-configuration]]
==== 配置 Cinnamon

Cinnamon 需要挂载 `/proc`。在系统启动时自动挂载该文件系统，请将以下行添加到 `/etc/fstab` 文件中：

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

Cinnamon 使用 man:dbus-daemon[1] 作为消息总线和硬件抽象层。这个应用程序会自动作为 Cinnamon 的依赖项安装。在 `/etc/rc.conf` 中启用 D-BUS 以在系统启动时启动它：

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[cinnamon-start]]
==== 启动 Cinnamon

package:x11/lightdm[] 是一个支持不同显示技术的显示管理器，它非常轻量级，内存使用量少，并且性能快速，是一个很好的选择。

要安装它，请执行以下操作：

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

在 `/etc/rc.conf` 中启用 lightdm 以在系统启动时启动：

[source, shell]
....
# sysrc lightdm_enable="YES"
....

启动 Cinnamon 的第二种方法是手动调用 man:startx[1]。为了使其工作，需要在 `~/.xinitrc` 中添加以下行：

[source, shell]
....
% echo "exec ck-launch-session cinnamon-session" > ~/.xinitrc
....

[[lxqt-environment]]
=== LXQT

LXQt 是一个基于 Qt 技术的先进、易于使用和快速的桌面环境。它专为那些重视简洁、速度和直观界面的用户量身定制。与大多数桌面环境不同，LXQt 在性能较低的机器上也能良好运行。

[[lxqt-install]]
==== 安装 LXQT

要安装 LXQT 元包，请执行以下操作：

[source, shell]
....
# pkg install lxqt
....

[[lxqt-configuration]]
==== 配置 LXQT

LXQT 需要挂载 `/proc` 。在系统启动时自动挂载该文件系统，请将以下行添加到 `/etc/fstab` 文件中：

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

LXQT 使用 man:dbus-daemon[1] 作为消息总线和硬件抽象的工具。这个应用程序会自动作为 LXQT 的依赖项进行安装。

在 `/etc/rc.conf` 中启用 D-BUS 以在系统启动时启动：

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[lxqt-start]]
==== 启动 LXQT

首选的 LXQT 显示管理器是 package:x11/sddm[]。要安装 package:x11/sddm[]，请执行以下操作：

[source, shell]
....
# pkg install sddm
....

在 `/etc/rc.conf` 中启用 SDDM 服务以在系统启动时启动：

[source, shell]
....
# sysrc sddm_enable="YES"
....

在 SDDM 中，可以通过运行以下命令来设置键盘语言（例如，对于西班牙语）：

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

启动 LXQT 的第二种方法是手动调用 man:startx[1]。为了使其工作，需要在 `~/.xinitrc` 中添加以下行：

[source, shell]
....
% echo "exec ck-launch-session startlxqt" > ~/.xinitrc
....

[[desktop-browsers]]
== 浏览器

本节介绍了如何在 FreeBSD 系统上安装和配置一些流行的网络浏览器，从资源消耗较高的完整网络浏览器到资源使用较少的命令行网络浏览器。

.支持的浏览器
[options="header", cols="1,1,1,1"]
|===
| 名称 | 许可证 | 包 | 所需资源

| Firefox
| MPL 2.0
| package:www/firefox[]
| Heavy

| Chromium
| BSD-3 and others
| package:www/chromium[]
| Heavy

| Iridium browser
| BSD-3 and others
| package:www/iridium-browser[]
| Heavy

| Falkon
| MPL 2.0
| package:www/falkon-qtonly[]
| Heavy

| Konqueror
| GPL 2.0 or later
| package:x11-fm/konqueror[]
| Medium

| Gnome Web (Epiphany)
| GPL 3.0 or later
| package:www/epiphany[]
| Medium

| qutebrowser
| GPL 3.0 or later
| package:www/qutebrowser[]
| Medium

| Dillo
| GPL 3.0 or later
| package:www/dillo[]
| Light

| Links
| GPL 2.0 or later
| package:www/links[]
| Light

| w3m
| MIT
| package:www/w3m[]
| Light

|===

[[firefox]]
=== Firefox

Firefox 是一个开源浏览器，具有符合标准的 HTML 显示引擎、选项卡浏览、弹窗阻止、扩展功能、增强的安全性等特点。Firefox 基于 Mozilla 代码库开发。

要安装最新发布版本的 Firefox 软件包，请执行以下操作：

[source, shell]
....
# pkg install firefox
....

要安装 Firefox Extended Support Release (ESR) 版本，执行以下操作：

[source, shell]
....
# pkg install firefox-esr
....

[[chromium]]
=== Chromium

Chromium 是一个开源的浏览器项目，旨在构建更安全、更快速、更稳定的网络浏览体验。Chromium 具有标签式浏览、弹窗拦截、扩展等功能。 Chromium 是 Google Chrome 浏览器基于的开源项目。

要安装 Chromium ，请执行以下操作：

[source, shell]
....
# pkg install chromium
....

[NOTE]
====
Chromium 的可执行文件是 [.filename]#/usr/local/bin/chrome# ，而不是 [.filename]/usr/local/bin/chromium#。
====

[[iridium]]
=== Iridium browser

Iridium 是一个免费、开放和自由的浏览器修改版本，基于 Chromium 代码库，通过增强隐私保护在几个关键领域进行改进。禁止自动传输部分查询、关键词和指标到中央服务，只有在获得同意的情况下才会发生传输。

要安装 Iridium ，请执行以下操作：

[source, shell]
....
# pkg install iridium-browser
....

[[falkon]]
=== Falkon

Falkon 是一个新近推出的非常快速的 QtWebEngine 浏览器。它旨在成为一款轻量级的适用于所有主要平台的网络浏览器。 Falkon 具备您从一个网络浏览器所期望的所有标准功能。它包括书签、历史记录（两者都在侧边栏中）和选项卡。除此之外，您还可以使用内置的 AdBlock 插件屏蔽广告，使用 Click2Flash 屏蔽 Flash 内容，并使用 SSL 管理器编辑本地 CA 证书数据库。

要安装 Falkon ，请执行以下操作：

[source, shell]
....
# pkg install falkon
....

[[konqueror]]
=== Konqueror

Konqueror 不仅是一个网页浏览器，还是一个文件管理器和多媒体查看器。它支持 WebKit ，这是许多现代浏览器（包括 Chromium ）使用的渲染引擎，同时也支持自己的 KHTML 引擎。

要安装 Konqueror ，请执行以下操作：

[source, shell]
....
# pkg install konqueror
....

[[gnome-web-epiphany]]
=== Gnome Web (Epiphany)

Gnome Web （Epiphany）是一个旨在尽可能轻量和快速的网络浏览器，但牺牲了其他浏览器中的许多功能。

要安装 Gnome Web（Epiphany），执行以下操作：

[source, shell]
....
# pkg install epiphany
....

[[qutebrowser]]
=== qutebrowser

Qutebrowser 是一个以键盘为重点的浏览器，具有简洁的图形用户界面。它基于 Python 和 PyQt5，是一款自由软件，根据 GPL 许可证发布。

要安装 qutebrowser ，请执行以下操作：

[source, shell]
....
# pkg install qutebrowser
....

[[dillo]]
=== Dillo

Dillo 旨在成为一个跨平台的替代浏览器，它小巧、稳定、开发者友好、易用、快速和可扩展。这个新的实验版本的 Dillo 基于 FLTK 工具包，而不是 GTK1，并且已经进行了大量的重写。

要安装 Dillo，请执行以下操作：

[source, shell]
....
# pkg install dillo
....

[[links]]
=== Links

一个类似 lynx-like 的网络浏览器，具有文本和图形模式，具有许多功能，如显示表格、菜单等。

要安装 Links ，请执行以下操作：

[source, shell]
....
# pkg install links
....

[[w3m]]
=== w3m

w3m 是基于页面/文本的网络浏览器。它与 Lynx 类似，但具有 Lynx 没有的几个功能，如渲染表格和渲染框架。

要安装 w3m，请执行以下操作：

[source, shell]
....
# pkg install w3m
....

[[desktop-development]]
== 开发工具

本节介绍了如何在 FreeBSD 系统上安装和配置一些流行的开发工具。

.支持的开发工具
[options="header", cols="1,1,1,1"]
|===
| 名称 | 许可证 | 包 | 所需资源

| Visual Studio Code
| MIT
| package:editors/vscode[]
| Heavy

| Qt Creator
| QtGPL
| package:devel/qtcreator[]
| Heavy

| Kdevelop
| GPL 2.0 or later and LGPL 2.0 or later
| package:devel/kdevelop[]
| Heavy

| Eclipse IDE
| EPL
| package:java/eclipse[]
| Heavy

| Vim
| VIM
| package:editors/vim[]
| Light

| Neovim
| Apache 2.0
| package:editors/neovim[]
| Light

| GNU Emacs
| GPL 3.0 or later
| package:editors/emacs[]
| Light

|===

[[vs-code]]
=== Visual Studio Code

Visual Studio Code 是一种工具，它将代码编辑器的简洁性与开发人员在 编辑-构建-调试 核心循环中所需的功能结合在一起。它提供全面的编辑和调试支持，可扩展性模型以及与现有工具的轻量级集成。

要安装 Visual Studio Code ，请执行以下操作：

[source, shell]
....
# pkg install vscode
....

[[qt-creator]]
=== Qt Creator

Qt Creator 是一个跨平台的集成开发环境（IDE），专为 Qt 开发人员的需求而设计。Qt Creator 包含的功能有：

* 支持 C ++、 QML 和 ECMAscript 的代码编辑器；
* 快速代码导航工具；
* 实时代码检查和样式提示；
* 上下文敏感帮助；
* 可视化调试器；
* 集成的 GUI 布局和表单设计工具。

要安装 Qt Creator ，请执行以下操作：

[source, shell]
....
# pkg install qtcreator
....

[[kdevelop]]
=== kdevelop

开源、功能丰富、可扩展插件的 C/C ++和其他编程语言的集成开发环境。它基于 KDevPlatform、KDE 和 Qt 库进行开发，并自 1998 年以来一直在不断发展。

要安装 kdevelop ，请执行以下操作：

[source, shell]
....
# pkg install kdevelop
....

[[eclipse]]
=== Eclipse IDE

Eclipse 平台是一个开放的可扩展的集成开发环境（IDE），可以用于任何事情，但又没有特定的限制。Eclipse 平台提供了构建和运行集成软件开发工具的基础和组件。Eclipse 平台允许工具开发者独立地开发与其他人的工具集成的工具。

要安装 Eclipse IDE ，请执行以下操作：

[source, shell]
....
# pkg install eclipse
....

[[vim]]
=== Vim

Vim 是一个高度可配置的文本编辑器，旨在实现高效的文本编辑。它是 vi 编辑器的改进版本，大多数 UNIX 系统都配备了 vi 编辑器。

Vim 通常被称为“程序员的编辑器”，对于编程非常有用，以至于许多人认为它是一个完整的集成开发环境（IDE）。然而， Vim 不仅适用于程序员。 Vim 非常适合各种文本编辑，从撰写电子邮件到编辑配置文件都可以。

要安装 Vim ，请执行以下命令：

[source, shell]
....
# pkg install vim
....

[[neovim]]
=== Neovim

Neovim 是编辑器 package:editors/vim[] 的一个积极的重构版本。它对代码库进行了彻底的改进，包括合理的默认设置、内置终端仿真器、异步插件架构和为速度和可扩展性而设计的强大 API 。它与几乎所有的 Vim 插件和脚本保持完全兼容。

要安装 Neovim ，请执行以下操作：

[source, shell]
....
# pkg install neovim
....

[[gnu-emacs]]
=== GNU Emacs

GNU Emacs 是一个可扩展、可定制、自由/开源的文本编辑器。其核心是一个用于解释 Emacs Lisp 的解释器，Emacs Lisp 是一种 Lisp 编程语言的方言，具有支持文本编辑的扩展功能。

要安装 GNU Emacs ，请执行以下操作：

[source, shell]
....
# pkg install emacs
....

[[desktop-productivity]]
== 桌面办公生产力

当谈到生产力时，用户通常会寻找一个办公套件或易于使用的文字处理软件。虽然一些桌面环境（如 KDE Plasma ）提供了一个办公套件，但没有默认的生产力软件包。无论安装的桌面环境如何，FreeBSD 都提供了几个办公套件和图形化文字处理软件。

本节演示了如何安装以下流行的生产力软件，并指出应用程序是否资源密集型，从 ports 编译需要时间，或者是否有任何重要的依赖关系。

.支持的桌面办公生产力套件
[options="header", cols="1,1,1,1"]
|===
| 名称 | 许可证 | 包 | 所需资源

| LibreOffice
| MPL 2.0
| package:editors/libreoffice[]
| Heavy

| Calligra Suite
| LGPL and GPL
| package:editors/calligra[]
| Medium

| AbiWord
| GPL 2.0 or later
| package:editors/abiword[]
| Medium

|===

[[libreoffice]]
=== LibreOffice

LibreOffice 是由 http://www.documentfoundation.org/[The Document Foundation] 开发的免费软件办公套件。它与其他主要办公套件兼容，并可在多种平台上使用。它是 Apache OpenOffice 的重新品牌分支，包括完整办公生产力套件中的应用程序：文字处理器、电子表格、演示文稿管理器、绘图程序、数据库管理程序以及用于创建和编辑数学公式的工具。它提供多种不同语言版本，并将国际化扩展到界面、拼写检查和字典。有关 LibreOffice 的更多信息，请访问 http://www.libreoffice.org/[libreoffice.org] 。

要安装 LibreOffice ，请执行以下操作：

[source, shell]
....
# pkg install libreoffice
....

LibreOffice 软件包默认只提供英文版本。要使用本地化的 LibreOffice 版本，需要安装语言包。例如，要安装西班牙语本地化版本，需要使用以下命令安装软件包：package:editors/libreoffice-es[]。

[source, shell]
....
# pkg install libreoffice-es
....

[[calligra]]
=== Calligra

KDE Plasma 桌面环境包含一个办公套件，可以单独从 KDE Plasma 中安装。 Calligra 包括其他办公套件中常见的标准组件。 Words 是文字处理器， Sheets 是电子表格程序， Stage 用于管理幻灯片演示，而 Karbon 用于绘制图形文档。

要安装 Calligra，请执行以下操作：

[source, shell]
....
# pkg install calligra
....

[[abiword]]
=== AbiWord

AbiWord 是一个免费的文字处理程序，外观和感觉类似于 Microsoft(R) Word。它运行速度快，拥有许多功能，并且用户友好。

AbiWord 可以导入或导出许多文件格式，包括一些专有格式，如 Microsoft(R) 的 [.filename]#.rtf# 格式。

要安装 AbiWord ，请执行以下操作：

[source, shell]
....
# pkg install abiword
....

[[desktop-viewers]]
== 文档查看器

自从 UNIX(R) 问世以来，一些新的文档格式已经变得流行起来，而这些格式所需的查看器可能在基本系统中不可用。本节介绍如何安装以下文档查看器：

.支持的文档查看器
[options="header", cols="1,1,1,1"]
|===
| 名称 | 许可证 | 包 | 所需资源

| Okular
| GPL 2.0
| package:graphics/okular[]
| Heavy

| Evince
| GPL 2.0
| package:graphics/evince[]
| Medium

| ePDFView
| GPL 2.0
| package:graphics/epdfview[]
| Medium

| Xpdf
| GPL 2.0
| package:graphics/xpdf[]
| light

|===

[[okular]]
=== Okular

Okular 是一个通用的文档查看器，是 KDE Plasma 项目的一部分。

Okular 结合了出色的功能性和支持不同类型文档的多样性，如 PDF、Postscript、DjVu、CHM、XPS、ePub 等。

要安装 Okular，请执行以下操作：

[source, shell]
....
# pkg install okular
....

[[evince]]
=== Evince

Evince 是一个支持多种文档格式的文档查看器，包括 PDF 和 Postscript。它是 GNOME 项目的一部分。Evince 的目标是用一个简单的应用程序取代 ggv 和 gpdf 等文档查看器。

要安装 Evince，请执行以下操作：

[source, shell]
....
# pkg install evince
....

[[epdfview]]
=== ePDFView

ePDFView 是一个轻量级的 PDF 文档查看器，只使用 Gtk +和 Poppler 库。ePDFView 的目标是创建一个简单的 PDF 文档查看器，类似于 Evince，但不使用 GNOME 库。

要安装 ePDFView，请执行以下操作：

[source, shell]
....
# pkg install epdfview
....

[[xpdf]]
=== Xpdf

对于喜欢小型 FreeBSD PDF 阅读器的用户，Xpdf 提供了一个轻量级和高效的阅读器，需要很少的资源。它使用标准的 X 字体，不需要任何额外的工具包。

要安装 Xpdf，请执行以下操作：

[source, shell]
....
# pkg install xpdf
....

[[desktop-finance]]
== 金融

在 FreeBSD 桌面上管理个人财务，可以安装一些强大且易于使用的应用程序。其中一些应用程序与广泛使用的文件格式兼容，例如 Quicken 和 Excel 使用的格式。

本节涵盖以下程序：

.支持的金融程序
[options="header", cols="1,1,1,1"]
|===
| 名称 | 许可证 | 包 | 所需资源

| KMyMoney
| GPL 2.0
| package:finance/kmymoney[]
| Heavy

| GnuCash
| GPL 2.0 and GPL 3.0
| package:finance/gnucash[]
| Heavy

|===

[[kmymoney]]
=== KMyMoney

KMyMoney 是由 KDE 社区创建的个人财务应用程序。KMyMoney 旨在提供商业个人财务管理应用程序中的重要功能。它还强调易用性和正确的复式记账。KMyMoney 可以导入标准的 Quicken QIF 文件，跟踪投资，处理多种货币，并提供丰富的报告。

要安装 KMyMoney，请执行以下操作：

[source, shell]
....
# pkg install kmymoney
....

[[gnucash]]
=== GnuCash

GnuCash 是 GNOME 努力提供给最终用户的用户友好且功能强大的应用程序的一部分。GnuCash 可以用于跟踪收入和支出、银行账户和股票。它具有直观的界面，同时保持专业性。

GnuCash 提供了智能账户注册表、分层的账户系统以及许多键盘加速器和自动完成方法。它可以将单个交易拆分为多个更详细的部分。 GnuCash 可以导入和合并 Quicken QIF 文件。它还处理大多数国际日期和货币格式。

要安装 GnuCash ，请执行以下操作：

[source, shell]
....
# pkg install gnucash
....
