---
description: 'FreeBSD 手册参考文献'
next: books/handbook/eresources
part: '第五部分 . 附录'
path: /books/handbook/
prev: books/handbook/mirrors
showBookMenu: true
tags: ["appendix", "bibliography", "handbook", "books", "guides", "security", "periodicals", "journals", "magazines"]
title: '附录 B. 参考文献'
weight: 42
---

[appendix]
[[bibliography]]
= 参考文献
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: B
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/bibliography/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[] include::shared/{{% lang %}}/teams.adoc[] include::shared/{{% lang %}}/mailing-lists.adoc[] include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

虽然手册为 FreeBSD 操作系统的各个组件提供了确切的参考，但它们很少说明如何将这些组件组合起来以使整个操作系统顺利运行。因此，没有什么能替代一本关于 UNIX(R) 系统管理的好书或用户手册。

[[bibliography-freebsd]]
== FreeBSD 参考文献

* 《绝对 FreeBSD ： FreeBSD 完全指南》，第三版，由 link:https://nostarch.com/absfreebsd3[No Starch Press] 出版， 2018 年。 ISBN ： 978-1593278922 。
* 《 FreeBSD Mastery: 存储基础》是由 Tilted Windmill Press 于 2014 年出版的图书。 ISBN 号为 978-1642350098 。
* 《 FreeBSD Mastery: Specialty Filesystems 》是由 Tilted Windmill Press 于 2015 年出版的图书。 ISBN 号为 978-1642350111 。
* 《 FreeBSD Mastery: ZFS 》是由 Tilted Windmill Press 于 2015 年出版的图书。 ISBN 号为 978-1642350005 。
* 《 FreeBSD Mastery: Advanced ZFS 》是由 Tilted Windmill Press 于 2016 年出版的图书。 ISBN 号为 978-0692688687 。
* 《 FreeBSD Mastery: Jails 》是由 Tilted Windmill Press 于 2019 年出版的图书。 ISBN 号为 978-1642350241 。
* 《 FreeBSD 设备驱动程序：勇敢者指南》是由 No Starch Press 于 2012 年出版的。 ISBN ： 978-1593272043 。
* 《 Freebsd 操作系统的设计与实现》第二版，由 Pearson Education , Inc. 于 2014 年出版。 ISBN ： 978-0321968975 。
* 《 UNIX 和 Linux 系统管理手册》，第五版，由 Pearson Education , Inc. 出版， 2017 年。 ISBN ： 978-0134277554 。
* 《设计 BSD Rootkits 》，由 No Starch Press 于 2007 年出版。 ISBN ： 978-1593271428 。
* *FreeBSD 使用 VNET 的 Jails* ，发布在 [gumroad](https://rderik.gumroad.com/l/uwOLZ) 上。

[[bibliography-security]]
== 安全参考

* 《 PF 之书： OpenBSD 防火墙的无废话指南》第三版，由 No Starch Press 于 2014 年出版。 ISBN ： 978-1593275891 。
* 《 SSH 精通： OpenSSH 、 PuTTY 、隧道和密钥》，第二版， 2018 年。 ISBN ： 978-1642350029 

[[bibliography-history]]
== UNIX(R) 历史

* 狮子，约翰 _狮子对 UNIX 的评论，第 6 版，附源代码_. ITP 媒体集团， 1996 年。 ISBN 1573980137
* Raymond , Eric S. 《新黑客词典，第三版》。 MIT 出版社， 1996 年。 ISBN 0-262-68092-0 。也被称为 http://www.catb.org/ ~ esr/jargon/html/index.html[Jargon File] 。
* Salus , Peter H. 《 UNIX 的四分之一个世纪》。 Addison-Wesley 出版公司， 1994 年。 ISBN 0-201-54777-5 。
* Simon Garfinkel , Daniel Weise , Steven Strassmann. 《 UNIX-HATERS 手册》。 IDG Books Worldwide , Inc. ， 1994 年。 ISBN 1-56884-203-1 。已绝版，但可在 http://www.simson.net/ref/ugh.pdf[在线] 获取。
* Don Libes ， Sandy Ressler 《与 UNIX 共度的生活》 - 特别版。 Prentice-Hall ， Inc. ， 1989 年。 ISBN 0-13-536657-7
* _BSD 家族树_. 在 FreeBSD 机器上，可以通过链接 https://cgit.freebsd.org/src/tree/share/misc/bsd-family-tree[https://cgit.freebsd.org/src/tree/share/misc/bsd-family-tree] 或链接 file://localhost/usr/share/misc/bsd-family-tree[/usr/share/misc/bsd-family-tree] 来查看。
* 网络化的计算机科学技术报告库。
* 计算机系统研究组（ CSRG ）的旧版 BSD 发布。 http://www.mckusick.com/csrg/ ：这套 4CD 包含了从 1BSD 到 4.4BSD 和 4.4BSD-Lite2 的所有 BSD 版本（不包括 2.11BSD ，遗憾）。最后一张光盘还包含了最终的源代码和 SCCS 文件。
* Kernighan , Brian _Unix: A History and a Memoir_. Kindle Direct Publishing , 2020. ISBN 978-169597855-3

[[bibliography-journals]]
== 期刊、杂志和期刊

* https://www.admin-magazin.de/ [Admin Magazin] （德语），由 Medialinx AG 出版。 ISSN ： 2190-1066
* https://www.bsdnow.tv/ 【 BSD Now - 视频播客】，由 Jupiter Broadcasting LLC 发布
* [FreeBSD Journal] ，由 S & W Publishing 出版，由 FreeBSD Foundation 赞助。 ISBN ： 978-0-615-88479-0 。
