---
description: '本章介绍 FreeBSD 项目的各个方面，如历史、目标、开发模式等。'
next: books/handbook/bsdinstall
part: '第一部分 入门'
path: /books/handbook/
prev: books/handbook/parti
showBookMenu: 'true'
tags: '["introduction", "synopsis", "about", "Who Uses FreeBSD", "goals", "history"]'
title: '第 1 章 导言导言'
weight: 3
---

[[introduction]]
= 导言
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/introduction/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[] include::shared/{{% lang %}}/teams.adoc[] include::shared/{{% lang %}}/mailing-lists.adoc[] include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[introduction-synopsis]]
== 简介

感谢您对 FreeBSD 的关注！下面的章节将介绍 FreeBSD 项目的各个方面，如历史、目标、开发模式等。

读完本章，你就会知道

* FreeBSD 与其他计算机操作系统的关系。
* FreeBSD 项目的历史。
* FreeBSD 项目的目标
* FreeBSD 开放源码开发模式的基础知识。
* 当然还有："FreeBSD "名称的由来。

[[nutshell]]
== 欢迎来到 FreeBSD！

FreeBSD 是一种开源的、符合标准的 Unix 类操作系统，适用于 x86（32 位和 64 位）、ARM、AArch64、RISC-V、POWER 和 PowerPC 计算机。 它提供了时下理所当然的所有功能，如抢占式多任务、内存保护、虚拟内存、多用户设施、SMP 支持、适用于不同语言和框架的所有开源开发工具，以及以 X Window System、KDE 或 GNOME 为中心的桌面功能。 它的特别优势在于

* 自由开放源代码许可_，它授予您自由修改和扩展其源代码的权利，并将其纳入开放源代码项目和封闭产品中，而不会施加典型的版权许可限制，同时也避免了潜在的许可不兼容问题。
* 强大的 TCP/IP 网络_ - FreeBSD 实现了性能和可扩展性不断提高的工业标准协议。这使它成为服务器和路由/防火墙角色的理想选择 - 事实上，许多公司和供应商正是为此目的而使用它的。
* 完全集成的 OpenZFS 支持，包括 root-on-ZFS、ZFS 启动环境、故障管理、管理授权、对 jails 的支持、FreeBSD 专用文档和系统安装程序支持。
* 从强制访问控制框架到 Capsicum 能力和沙盒机制，具有广泛的安全功能。
* 超过 3 万个预编译软件包_适用于所有支持的架构，而 Ports Collection 可让您轻松创建自己的定制软件包。
* _Documentation_ - 除了涵盖从系统管理到内核内部等各种主题的手册和不同作者的书籍外，还有 man:man[1] 页面，不仅包括用户空间守护进程、实用程序和配置文件，还包括内核驱动程序 API（第 9 节）和单个驱动程序（第 4 节）。
* _简单一致的版本库结构和联编系统_ - FreeBSD 的所有组件，无论是内核还是用户空间，都使用单一的版本库。这一点，再加上统一的、易于定制的联编系统，以及深思熟虑的开发流程，使得 FreeBSD 能够很容易地集成到您自己产品的联编基础架构中。
* 忠于 Unix 理念，倾向于可组合性，而不是具有硬编码行为的 "一体化 "守护进程。
* 与 Linux 的_二进制兼容_，这样就可以运行许多 Linux 二进制程序，而无需虚拟化。

FreeBSD 基于加州大学伯克利分校计算机系统研究组 (CSRG) 的 4.4BSD-Lite 版本，继承了 BSD 系统开发的优良传统。 除了 CSRG 提供的出色工作外，FreeBSD 项目还投入了成千上万的工时来扩展功能和微调系统，以便在实际负载情况下实现最高的性能和可靠性。 FreeBSD 的性能和可靠性与其他开源软件和商业软件不相上下，并具有其他任何地方都不具备的尖端功能。

[[os-overview]]
=== FreeBSD 能做什么？

FreeBSD 可以应用的领域非常广泛，这完全取决于您的想象力。 从软件开发到工厂自动化，从库存控制到远程卫星天线的方位角校正，只要是商业 UNIX(R)产品能做到的，FreeBSD 就一定能做到！FreeBSD 还从世界各地的研究中心和大学开发的数以千计的高质量应用程序中获益匪浅，这些应用程序通常只需很少的费用甚至是免费的。

由于 FreeBSD 本身的源代码是免费提供的，因此该系统还可以为特殊的应用程序或项目进行定制，定制的程度几乎是前所未闻的，这也是大多数主要商业供应商的操作系统所无法做到的。 以下是目前人们使用 FreeBSD 的一些应用实例：

* 互联网服务：_ FreeBSD 内置的强大 TCP/IP 网络使其成为各种互联网服务的理想平台，如

** 网络服务器
** IPv4 和 IPv6 路由
** 防火墙和 NAT（"IP 伪装"）网关
** FTP 服务器
** 电子邮件服务器
** 存储服务器
** 虚拟化服务器
** 更多

* _教育背景:_ 您是计算机科学或相关工程领域的学生吗？学习操作系统、计算机体系结构和网络的最好方法莫过于 FreeBSD 所能提供的实际操作经验。一些免费提供的 CAD、数学和图形设计软件包也使 FreeBSD 对那些对计算机的主要兴趣是完成其他工作的人非常有用！
* _Research:_ 由于整个系统的源代码都是可用的， FreeBSD 是研究操作系统和计算机科学其它分支的绝佳平台。FreeBSD 免费提供的特性也使得远程小组可以就一些想法进行合作或共享开发，而不必担心特殊的许可协议或在开放论坛上讨论的限制。
* 网络：_ 需要新的路由器？名称服务器（DNS）？需要防火墙来防止他人进入您的内部网络？FreeBSD 可以轻松地将角落里那台闲置的 PC 变成具有复杂数据包过滤功能的高级路由器。
* 嵌入式：_ FreeBSD 是构建嵌入式系统的绝佳平台。FreeBSD 支持 ARM、AArch64 和 PowerPC 平台，拥有强大的网络堆栈、尖端的功能和许可的 extref:{faq}[BSD 许可证, bsd-license-restrictions] ，是构建嵌入式路由器、防火墙和其他设备的绝佳基础。
* _Desktop:_ FreeBSD 使用免费提供的 X11 服务器和 Wayland 显示服务器，是廉价桌面解决方案的理想选择。FreeBSD 提供了多种开源桌面环境，包括标准的 GNOME 和 KDE 图形用户界面。FreeBSD 甚至可以从中央服务器 "无盘 "启动，使单个工作站的成本更低，管理更方便。
* 软件开发：_ 基本的 FreeBSD 系统带有一整套开发工具，包括完整的 C/C++ 编译器和调试器套件。通过 ports 和 packages 套件还可以支持许多其它语言。

FreeBSD 可以免费下载，也可以通过 CD-ROM 或 DVD 光盘获取。 有关获取 FreeBSD 的更多信息，请参见 crossref:mirrors[镜像，获取 FreeBSD]。

[[introduction-nutshell-users]]
=== 谁在使用 FreeBSD？

FreeBSD 因其网络服务能力而闻名。 在 FreeBSD 基金会的网站上有一个 link:https://freebsdfoundation.org/about-us/testimonials/[基于 FreeBSD 的产品和服务的公司推荐]的列表。 维基百科也有一个 link:https://en.wikipedia.org/wiki/List_of_products_based_on_FreeBSD[基于 FreeBSD 的产品列表]。

[[history]]
== 关于 FreeBSD 项目

下文将介绍项目的一些背景信息，包括项目的简要历史、项目目标和 extref:{dev-model}[开发模式]。

[[intro-history]]
=== FreeBSD 简史

FreeBSD 项目起源于 1993 年初，部分源于非官方 386BSDPatchkit 最后三位协调人的创意：Nate Williams、Rod Grimes 和 Jordan Hubbard。

最初的目标是制作 386BSD 的中间快照，以修复补丁包机制无法解决的一些问题。 因此，项目的早期名称是 386BSD 0.5 或 386BSD Interim。

386BSD 是比尔-约利兹（Bill Jolitz）的操作系统，由于近一年的疏于管理，该系统的运行状况一直非常糟糕。 随着补丁包的日益膨胀，他们决定通过提供临时 "清理 "快照来帮助比尔。 比尔-约利兹（Bill Jolitz）突然决定退出该项目，而且没有明确表示将采取什么措施，因此这些计划戛然而止。

三人认为，即使没有比尔的支持，这个目标仍然值得实现，因此他们采用了大卫-格林曼（David Greenman）创造的 "FreeBSD "这个名字。 在征求了系统现有用户的意见后，乔丹确定了最初的目标。一旦明确该项目即将成为现实，乔丹便联系了核桃溪 CDROM 公司，希望改善 FreeBSD 的发行渠道，让更多无法轻松访问互联网的人也能使用 FreeBSD。 核桃溪 CDROM 不仅支持以光盘发行 FreeBSD 的想法，而且还为该项目提供了工作用的机器和快速的互联网连接。 如果没有 Walnut Creek CDROM 对当时还完全不为人知的 FreeBSD 项目前所未有的信任，FreeBSD 不可能走得这么远，走得这么快。

FreeBSD 1.0 是第一个 CD-ROM 发行版（也是全网发行版），于 1993 年 12 月发布。 它基于加州大学伯克利分校的 4.3BSD-Lite （"Net/2"）磁带，许多组件也由 386BSD 和自由软件基金会提供。 作为首次发布的版本，它取得了相当大的成功，随后他们又于 1994 年 5 月发布了非常成功的 FreeBSD 1.1 版本。

就在此时，Novell 和加州大学伯克利分校就伯克利 Net/2 磁带的法律地位问题的长期诉讼达成了和解。 和解的条件之一是伯克利加州大学让步，Net/2 的三个文件是 "抵押 "代码，必须删除，因为它们是 Novell 的财产，而 Novell 早些时候从 AT&T 收购了 Net/2。 伯克利得到的回报是 Novell 的 "祝福"，即 4.4BSD-Lite 版本最终发布时，将被宣布为非加密版本，并大力鼓励所有现有的 Net/2 用户转换。 包括 FreeBSD 在内，该项目将在 1994 年 7 月底之前停止发布其基于 Net/2 的产品。 根据协议条款，该项目被允许在最后期限之前发布最后一个版本，即 FreeBSD 1.1.5.1。

随后，FreeBSD 开始了一项艰巨的任务，从一套全新的、相当不完整的 4.4BSD-Lite 中重新发明自己。 尽管只有三个与 System V 共享内存和 Semaphores 有关的文件被移除，但 BSD 发行版中还有许多其他的修改和错误修正，因此将所有的 FreeBSD 开发合并到 4.4BSD-Lite 中是一项艰巨的任务。 该项目直到 1994 年 11 月才完成这一过渡，并于 12 月向全世界发布了 FreeBSD 2.0。 尽管还有些粗糙，但这一版本取得了巨大的成功，并在 1995 年 6 月发布了更强大、更易于安装的 FreeBSD 2.0.5 版本。

从那时起，FreeBSD 发布了一系列版本，每次都会在前一版本的稳定性、速度和功能集上进行改进。

目前，{rel-head}-CURRENT（主）分支仍在进行长期的开发项目，{rel-head}的快照版本会随着工作的进展不断从 link:https://download.freebsd.org/snapshots/[快照服务器]发布。

[[goals]]
=== FreeBSD 项目目标

The goals of the FreeBSD Project are to provide software that may be used for any purpose and without strings attached. Many of us have a significant investment in the code (and project) and would certainly not mind a little financial compensation now and then, but we are definitely not prepared to insist on it. We believe that our first and foremost "mission" is to provide code to any and all comers, and for whatever purpose, so that the code gets the widest possible use and provides the widest possible benefit. This is, we believe, one of the most fundamental goals of Free Software and one that we enthusiastically support.

在我们的源代码树中，属于 GNU 通用公共许可证 (GPL) 或图书馆通用公共许可证 (LGPL) 的代码附带的条件稍多一些，但至少是在强制访问方面，而不是通常的相反。 然而，由于 GPL 软件在商业用途上可能会产生额外的复杂性，因此，在合理的情况下，我们更倾向于使用更为宽松的 BSD 许可提交软件。

[[development]]
=== FreeBSD 开发模式

FreeBSD 的开发是一个 extref:{dev-model}[非常开放和灵活的过程]，它是由全世界成千上万的贡献者共同完成的，这一点可以从我们的 extref:{contributors}[贡献者名单] 中看出。 FreeBSD 的开发基础架构允许成千上万的贡献者通过互联网进行协作。 我们一直在寻找新的志愿者，有兴趣的朋友可以参考 extref:{contributing}[对 FreeBSD 的贡献] 一文。

关于 FreeBSD 项目及其开发过程的有用信息，无论是独立工作还是密切合作：

Git 仓库[[development-cvs-repository]]]::
几年来，FreeBSD 的中心源代码树一直由 link:https://www.nongnu.org/cvs/[CVS]（并发版本系统）维护，这是一种免费提供的源代码控制工具。2008 年 6 月，项目转而使用 link:https://www.nongnu.org/cvs/[SVN]（Subversion）。 2008 年 6 月，项目转而使用 link:https://subversion.apache.org/[SVN]（Subversion）。 由于源代码树的快速扩展和已存储的历史记录的数量，CVS 的技术限制已变得非常明显，因此有必要进行切换。 文档项目和 Ports Collection 软件库也分别于 2012 年 5 月和 2012 年 7 月从 CVS 迁移到 SVN。 2020 年 12 月，项目 link:https://www.freebsd.org/status/report-2020-10-2020-12.html#Git-Migration-Working-Group[源代码和文档库迁移]到 link:https://git-scm.com/[Git]，2021 年 4 月 link:https://www.freebsd.org/status/report-2021-04-2021-06/#_git_migration_working_group[端口库效仿]。 请参阅 crossref:cutting-edge[同步， 获取源代码] 部分， 以了解获取 FreeBSD `src/` 代码库的更多信息， 以及 crossref:ports[ports-using, 使用 Ports Collection] 部分， 以了解获取 FreeBSD Ports Collection 的详细信息。

提交者列表[[development-committers]]]::
提交者（committers）是指拥有 Git 仓库的_push_访问权限，并被授权对 FreeBSD 源代码进行修改的人（"提交者 "一词来源于 "commit"，源代码控制命令，用于将新的修改引入仓库）。 任何人都可以提交错误到链接:https://bugs.FreeBSD.org/submit/[错误数据库]。 在提交错误报告之前，可以使用 FreeBSD 邮件列表、IRC 频道或论坛来帮助验证问题是否真的是一个错误。

FreeBSD 核心团队[[开发-核心]]]::
如果 FreeBSD 项目是一家公司，_FreeBSD 核心团队_ 就相当于董事会。 核心团队的主要任务是确保整个项目处于良好的状态，并朝着正确的方向前进。 核心团队的职能之一是邀请有奉献精神和责任心的开发人员加入我们的提交者团队，并在其他核心团队成员离开后招募新的核心团队成员。 目前的核心团队是 2022 年 5 月从提交者候选人中选举产生的。 选举每两年举行一次。
+
[NOTE]
====
和大多数开发者一样，核心团队的大多数成员也是 FreeBSD 开发的志愿者，并不从项目中获得经济利益，因此 "承诺 "也不应该被误解为 "保证支持"。上述 "董事会 "的比喻并不十分准确，更恰当的说法是，这些人放弃了自己的生命，不顾自己的判断而支持 FreeBSD！
====

FreeBSD 基金会::
链接：https://freebsdfoundation.org/[FreeBSD 基金会]是一个 501(c)(3)、总部设在美国的非营利性组织，致力于支持和促进 FreeBSD 项目及全球社区的发展。 基金会通过项目资助的方式为软件开发提供资金，并提供人员立即应对紧急问题，实施新特性和功能。 基金会购买硬件以改善和维护 FreeBSD 基础设施，并为提高测试覆盖率、持续集成和自动化提供资金支持。 基金会在世界各地的技术会议和活动中宣传 FreeBSD。 基金会还提供研讨会、教材和演讲，以招募更多的 FreeBSD 用户和贡献者。 基金会还代表 FreeBSD 项目执行合同、许可协议和其他需要公认法律实体的法律安排。

外部捐助者::
最后，但绝对不是最不重要的，最大的开发者群体是用户本身，他们几乎持续不断地向我们提供反馈和错误修正。 与 FreeBSD 基本系统的开发保持联系的主要方式是订阅讨论此类问题的 {freebsd-hackers} 。 要移植第三方应用程序，可以订阅 {freebsd-ports}。 至于文档--{freebsd-doc}。 有关各种 FreeBSD 邮件列表的更多信息，请参见 crossref:eresources[eresources，互联网上的资源]。
+
extref:{contributors}[FreeBSD 贡献者列表]是一个很长并且在不断成长的列表，为什么不今天就通过 extref:{contributing}[为 FreeBSD 做出贡献]来加入它呢？提供代码并不是唯一的方法！

总之，我们的开发模式是一个松散的同心圆。 这种集中式的开发模式是为了方便 FreeBSD 的用户， 让他们能够方便地跟踪中央代码库， 而不是把潜在的贡献者拒之门外！我们的目标是提供一个稳定的操作系统， 以及一大批连贯的 crossref:ports[ports,应用程序]， 用户可以很容易地安装和使用它们 - 这种模式可以很好地实现这一目标。

我们对愿意加入我们成为 FreeBSD 开发者的人的要求是，他们能像 FreeBSD 目前的员工一样，为 FreeBSD 的持续成功做出奉献！

[[third-party-programs]]
=== 第三方计划

除了基本发行版之外，FreeBSD 还提供了一个移植软件集，其中有数千个常用的程序。 从 HTTP 服务器到游戏、语言、编辑器，以及几乎所有介于两者之间的软件。 大约有 {numports} 个 port；整个 Ports Collection 大约需要 {ports-size} 个 port。 要编译一个 port，只需转到要安装的程序所在的目录，键入 `make install`， 剩下的就交给系统吧。 您编译的每一个 port 的原始文件都是动态获取的， 因此您只需要足够的磁盘空间来编译您想要的 port。

几乎每一个 port 都以预编译的 "软件包 "的形式提供， 不想自己从源代码编译 port 的人可以用一个简单的命令 (`pkg install`) 来安装。 关于软件包和 port 的更多信息， 请参阅 crossref:ports[ports,安装应用程序：软件包和 port]。

=== 补充文件

所有支持的 FreeBSD 版本都在安装程序中提供了一个选项， 在初始系统设置时将附加文档安装到 [.filename]#/usr/local/share/doc/freebsd# 下。 文档也可以稍后使用软件包安装：

[source, shell]
....
# pkg install en-freebsd-doc
....

对于本地化版本，请用所选语言前缀替换 "en"。 请注意，某些本地化版本可能已经过时，可能包含不再正确或相关的信息。 您可以通过以下 URL 使用网络浏览器查看本地安装的手册：

FreeBSD 手册::
`/usr/local/share/doc/freebsd/en/books/handbook/handbook_en.pdf`。

FreeBSD 常见问题::
`/usr/local/share/doc/freebsd/en/books/faq/faq_en.pdf`。

您可以随时在 link:https://docs.FreeBSD.org/[文件门户网站]上找到最新的文件。

所有商标均为其各自所有者的财产。
