---
description: 本章介绍了FreeBSD项目的各个方面，包括其历史、目标、开发模型等等。
next: books/handbook/bsdinstall
part: 第一部分：入门指南
path: /books/handbook/
prev: books/handbook/parti
showBookMenu: true
tags: '["introduction", "synopsis", "about", "Who Uses FreeBSD", "goals", "history"]'
title: '第一章. 引言'
weight: 3
---

[[introduction]]
= 介绍
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/introduction/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[] include::shared/{{% lang %}}/teams.adoc[] include::shared/{{% lang %}}/mailing-lists.adoc[] include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[introduction-synopsis]]
== 概要

感谢您对FreeBSD的关注！以下章节涵盖了FreeBSD项目的各个方面，如其历史、目标、开发模型等等。

阅读本章后，您将了解：

* FreeBSD与其他计算机操作系统的关系。
* FreeBSD项目的历史。
* FreeBSD项目的目标。
* FreeBSD开源开发模型的基础知识。
* 当然，还有一个问题：FreeBSD这个名字的由来。

[[nutshell]]
== 欢迎来到FreeBSD！

FreeBSD是一个开源的、符合标准的类Unix操作系统，适用于x86（32位和64位）、ARM、AArch64、RISC-V、POWER和PowerPC计算机。它提供了现在被视为理所当然的所有功能，如抢占式多任务处理、内存保护、虚拟内存、多用户设施、SMP支持、各种语言和框架的开源开发工具，以及以X Window System、KDE或GNOME为中心的桌面功能。它的特点有：

* 自由开源许可证（Liberal Open Source license）赋予您自由修改和扩展其源代码的权利，并将其纳入开源项目和闭源产品中，而不会施加典型的强制共享许可证所具有的限制，同时避免潜在的许可证不兼容问题。
* 强大的TCP/IP网络 - FreeBSD采用行业标准协议，具有越来越高的性能和可扩展性。这使得它在服务器和路由/防火墙角色中都能很好地匹配 - 实际上，许多公司和供应商正是出于这个目的使用它。
* 完全集成的OpenZFS支持，包括root-on-ZFS、ZFS引导环境、故障管理、管理委派、支持jails、FreeBSD特定文档和系统安装程序支持。
* _广泛的安全功能_，从强制访问控制框架到Capsicum能力和沙盒机制。
* 支持所有架构的超过30,000个预构建软件包，以及Ports Collection，使得构建自己定制的软件包变得容易。
* _文档_ - 除了手册和涵盖从系统管理到内核内部的各种主题的不同作者的书籍之外，还有man:man[1]页面，不仅适用于用户空间的守护进程、实用程序和配置文件，还适用于内核驱动程序API（第9节）和单个驱动程序（第4节）。
* 简单而一致的存储库结构和构建系统 - FreeBSD使用一个存储库来管理所有组件，包括内核和用户空间。这个特点，加上统一且易于定制的构建系统以及经过深思熟虑的开发流程，使得将FreeBSD与自己产品的构建基础设施集成变得容易。
* 秉承Unix哲学，更倾向于可组合性，而不是硬编码行为的单体化“一体化”守护程序。
* 与Linux的二进制兼容性，使得在不需要虚拟化的情况下可以运行许多Linux二进制文件。

FreeBSD基于加利福尼亚大学伯克利分校计算机系统研究组（CSRG）的4.4BSD-Lite发布版，并延续了BSD系统开发的卓越传统。除了CSRG提供的出色工作外，FreeBSD项目还投入了数千小时的工作，扩展了功能并对系统进行了精细调整，以在实际负载情况下实现最大性能和可靠性。FreeBSD提供与其他开源和商业产品相当的性能和可靠性，同时结合了其他地方无法获得的尖端功能。

[[os-overview]]
=== FreeBSD可以做什么？

FreeBSD的应用范围几乎只受你的想象力限制。从软件开发到工厂自动化，从库存控制到远程卫星天线的方位校正；如果可以用商业UNIX(R)产品完成，那么很有可能你也可以用FreeBSD来实现！FreeBSD还受益于全球研究中心和大学开发的成千上万个高质量应用程序，通常可以以很低的或者零成本获得。

由于FreeBSD本身的源代码是免费提供的，因此该系统可以根据特定应用或项目的需求进行几乎无与伦比的定制，而这在大多数主要商业供应商的操作系统中通常是不可能的。以下是一些人们目前正在使用FreeBSD的应用程序的示例：

* 互联网服务：FreeBSD内置的强大的TCP/IP网络使其成为各种互联网服务的理想平台，例如：

** Web服务器
** IPv4和IPv6路由
** 防火墙和NAT（"IP伪装"）网关
** FTP服务器
** 电子邮件服务器
** 存储服务器
** 虚拟化服务器
** 还有更多...

* _教育：_ 你是计算机科学或相关工程领域的学生吗？没有比FreeBSD提供的亲身实践、深入了解操作系统、计算机架构和网络更好的学习方式了。还有一些免费的CAD、数学和图形设计软件包，对于那些主要关注计算机用于完成其他工作的人来说，它们也非常有用！
* _研究：_由于整个系统的源代码可用，FreeBSD是操作系统以及计算机科学其他领域研究的优秀平台。FreeBSD的自由可用性也使得远程团队能够在想法或共享开发上进行合作，而无需担心特殊许可协议或在公开论坛上讨论的限制。
* _网络：_ 需要一个新的路由器吗？一个名称服务器（DNS）？一个防火墙来阻止人们进入您的内部网络？FreeBSD可以轻松地将闲置在角落的个人电脑转变为具有复杂数据包过滤功能的高级路由器。
* 嵌入式：FreeBSD是构建嵌入式系统的优秀平台。它支持ARM、AArch64和PowerPC平台，配备强大的网络堆栈、尖端功能和宽松的BSD许可证限制，使FreeBSD成为构建嵌入式路由器、防火墙和其他设备的理想基础。
* _桌面：_ FreeBSD是一个使用免费的X11服务器和Wayland显示服务器的廉价桌面解决方案的不错选择。FreeBSD提供了许多开源桌面环境的选择，包括标准的GNOME和KDE图形用户界面。FreeBSD甚至可以从中央服务器“无盘启动”，使得个人工作站更加便宜和易于管理。
* 软件开发：基本的FreeBSD系统配备了一套完整的开发工具，包括完整的C/C++编译器和调试器套件。通过端口和软件包集合，还可以支持许多其他编程语言。

FreeBSD可以免费下载，也可以通过CD-ROM或DVD获取。有关获取FreeBSD的更多信息，请参阅crossref:mirrors[mirrors, Obtaining FreeBSD]。

[[introduction-nutshell-users]]
=== 谁使用FreeBSD？

FreeBSD以其Web服务器功能而闻名。可以在FreeBSD基金会的网站上找到一份基于FreeBSD的产品和服务的公司的[testimonials列表]。维基百科还维护着一个基于FreeBSD的[产品列表]。

[[history]]
== 关于FreeBSD项目

FreeBSD项目是一个开源的操作系统项目，它基于UNIX操作系统的设计原则和BSD许可证。该项目的目标是提供一个稳定、高性能、可靠的操作系统，适用于各种不同的硬件平台。

FreeBSD项目的发展始于1993年，它由一群志愿者开发和维护。这个项目的核心团队致力于开发和改进FreeBSD操作系统的各个方面，包括内核、驱动程序、网络协议栈、安全性和性能优化等。

FreeBSD操作系统具有许多优点，例如可靠性、稳定性和安全性。它还提供了丰富的软件包管理系统，使用户可以轻松地安装和更新软件。此外，FreeBSD还支持多种架构，包括x86、ARM和PowerPC等。

FreeBSD项目的开发过程是透明和开放的，任何人都可以参与其中。它拥有一个活跃的社区，社区成员之间进行交流和合作，共同推动项目的发展。

总之，FreeBSD项目是一个强大而灵活的操作系统项目，它为用户提供了一个可靠和高性能的平台，适用于各种不同的应用场景。

下面的部分提供了关于项目的一些背景信息，包括简要历史、项目目标以及项目的开发模型。

[[intro-history]]
=== FreeBSD的简要历史

FreeBSD项目诞生于1993年初，部分是由非官方的386BSDPatchkit的最后三位协调员Nate Williams、Rod Grimes和Jordan Hubbard共同构思而成。

最初的目标是生成386BSD的中间快照，以解决一些无法通过补丁机制解决的问题。该项目的早期工作标题是386BSD 0.5或386BSD Interim，以此为参考。

386BSD是Bill Jolitz的操作系统，到那时为止，它已经遭受了将近一年的严重忽视。随着每一天过去，补丁包变得越来越不舒服，他们决定通过提供这个临时的“清理”快照来帮助Bill。然而，当Bill Jolitz突然决定撤回对该项目的支持，并没有明确表示将采取什么替代措施时，这些计划被粗暴地中止了。

即使没有Bill的支持，三人组仍然认为目标仍然值得追求，因此他们采用了David Greenman提出的“FreeBSD”这个名字。在与系统当前用户咨询后，确定了最初的目标。一旦清楚该项目可能成为现实，Jordan便联系了Walnut Creek CDROM，以改善FreeBSD的发行渠道，以便那些没有便捷访问互联网的人。Walnut Creek CDROM不仅支持在光盘上分发FreeBSD，还提供了一台用于开发工作的机器和快速的互联网连接。如果没有Walnut Creek CDROM对当时一个完全未知的项目的几乎前所未有的信任，FreeBSD很可能不会像今天这样迅速取得如此大的进展。

第一张CD-ROM（以及整个网络范围内的）发行版是FreeBSD 1.0，于1993年12月发布。它基于来自加州大学伯克利分校的4.3BSD-Lite（“Net/2”）磁带，同时还借鉴了386BSD和自由软件基金会提供的许多组件。作为首次发布，它取得了相当不错的成功，并在1994年5月发布了备受好评的FreeBSD 1.1版本。

在这个时候，诺维尔（Novell）和加州大学伯克利分校（U.C. Berkeley）就有关伯克利Net/2磁带的法律地位的长期诉讼达成了意外的和解。和解的条件是U.C. Berkeley承认Net/2的三个文件是“受限制”的代码，必须予以删除，因为它们是诺维尔的财产，而诺维尔则是之前从AT&T收购的。作为回报，伯克利获得了诺维尔的“祝福”，即当4.4BSD-Lite版本最终发布时，将被宣布为无限制的，并强烈鼓励所有现有的Net/2用户切换过来。这包括FreeBSD，该项目被给予截止到1994年7月底停止发布基于Net/2的产品的时间。根据协议的条款，该项目在最后期限之前被允许发布最后一个版本，即FreeBSD 1.1.5.1。

FreeBSD随后开始了一项艰巨的任务，从一个全新且相当不完整的4.4BSD-Lite代码库中重新塑造自己。虽然只有与System V共享内存和信号量相关的三个文件被删除，但在BSD发行版中进行了许多其他的更改和错误修复，因此将所有FreeBSD的开发工作合并到4.4BSD-Lite中是一项巨大的任务。该项目直到1994年11月才完成了这一过渡，并在12月向世界发布了FreeBSD 2.0版本。尽管在某种程度上仍然存在一些问题，但这个版本取得了重大的成功，并在1995年6月发布了更稳定、更易安装的FreeBSD 2.0.5版本。

自那时起，FreeBSD每次发布都会改进之前版本的稳定性、速度和功能集。

目前，长期发展项目仍在{rel-head}-CURRENT（主要）分支中进行，并且随着工作的进行，{rel-head}的快照版本将持续从link:https://download.freebsd.org/snapshots/[快照服务器]发布。

[[goals]]
=== FreeBSD项目的目标

FreeBSD项目的目标是提供可用于任何目的且无附加条件的软件。我们中的许多人在代码（和项目）上投入了大量资源，偶尔获得一些财务补偿并不介意，但我们绝对不会坚持要求。我们相信我们的首要任务是向任何人提供代码，无论出于何种目的，以便代码得到最广泛的使用并提供最广泛的利益。我们认为这是自由软件的最基本目标之一，我们对此表示热情支持。

我们源代码树中受GNU通用公共许可证（GPL）或库通用公共许可证（LGPL）约束的代码，附带了稍微更多的限制，尽管至少是在强制访问方面，而不是通常的相反情况。由于商业使用GPL软件可能出现的额外复杂性，我们更喜欢在合理的情况下选择以更宽松的BSD许可证提交的软件。

[[development]]
=== FreeBSD开发模型

FreeBSD的开发是一个非常开放和灵活的过程，从世界各地成千上万的人的贡献中构建而成，这一点可以从我们的贡献者列表中看出来。FreeBSD的开发基础设施允许这些成千上万的贡献者在互联网上进行合作。我们一直在寻找新的志愿者，有兴趣更深入参与的人应该参考有关贡献FreeBSD的文章。

无论是独立工作还是密切合作，以下是关于FreeBSD项目及其开发过程的一些有用信息：

Git仓库[[development-cvs-repository]]::
多年来，FreeBSD的中央源代码树由免费可用的源代码控制工具link:https://www.nongnu.org/cvs/[CVS]（Concurrent Versions System）维护。2008年6月，该项目转而使用link:https://subversion.apache.org/[SVN]（Subversion）。由于源代码树的迅速扩展和已存储的历史记录量，CVS所施加的技术限制变得明显，因此这次转换被认为是必要的。文档项目和端口集合存储库也分别于2012年5月和2012年7月从CVS迁移到了SVN。2020年12月，该项目将源代码和文档存储库迁移到了link:https://git-scm.com/[Git]，而端口集合则在2021年4月跟随。有关获取FreeBSD `src/`存储库的更多信息，请参阅crossref:cutting-edge[synching, Obtaining the Source]部分，有关获取FreeBSD端口集合的详细信息，请参阅crossref:ports[ports-using, Using the Ports Collection]。

贡献者列表[[development-committers]]::
_committers_是那些具有对Git仓库的_push_访问权限的人，他们被授权对FreeBSD源代码进行修改（术语“committer”来自于`commit`，这是用于将新更改引入仓库的源代码控制命令）。任何人都可以提交一个bug到link:https://bugs.FreeBSD.org/submit/[Bug Database]。在提交bug报告之前，可以使用FreeBSD邮件列表、IRC频道或论坛来帮助验证一个问题是否真的是一个bug。

FreeBSD核心团队[[development-core]]::
如果FreeBSD项目是一家公司，那么_FreeBSD核心团队_将相当于董事会。核心团队的主要任务是确保整个项目处于良好状态并朝着正确的方向发展。邀请专注和负责任的开发人员加入我们的提交者团队是核心团队的职责之一，招募新的核心团队成员也是核心团队的职责之一。当前的核心团队是在2022年5月从提交者候选人中选举产生的。选举每2年举行一次。
+
[NOTE]
====
和大多数开发者一样，FreeBSD核心团队的大多数成员在FreeBSD开发方面也是志愿者，并且没有从项目中获得经济利益，所以“承诺”也不应被误解为“有保证的支持”。上面提到的“董事会”类比并不十分准确，更适合说这些人是在违背自己更好判断的情况下选择了FreeBSD而放弃了自己的生活！
====

自由BSD基金会[[开发基金会]]::
链接：https://freebsdfoundation.org/ [FreeBSD基金会] 是一个位于美国的501(c)(3)非营利组织，致力于支持和推广全球的FreeBSD项目和社区。基金会通过项目拨款资助软件开发，并提供员工立即响应紧急问题并实施新功能和功能。基金会购买硬件以改善和维护FreeBSD基础设施，并资助人员提高测试覆盖率、持续集成和自动化。基金会通过在世界各地的技术会议和活动上推广FreeBSD来支持FreeBSD。基金会还提供研讨会、教育材料和演示，以吸引更多的FreeBSD用户和贡献者。基金会还代表FreeBSD项目执行合同、许可协议和其他需要认可法律实体的法律安排。

外部贡献者::
最后，但绝对不是最不重要的，最大的开发者群体是用户自己，他们几乎一直向我们提供反馈和错误修复。与FreeBSD基本系统的开发保持联系的主要方式是订阅{freebsd-hackers}，在这里讨论这些事情。对于移植第三方应用程序，可以使用{freebsd-ports}。对于文档，可以使用{freebsd-doc}。有关各种FreeBSD邮件列表的更多信息，请参见交叉引用：eresources[eresources，互联网资源]。
+
extref:{contributors}[The FreeBSD贡献者列表]是一个长期而不断增长的列表，为什么不通过extref:{contributing}[今天为FreeBSD做出贡献]加入其中呢？提供代码并不是唯一的方式！

总之，我们的开发模型是以一组松散的同心圆组织起来的。中心化模型是为了方便FreeBSD的用户，他们可以通过追踪一个中央代码库来获得便利，而不是为了排斥潜在的贡献者！我们的愿望是提供一个稳定的操作系统，配备一套大量的一致的应用程序，用户可以轻松安装和使用 - 这个模型在实现这一目标方面非常成功。

我们对那些希望加入我们成为FreeBSD开发者的人只有一个要求，那就是拥有与现有成员一样对其持续成功的奉献精神！

[[third-party-programs]]
=== 第三方程序

除了基本发行版之外，FreeBSD还提供了一个移植软件集合，其中包含数千个常见的程序。端口列表涵盖了从HTTP服务器到游戏、编程语言、编辑器等几乎所有领域的程序。大约有{numports}个端口；整个端口集合需要大约{ports-size}的空间。要编译一个端口，只需切换到您想要安装的程序的目录，输入“make install”，然后让系统完成剩下的工作。每个构建的端口都会动态地检索完整的原始发行版，因此您只需要足够的磁盘空间来构建所需的端口。

几乎每个端口也都提供了预编译的“软件包”，不希望从源代码编译自己的端口的用户可以使用简单的命令（`pkg install`）进行安装。有关软件包和端口的更多信息，请参阅crossref:ports[ports，安装应用程序：软件包和端口]。

=== 附加文档

所有支持的FreeBSD版本在安装程序中提供了一个选项，在初始系统设置期间可以安装附加文档到[/usr/local/share/doc/freebsd]。文档也可以在之后使用软件包进行安装：

[source, shell]
....
# pkg install en-freebsd-doc
....

对于本地化版本，请将“en”替换为所选语言的语言前缀。请注意，一些本地化版本可能已过时，可能包含不再正确或相关的信息。您可以使用以下URL在Web浏览器中查看本地安装的手册：

FreeBSD手册::
`/usr/local/share/doc/freebsd/en/books/handbook/handbook_en.pdf` 是一个路径，指向一个名为 `handbook_en.pdf` 的文件，位于 FreeBSD 操作系统的文档目录中。

FreeBSD常见问题解答::
`/usr/local/share/doc/freebsd/en/books/faq/faq_en.pdf` 是一个路径，指向一个名为 `faq_en.pdf` 的文件。

您可以随时在[文档门户](https://docs.FreeBSD.org/)找到最新的文档。

所有商标均为其各自所有者的财产。
